// Generated by pnpm gen (vue-playground) from packages/vue/playground/sections/*.ts. Do not edit by hand.
/**
 * SSR playground — the Vue twin of the React harness. It mounts one section
 * per component, each in its default (closed) state, so the SSR suite can
 * assert a stable server string and the open popovers' teleported markup.
 *
 * A section lives in `sections/<slug>.ts` and says which SSR hazard its
 * component exercises; `test/ssr/<slug>.test.ts` asserts that section's
 * server string on its own. `open` mounts the Dialog and Select popovers to
 * exercise the harder portal/id path.
 */
import { defineComponent, h } from "vue";
import AccordionSection from "./sections/accordion.js";
import AlertSection from "./sections/alert.js";
import AvatarSection from "./sections/avatar.js";
import BadgeSection from "./sections/badge.js";
import ButtonSection from "./sections/button.js";
import CalloutSection from "./sections/callout.js";
import CardSection from "./sections/card.js";
import ChartsSection from "./sections/charts.js";
import CheckboxSection from "./sections/checkbox.js";
import ChipSection from "./sections/chip.js";
import DialogSection from "./sections/dialog.js";
import DividerSection from "./sections/divider.js";
import FieldSection from "./sections/field.js";
import IndicatorSection from "./sections/indicator.js";
import NumberInputSection from "./sections/number-input.js";
import PaginationSection from "./sections/pagination.js";
import PinInputSection from "./sections/pin-input.js";
import ProgressSection from "./sections/progress.js";
import RadioGroupSection from "./sections/radio-group.js";
import SelectSection from "./sections/select.js";
import SkeletonSection from "./sections/skeleton.js";
import SliderSection from "./sections/slider.js";
import SpinnerSection from "./sections/spinner.js";
import SwitchSection from "./sections/switch.js";
import TabsSection from "./sections/tabs.js";
import ToggleSection from "./sections/toggle.js";
import ToggleGroupSection from "./sections/toggle-group.js";

export const App = defineComponent({
  name: "VueSsrApp",
  props: {
    /** Mount the Dialog + Select popovers open (exercises the portal/id path). */
    open: { type: Boolean, default: false },
  },
  setup(props) {
    return () =>
      h("main", {}, [
        h(AccordionSection, { open: props.open }),
        h(AlertSection, { open: props.open }),
        h(AvatarSection, { open: props.open }),
        h(BadgeSection, { open: props.open }),
        h(ButtonSection, { open: props.open }),
        h(CalloutSection, { open: props.open }),
        h(CardSection, { open: props.open }),
        h(ChartsSection, { open: props.open }),
        h(CheckboxSection, { open: props.open }),
        h(ChipSection, { open: props.open }),
        h(DialogSection, { open: props.open }),
        h(DividerSection, { open: props.open }),
        h(FieldSection, { open: props.open }),
        h(IndicatorSection, { open: props.open }),
        h(NumberInputSection, { open: props.open }),
        h(PaginationSection, { open: props.open }),
        h(PinInputSection, { open: props.open }),
        h(ProgressSection, { open: props.open }),
        h(RadioGroupSection, { open: props.open }),
        h(SelectSection, { open: props.open }),
        h(SkeletonSection, { open: props.open }),
        h(SliderSection, { open: props.open }),
        h(SpinnerSection, { open: props.open }),
        h(SwitchSection, { open: props.open }),
        h(TabsSection, { open: props.open }),
        h(ToggleSection, { open: props.open }),
        h(ToggleGroupSection, { open: props.open }),
      ]);
  },
});
