// Generated by pnpm gen (solid-playground) from packages/solid/playground/sections/*.tsx. Do not edit by hand.
/**
 * SSR playground — the Solid twin of the React harness.
 *
 * It mounts one section per component, each in its default (closed) state.
 * A section lives in `sections/<slug>.tsx` and says which SSR hazard its
 * component exercises; `test/ssr/<slug>.ssr.test.tsx` asserts that section's
 * server string on its own.
 *
 * `open` mounts the Dialog and Select popovers open so the SSR test can
 * exercise the portal/id path.
 */
import AccordionSection from "./sections/accordion.jsx";
import AlertSection from "./sections/alert.jsx";
import AngleSliderSection from "./sections/angle-slider.jsx";
import AvatarSection from "./sections/avatar.jsx";
import BadgeSection from "./sections/badge.jsx";
import BarListSection from "./sections/bar-list.jsx";
import ButtonSection from "./sections/button.jsx";
import CalloutSection from "./sections/callout.jsx";
import CardSection from "./sections/card.jsx";
import CarouselSection from "./sections/carousel.jsx";
import ChartsSection from "./sections/charts.jsx";
import CheckboxSection from "./sections/checkbox.jsx";
import ChipSection from "./sections/chip.jsx";
import ColorPickerSection from "./sections/color-picker.jsx";
import ComboboxSection from "./sections/combobox.jsx";
import DatePickerSection from "./sections/date-picker.jsx";
import DialogSection from "./sections/dialog.jsx";
import DividerSection from "./sections/divider.jsx";
import DonutChartSection from "./sections/donut-chart.jsx";
import DrawerSection from "./sections/drawer.jsx";
import FieldSection from "./sections/field.jsx";
import IndicatorSection from "./sections/indicator.jsx";
import MenuSection from "./sections/menu.jsx";
import NumberInputSection from "./sections/number-input.jsx";
import PaginationSection from "./sections/pagination.jsx";
import PinInputSection from "./sections/pin-input.jsx";
import PopoverSection from "./sections/popover.jsx";
import ProgressSection from "./sections/progress.jsx";
import RadioGroupSection from "./sections/radio-group.jsx";
import SelectSection from "./sections/select.jsx";
import SkeletonSection from "./sections/skeleton.jsx";
import SliderSection from "./sections/slider.jsx";
import SparkChartSection from "./sections/spark-chart.jsx";
import SpinnerSection from "./sections/spinner.jsx";
import SplitterSection from "./sections/splitter.jsx";
import SwitchSection from "./sections/switch.jsx";
import TabsSection from "./sections/tabs.jsx";
import TagsInputSection from "./sections/tags-input.jsx";
import ToastSection from "./sections/toast.jsx";
import ToggleSection from "./sections/toggle.jsx";
import ToggleGroupSection from "./sections/toggle-group.jsx";
import TooltipSection from "./sections/tooltip.jsx";

export interface AppProps {
  /** Mount the Dialog + Select popovers open (exercises the portal/id path). */
  open?: boolean;
}

export function App(props: AppProps) {
  return (
    <main>
      <AccordionSection open={props.open ?? false} />
      <AlertSection open={props.open ?? false} />
      <AngleSliderSection open={props.open ?? false} />
      <AvatarSection open={props.open ?? false} />
      <BadgeSection open={props.open ?? false} />
      <BarListSection open={props.open ?? false} />
      <ButtonSection open={props.open ?? false} />
      <CalloutSection open={props.open ?? false} />
      <CardSection open={props.open ?? false} />
      <CarouselSection open={props.open ?? false} />
      <ChartsSection open={props.open ?? false} />
      <CheckboxSection open={props.open ?? false} />
      <ChipSection open={props.open ?? false} />
      <ColorPickerSection open={props.open ?? false} />
      <ComboboxSection open={props.open ?? false} />
      <DatePickerSection open={props.open ?? false} />
      <DialogSection open={props.open ?? false} />
      <DividerSection open={props.open ?? false} />
      <DonutChartSection open={props.open ?? false} />
      <DrawerSection open={props.open ?? false} />
      <FieldSection open={props.open ?? false} />
      <IndicatorSection open={props.open ?? false} />
      <MenuSection open={props.open ?? false} />
      <NumberInputSection open={props.open ?? false} />
      <PaginationSection open={props.open ?? false} />
      <PinInputSection open={props.open ?? false} />
      <PopoverSection open={props.open ?? false} />
      <ProgressSection open={props.open ?? false} />
      <RadioGroupSection open={props.open ?? false} />
      <SelectSection open={props.open ?? false} />
      <SkeletonSection open={props.open ?? false} />
      <SliderSection open={props.open ?? false} />
      <SparkChartSection open={props.open ?? false} />
      <SpinnerSection open={props.open ?? false} />
      <SplitterSection open={props.open ?? false} />
      <SwitchSection open={props.open ?? false} />
      <TabsSection open={props.open ?? false} />
      <TagsInputSection open={props.open ?? false} />
      <ToastSection open={props.open ?? false} />
      <ToggleSection open={props.open ?? false} />
      <ToggleGroupSection open={props.open ?? false} />
      <TooltipSection open={props.open ?? false} />
    </main>
  );
}
