import { accordionRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Accordion",
  slug: "accordion",
  scope: "accordion",
  props: { file: "src/accordion.tsx", type: "ModernoAccordionRootProps" },
  parts: [
    { name: "root", description: "Carries variant and size for every item." },
    { name: "item", description: "One section; holds its trigger and its content." },
    {
      name: "item-trigger",
      description: "The native <button> header that opens and closes its item.",
    },
    {
      name: "item-indicator",
      description: "Optional icon inside the trigger; turns when the item opens.",
    },
    {
      name: "item-content",
      description: "The item's region; its height animates open and closed.",
    },
  ],
  variants: accordionRecipe.variants,
  examples: {
    react: [
      {
        title: "FAQ: one item open at a time, the open one can close",
        code: [
          'import { Accordion } from "@moderno-ui/react";',
          "",
          '<Accordion.Root defaultValue={["shipping"]} collapsible>',
          '  <Accordion.Item value="shipping">',
          "    <Accordion.ItemTrigger>",
          "      How long does shipping take?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Three to five working days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          '  <Accordion.Item value="returns">',
          "    <Accordion.ItemTrigger>",
          "      Can I return an order?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Yes, within 30 days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          "</Accordion.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "FAQ: one item open at a time, the open one can close",
        code: [
          '<script setup lang="ts">',
          'import { Accordion } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Accordion.Root :default-value=\"['shipping']\" collapsible>",
          '    <Accordion.Item value="shipping">',
          "      <Accordion.ItemTrigger>",
          "        How long does shipping take?",
          "        <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "      </Accordion.ItemTrigger>",
          "      <Accordion.ItemContent>Three to five working days.</Accordion.ItemContent>",
          "    </Accordion.Item>",
          '    <Accordion.Item value="returns">',
          "      <Accordion.ItemTrigger>",
          "        Can I return an order?",
          "        <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "      </Accordion.ItemTrigger>",
          "      <Accordion.ItemContent>Yes, within 30 days.</Accordion.ItemContent>",
          "    </Accordion.Item>",
          "  </Accordion.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "FAQ: one item open at a time, the open one can close",
        code: [
          '<script lang="ts">',
          '  import { Accordion } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Accordion.Root defaultValue={["shipping"]} collapsible>',
          '  <Accordion.Item value="shipping">',
          "    <Accordion.ItemTrigger>",
          "      How long does shipping take?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Three to five working days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          '  <Accordion.Item value="returns">',
          "    <Accordion.ItemTrigger>",
          "      Can I return an order?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Yes, within 30 days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          "</Accordion.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "FAQ: one item open at a time, the open one can close",
        code: [
          'import { Accordion } from "@moderno-ui/solid";',
          "",
          '<Accordion.Root defaultValue={["shipping"]} collapsible>',
          '  <Accordion.Item value="shipping">',
          "    <Accordion.ItemTrigger>",
          "      How long does shipping take?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Three to five working days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          '  <Accordion.Item value="returns">',
          "    <Accordion.ItemTrigger>",
          "      Can I return an order?",
          "      <Accordion.ItemIndicator>⌄</Accordion.ItemIndicator>",
          "    </Accordion.ItemTrigger>",
          "    <Accordion.ItemContent>Yes, within 30 days.</Accordion.ItemContent>",
          "  </Accordion.Item>",
          "</Accordion.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
