import { alertRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Alert",
  slug: "alert",
  scope: "alert",
  props: { file: "src/alert.tsx", type: "AlertRootProps" },
  parts: [
    { name: "root" },
    { name: "icon" },
    { name: "content" },
    { name: "title" },
    { name: "description" },
    { name: "action" },
  ],
  variants: alertRecipe.variants,
  examples: {
    react: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/react";',
          'import { TriangleAlert } from "lucide-react";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Warning with an action",
        code: [
          '<script setup lang="ts">',
          'import { Alert, Button } from "@moderno-ui/vue";',
          'import { TriangleAlert } from "lucide-vue-next";',
          "</script>",
          "",
          "<template>",
          '  <Alert.Root variant="warning">',
          "    <Alert.Icon>",
          "      <TriangleAlert aria-hidden />",
          "    </Alert.Icon>",
          "    <Alert.Content>",
          "      <Alert.Title>Card expiring</Alert.Title>",
          "      <Alert.Description>Your card expires next month.</Alert.Description>",
          "      <Alert.Action>",
          '        <Button size="sm" variant="outline">Update card</Button>',
          "      </Alert.Action>",
          "    </Alert.Content>",
          "  </Alert.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Warning with an action",
        code: [
          '<script lang="ts">',
          '  import { Alert, Button } from "@moderno-ui/svelte";',
          '  import { TriangleAlert } from "@lucide/svelte";',
          "</script>",
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">Update card</Button>',
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/solid";',
          'import { TriangleAlert } from "lucide-solid";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
