import { angleSliderRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "AngleSlider",
  slug: "angle-slider",
  scope: "angle-slider",
  props: { file: "src/angle-slider.tsx", type: "ModernoAngleSliderRootProps" },
  parts: [
    { name: "root", description: "Carries size and --angle; holds the dial and the angle field." },
    {
      name: "label",
      description: "Optional; names the dial and the field. Clicking it focuses the thumb.",
    },
    {
      name: "control",
      description: "The round dial you click or drag on; holds the thumb and the marks.",
    },
    { name: "thumb", description: "The needle, role=slider, turned to the angle; takes focus." },
    { name: "marker-group", description: "Optional; holds the marks around the dial." },
    { name: "marker", description: "A tick at one angle." },
    { name: "value-text", description: "Optional; the angle as text." },
  ],
  variants: angleSliderRecipe.variants,
  examples: {
    react: [
      {
        title: "A rotation dial with a number field",
        code: [
          'import { AngleSlider } from "@moderno-ui/react";',
          "",
          "<AngleSlider.Root value={angle} onValueChange={(e) => setAngle(e.value)}>",
          "  <AngleSlider.Label>Rotation</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "  <AngleSlider.HiddenInput />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
      {
        title: "Snap marks every 45°, reached with Shift while dragging",
        code: [
          'import { AngleSlider } from "@moderno-ui/react";',
          "",
          "const marks = [0, 45, 90, 135, 180, 225, 270, 315];",
          "",
          "<AngleSlider.Root defaultValue={90} marks={marks}>",
          "  <AngleSlider.Label>Gradient direction</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "    <AngleSlider.MarkerGroup>",
          "      {marks.map((mark) => (",
          "        <AngleSlider.Marker key={mark} value={mark} />",
          "      ))}",
          "    </AngleSlider.MarkerGroup>",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A rotation dial with a number field",
        code: [
          '<script setup lang="ts">',
          'import { AngleSlider } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <AngleSlider.Root v-model="angle">',
          "    <AngleSlider.Label>Rotation</AngleSlider.Label>",
          "    <AngleSlider.Control>",
          "      <AngleSlider.Thumb />",
          "    </AngleSlider.Control>",
          "    <AngleSlider.Input />",
          "    <AngleSlider.HiddenInput />",
          "  </AngleSlider.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Snap marks every 45°, reached with Shift while dragging",
        code: [
          '<script setup lang="ts">',
          'import { AngleSlider } from "@moderno-ui/vue";',
          "",
          "const marks = [0, 45, 90, 135, 180, 225, 270, 315];",
          "</script>",
          "",
          "<template>",
          '  <AngleSlider.Root :default-value="90" :marks="marks">',
          "    <AngleSlider.Label>Gradient direction</AngleSlider.Label>",
          "    <AngleSlider.Control>",
          "      <AngleSlider.Thumb />",
          "      <AngleSlider.MarkerGroup>",
          '        <AngleSlider.Marker v-for="mark in marks" :key="mark" :value="mark" />',
          "      </AngleSlider.MarkerGroup>",
          "    </AngleSlider.Control>",
          "    <AngleSlider.Input />",
          "  </AngleSlider.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A rotation dial with a number field",
        code: [
          '<script lang="ts">',
          '  import { AngleSlider } from "@moderno-ui/svelte";',
          "",
          "  let angle = $state(45);",
          "</script>",
          "",
          "<AngleSlider.Root bind:value={angle}>",
          "  <AngleSlider.Label>Rotation</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "  <AngleSlider.HiddenInput />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
      {
        title: "Snap marks every 45°, reached with Shift while dragging",
        code: [
          '<script lang="ts">',
          '  import { AngleSlider } from "@moderno-ui/svelte";',
          "",
          "  const marks = [0, 45, 90, 135, 180, 225, 270, 315];",
          "</script>",
          "",
          "<AngleSlider.Root defaultValue={90} {marks}>",
          "  <AngleSlider.Label>Gradient direction</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "    <AngleSlider.MarkerGroup>",
          "      {#each marks as mark (mark)}",
          "        <AngleSlider.Marker value={mark} />",
          "      {/each}",
          "    </AngleSlider.MarkerGroup>",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A rotation dial with a number field",
        code: [
          'import { AngleSlider } from "@moderno-ui/solid";',
          "",
          "<AngleSlider.Root value={angle()} onValueChange={(e) => setAngle(e.value)}>",
          "  <AngleSlider.Label>Rotation</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "  <AngleSlider.HiddenInput />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
      {
        title: "Snap marks every 45°, reached with Shift while dragging",
        code: [
          'import { For } from "solid-js";',
          'import { AngleSlider } from "@moderno-ui/solid";',
          "",
          "const marks = [0, 45, 90, 135, 180, 225, 270, 315];",
          "",
          "<AngleSlider.Root defaultValue={90} marks={marks}>",
          "  <AngleSlider.Label>Gradient direction</AngleSlider.Label>",
          "  <AngleSlider.Control>",
          "    <AngleSlider.Thumb />",
          "    <AngleSlider.MarkerGroup>",
          "      <For each={marks}>{(mark) => <AngleSlider.Marker value={mark} />}</For>",
          "    </AngleSlider.MarkerGroup>",
          "  </AngleSlider.Control>",
          "  <AngleSlider.Input />",
          "</AngleSlider.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
