import { carouselRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Carousel",
  slug: "carousel",
  scope: "carousel",
  props: { file: "src/carousel.tsx", type: "ModernoCarouselRootProps" },
  parts: [
    { name: "root", description: "The region a screen reader calls a carousel; carries size." },
    { name: "item-group", description: "Scrolls the slides and snaps to each page." },
    { name: "item", description: "One slide; takes its index, from 0." },
    { name: "control", description: "Holds the triggers and the indicators in a centred row." },
    { name: "prev-trigger", description: "A button that goes one page back. Off on the first." },
    { name: "next-trigger", description: "A button that goes one page on. Off on the last." },
    { name: "indicator-group", description: "Holds the indicators; arrow keys change page." },
    { name: "indicator", description: "One dot per page; the current one is marked." },
    { name: "autoplay-trigger", description: "Optional; a button that starts and stops autoplay." },
    {
      name: "autoplay-indicator",
      description: "Optional; shows its content while playing, its fallback when paused.",
    },
    { name: "progress-text", description: "Optional; the page as text, like 2 / 5." },
  ],
  variants: carouselRecipe.variants,
  examples: {
    react: [
      {
        title: "Slides with prev, next and one dot per slide",
        code: [
          'import { Carousel } from "@moderno-ui/react";',
          "",
          "<Carousel.Root slideCount={slides.length}>",
          "  <Carousel.ItemGroup>",
          "    {slides.map((slide, index) => (",
          "      <Carousel.Item key={slide.id} index={index}>",
          "        <img src={slide.src} alt={slide.alt} />",
          "      </Carousel.Item>",
          "    ))}",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.PrevTrigger>‹</Carousel.PrevTrigger>",
          "    <Carousel.IndicatorGroup>",
          "      {slides.map((slide, index) => (",
          "        <Carousel.Indicator key={slide.id} index={index} />",
          "      ))}",
          "    </Carousel.IndicatorGroup>",
          "    <Carousel.NextTrigger>›</Carousel.NextTrigger>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
      {
        title: "Two slides a page, playing on its own, with a pause button",
        code: [
          'import { Carousel } from "@moderno-ui/react";',
          "",
          '<Carousel.Root slideCount={slides.length} slidesPerPage={2} spacing="var(--spacing-3)" autoplay>',
          "  <Carousel.ItemGroup>",
          "    {slides.map((slide, index) => (",
          "      <Carousel.Item key={slide.id} index={index}>{slide.title}</Carousel.Item>",
          "    ))}",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.AutoplayTrigger>",
          '      <Carousel.AutoplayIndicator fallback="Play">Pause</Carousel.AutoplayIndicator>',
          "    </Carousel.AutoplayTrigger>",
          "    <Carousel.Context>",
          "      {(carousel) => (",
          "        <Carousel.IndicatorGroup>",
          "          {carousel.pageSnapPoints.map((_, index) => (",
          "            <Carousel.Indicator key={index} index={index} />",
          "          ))}",
          "        </Carousel.IndicatorGroup>",
          "      )}",
          "    </Carousel.Context>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Slides with prev, next and one dot per slide",
        code: [
          '<script setup lang="ts">',
          'import { Carousel } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Carousel.Root :slide-count="slides.length">',
          "    <Carousel.ItemGroup>",
          '      <Carousel.Item v-for="(slide, index) in slides" :key="slide.id" :index="index">',
          '        <img :src="slide.src" :alt="slide.alt" />',
          "      </Carousel.Item>",
          "    </Carousel.ItemGroup>",
          "    <Carousel.Control>",
          "      <Carousel.PrevTrigger>‹</Carousel.PrevTrigger>",
          "      <Carousel.IndicatorGroup>",
          '        <Carousel.Indicator v-for="(slide, index) in slides" :key="slide.id" :index="index" />',
          "      </Carousel.IndicatorGroup>",
          "      <Carousel.NextTrigger>›</Carousel.NextTrigger>",
          "    </Carousel.Control>",
          "  </Carousel.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Two slides a page, playing on its own, with a pause button",
        code: [
          '<script setup lang="ts">',
          'import { Carousel } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Carousel.Root :slide-count="slides.length" :slides-per-page="2" spacing="var(--spacing-3)" autoplay>',
          "    <Carousel.ItemGroup>",
          '      <Carousel.Item v-for="(slide, index) in slides" :key="slide.id" :index="index">{{ slide.title }}</Carousel.Item>',
          "    </Carousel.ItemGroup>",
          "    <Carousel.Control>",
          "      <Carousel.AutoplayTrigger>",
          '        <Carousel.AutoplayIndicator fallback="Play">Pause</Carousel.AutoplayIndicator>',
          "      </Carousel.AutoplayTrigger>",
          '      <Carousel.Context v-slot="{ pageSnapPoints }">',
          "        <Carousel.IndicatorGroup>",
          '          <Carousel.Indicator v-for="(_, index) in pageSnapPoints" :key="index" :index="index" />',
          "        </Carousel.IndicatorGroup>",
          "      </Carousel.Context>",
          "    </Carousel.Control>",
          "  </Carousel.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Slides with prev, next and one dot per slide",
        code: [
          '<script lang="ts">',
          '  import { Carousel } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Carousel.Root slideCount={slides.length}>",
          "  <Carousel.ItemGroup>",
          "    {#each slides as slide, index (slide.id)}",
          "      <Carousel.Item {index}><img src={slide.src} alt={slide.alt} /></Carousel.Item>",
          "    {/each}",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.PrevTrigger>‹</Carousel.PrevTrigger>",
          "    <Carousel.IndicatorGroup>",
          "      {#each slides as slide, index (slide.id)}",
          "        <Carousel.Indicator {index} />",
          "      {/each}",
          "    </Carousel.IndicatorGroup>",
          "    <Carousel.NextTrigger>›</Carousel.NextTrigger>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
      {
        title: "Two slides a page, playing on its own, with a pause button",
        code: [
          '<script lang="ts">',
          '  import { Carousel } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Carousel.Root slideCount={slides.length} slidesPerPage={2} spacing="var(--spacing-3)" autoplay>',
          "  <Carousel.ItemGroup>",
          "    {#each slides as slide, index (slide.id)}",
          "      <Carousel.Item {index}>{slide.title}</Carousel.Item>",
          "    {/each}",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.AutoplayTrigger>",
          "      <Carousel.AutoplayIndicator>",
          "        {#snippet fallback()}Play{/snippet}",
          "        Pause",
          "      </Carousel.AutoplayIndicator>",
          "    </Carousel.AutoplayTrigger>",
          "    <Carousel.Context>",
          "      {#snippet render(carousel)}",
          "        <Carousel.IndicatorGroup>",
          "          {#each carousel().pageSnapPoints as _, index (index)}",
          "            <Carousel.Indicator {index} />",
          "          {/each}",
          "        </Carousel.IndicatorGroup>",
          "      {/snippet}",
          "    </Carousel.Context>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Slides with prev, next and one dot per slide",
        code: [
          'import { Index } from "solid-js";',
          'import { Carousel } from "@moderno-ui/solid";',
          "",
          "<Carousel.Root slideCount={slides.length}>",
          "  <Carousel.ItemGroup>",
          "    <Index each={slides}>",
          "      {(slide, index) => (",
          "        <Carousel.Item index={index}>",
          "          <img src={slide().src} alt={slide().alt} />",
          "        </Carousel.Item>",
          "      )}",
          "    </Index>",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.PrevTrigger>‹</Carousel.PrevTrigger>",
          "    <Carousel.IndicatorGroup>",
          "      <Index each={slides}>{(_, index) => <Carousel.Indicator index={index} />}</Index>",
          "    </Carousel.IndicatorGroup>",
          "    <Carousel.NextTrigger>›</Carousel.NextTrigger>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
      {
        title: "Two slides a page, playing on its own, with a pause button",
        code: [
          'import { Index } from "solid-js";',
          'import { Carousel } from "@moderno-ui/solid";',
          "",
          '<Carousel.Root slideCount={slides.length} slidesPerPage={2} spacing="var(--spacing-3)" autoplay>',
          "  <Carousel.ItemGroup>",
          "    <Index each={slides}>",
          "      {(slide, index) => <Carousel.Item index={index}>{slide().title}</Carousel.Item>}",
          "    </Index>",
          "  </Carousel.ItemGroup>",
          "  <Carousel.Control>",
          "    <Carousel.AutoplayTrigger>",
          '      <Carousel.AutoplayIndicator fallback="Play">Pause</Carousel.AutoplayIndicator>',
          "    </Carousel.AutoplayTrigger>",
          "    <Carousel.Context>",
          "      {(carousel) => (",
          "        <Carousel.IndicatorGroup>",
          "          <Index each={carousel().pageSnapPoints}>",
          "            {(_, index) => <Carousel.Indicator index={index} />}",
          "          </Index>",
          "        </Carousel.IndicatorGroup>",
          "      )}",
          "    </Carousel.Context>",
          "  </Carousel.Control>",
          "</Carousel.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
