import { comboboxRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Combobox",
  slug: "combobox",
  scope: "combobox",
  props: { file: "src/combobox.tsx", type: "ModernoComboboxRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one combobox." },
    { name: "label", description: "Optional; names the input. Clicking it focuses the input." },
    { name: "control", description: "The bordered box; holds the input and its buttons." },
    { name: "input", description: "The text box the user types in; filters the list." },
    {
      name: "trigger",
      description: "Optional; a button at the end of the box that opens the list.",
    },
    {
      name: "clear-trigger",
      description: "Optional; a button that clears the value. Hidden while it is empty.",
    },
    {
      name: "positioner",
      description: "Placed by Ark below the control; never style its layout.",
    },
    { name: "content", description: 'The role="listbox" surface, as wide as the control.' },
    { name: "list", description: "Optional; wraps the items inside the content." },
    { name: "item-group", description: "Optional; a labelled group of items." },
    { name: "item-group-label", description: "The group's heading." },
    { name: "item", description: "One option, from the collection; takes item." },
    { name: "item-text", description: "The option's text." },
    { name: "item-indicator", description: "Shown while the option is picked, like a check." },
    { name: "empty", description: "Shown in the content while the collection is empty." },
  ],
  variants: comboboxRecipe.variants,
  examples: {
    react: [
      {
        title: "A framework picker that filters as the user types",
        code: [
          'import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/react";',
          "",
          'const { contains } = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({ initialItems: frameworks, filter: contains });",
          "",
          "<Combobox.Root collection={collection} onInputValueChange={(e) => filter(e.inputValue)}>",
          "  <Combobox.Label>Framework</Combobox.Label>",
          "  <Combobox.Control>",
          '    <Combobox.Input placeholder="Search frameworks" />',
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        <Combobox.Empty>No frameworks found</Combobox.Empty>",
          "        {collection.items.map((item) => (",
          "          <Combobox.Item key={item.value} item={item}>",
          "            <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        ))}",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
      {
        title: "Several small picks, with a clear button",
        code: [
          'import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/react";',
          "",
          'const { contains } = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({ initialItems: frameworks, filter: contains });",
          "",
          "<Combobox.Root",
          '  size="sm"',
          "  multiple",
          "  collection={collection}",
          "  onInputValueChange={(e) => filter(e.inputValue)}",
          ">",
          "  <Combobox.Label>Frameworks</Combobox.Label>",
          "  <Combobox.Control>",
          "    <Combobox.Input />",
          "    <Combobox.ClearTrigger>×</Combobox.ClearTrigger>",
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        {collection.items.map((item) => (",
          "          <Combobox.Item key={item.value} item={item}>",
          "            <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        ))}",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A framework picker that filters as the user types",
        code: [
          '<script setup lang="ts">',
          'import { Combobox, Portal, useFilter, useListCollection, type ComboboxInputValueChangeDetails } from "@moderno-ui/vue";',
          "",
          'const filters = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({",
          "  initialItems: frameworks,",
          "  filter: (text, query) => filters.value.contains(text, query),",
          "});",
          "const onInputValueChange = (details: ComboboxInputValueChangeDetails) => filter(details.inputValue);",
          "</script>",
          "",
          "<template>",
          '  <Combobox.Root :collection="collection" @input-value-change="onInputValueChange">',
          "    <Combobox.Label>Framework</Combobox.Label>",
          "    <Combobox.Control>",
          '      <Combobox.Input placeholder="Search frameworks" />',
          "      <Combobox.Trigger>▾</Combobox.Trigger>",
          "    </Combobox.Control>",
          "    <Portal>",
          "      <Combobox.Positioner>",
          "        <Combobox.Content>",
          "          <Combobox.Empty>No frameworks found</Combobox.Empty>",
          '          <Combobox.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Combobox.ItemText>{{ item.label }}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        </Combobox.Content>",
          "      </Combobox.Positioner>",
          "    </Portal>",
          "  </Combobox.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Several small picks, with a clear button",
        code: [
          '<script setup lang="ts">',
          'import { Combobox, Portal, useFilter, useListCollection, type ComboboxInputValueChangeDetails } from "@moderno-ui/vue";',
          "",
          'const filters = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({",
          "  initialItems: frameworks,",
          "  filter: (text, query) => filters.value.contains(text, query),",
          "});",
          "const onInputValueChange = (details: ComboboxInputValueChangeDetails) => filter(details.inputValue);",
          "</script>",
          "",
          "<template>",
          "  <Combobox.Root",
          '    size="sm"',
          "    multiple",
          '    :collection="collection"',
          '    @input-value-change="onInputValueChange"',
          "  >",
          "    <Combobox.Label>Frameworks</Combobox.Label>",
          "    <Combobox.Control>",
          "      <Combobox.Input />",
          "      <Combobox.ClearTrigger>×</Combobox.ClearTrigger>",
          "      <Combobox.Trigger>▾</Combobox.Trigger>",
          "    </Combobox.Control>",
          "    <Portal>",
          "      <Combobox.Positioner>",
          "        <Combobox.Content>",
          '          <Combobox.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Combobox.ItemText>{{ item.label }}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        </Combobox.Content>",
          "      </Combobox.Positioner>",
          "    </Portal>",
          "  </Combobox.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A framework picker that filters as the user types",
        code: [
          '<script lang="ts">',
          '  import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/svelte";',
          "",
          '  const filters = useFilter({ sensitivity: "base" });',
          "  const { collection, filter } = useListCollection({",
          "    initialItems: frameworks,",
          "    filter: (text, query) => filters().contains(text, query),",
          "  });",
          "</script>",
          "",
          "<Combobox.Root collection={collection()} onInputValueChange={(e) => filter(e.inputValue)}>",
          "  <Combobox.Label>Framework</Combobox.Label>",
          "  <Combobox.Control>",
          '    <Combobox.Input placeholder="Search frameworks" />',
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        <Combobox.Empty>No frameworks found</Combobox.Empty>",
          "        {#each collection().items as item (item.value)}",
          "          <Combobox.Item {item}>",
          "            <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        {/each}",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
      {
        title: "Several small picks, with a clear button",
        code: [
          '<script lang="ts">',
          '  import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/svelte";',
          "",
          '  const filters = useFilter({ sensitivity: "base" });',
          "  const { collection, filter } = useListCollection({",
          "    initialItems: frameworks,",
          "    filter: (text, query) => filters().contains(text, query),",
          "  });",
          "</script>",
          "",
          "<Combobox.Root",
          '  size="sm"',
          "  multiple",
          "  collection={collection()}",
          "  onInputValueChange={(e) => filter(e.inputValue)}",
          ">",
          "  <Combobox.Label>Frameworks</Combobox.Label>",
          "  <Combobox.Control>",
          "    <Combobox.Input />",
          "    <Combobox.ClearTrigger>×</Combobox.ClearTrigger>",
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        {#each collection().items as item (item.value)}",
          "          <Combobox.Item {item}>",
          "            <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "            <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "          </Combobox.Item>",
          "        {/each}",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A framework picker that filters as the user types",
        code: [
          'import { For } from "solid-js";',
          'import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/solid";',
          "",
          'const filters = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({",
          "  initialItems: frameworks,",
          "  filter: (text, query) => filters().contains(text, query),",
          "});",
          "",
          "<Combobox.Root collection={collection()} onInputValueChange={(e) => filter(e.inputValue)}>",
          "  <Combobox.Label>Framework</Combobox.Label>",
          "  <Combobox.Control>",
          '    <Combobox.Input placeholder="Search frameworks" />',
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        <Combobox.Empty>No frameworks found</Combobox.Empty>",
          "        <For each={collection().items}>",
          "          {(item) => (",
          "            <Combobox.Item item={item}>",
          "              <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "              <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "            </Combobox.Item>",
          "          )}",
          "        </For>",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
      {
        title: "Several small picks, with a clear button",
        code: [
          'import { For } from "solid-js";',
          'import { Combobox, Portal, useFilter, useListCollection } from "@moderno-ui/solid";',
          "",
          'const filters = useFilter({ sensitivity: "base" });',
          "const { collection, filter } = useListCollection({",
          "  initialItems: frameworks,",
          "  filter: (text, query) => filters().contains(text, query),",
          "});",
          "",
          "<Combobox.Root",
          '  size="sm"',
          "  multiple",
          "  collection={collection()}",
          "  onInputValueChange={(e) => filter(e.inputValue)}",
          ">",
          "  <Combobox.Label>Frameworks</Combobox.Label>",
          "  <Combobox.Control>",
          "    <Combobox.Input />",
          "    <Combobox.ClearTrigger>×</Combobox.ClearTrigger>",
          "    <Combobox.Trigger>▾</Combobox.Trigger>",
          "  </Combobox.Control>",
          "  <Portal>",
          "    <Combobox.Positioner>",
          "      <Combobox.Content>",
          "        <For each={collection().items}>",
          "          {(item) => (",
          "            <Combobox.Item item={item}>",
          "              <Combobox.ItemText>{item.label}</Combobox.ItemText>",
          "              <Combobox.ItemIndicator>✓</Combobox.ItemIndicator>",
          "            </Combobox.Item>",
          "          )}",
          "        </For>",
          "      </Combobox.Content>",
          "    </Combobox.Positioner>",
          "  </Portal>",
          "</Combobox.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
