import { datePickerRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "DatePicker",
  slug: "date-picker",
  scope: "date-picker",
  props: { file: "src/date-picker.tsx", type: "ModernoDatePickerRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one date field and its calendar." },
    { name: "label", description: "Optional; names the field. Clicking it focuses the input." },
    { name: "control", description: "The bordered box; holds the input(s) and the buttons." },
    {
      name: "input",
      description:
        "The text box; takes a date typed in the locale's format. Two in range mode (index 0, 1).",
    },
    { name: "trigger", description: "The button in the box that opens and closes the calendar." },
    {
      name: "clear-trigger",
      description: "Optional; a button in the box that clears the value. Hidden while empty.",
    },
    {
      name: "value-text",
      description: "Optional; the picked date as text, for a trigger with no input.",
    },
    { name: "positioner", description: "Placed by Ark under the control; never style its layout." },
    { name: "content", description: "The calendar surface; carries data-size from the Root." },
    {
      name: "view",
      description: "One view of the calendar: day, month or year. Ark shows one at a time.",
    },
    { name: "view-control", description: "The row above the grid: previous, title, next." },
    { name: "prev-trigger", description: "Shows the previous month (or year, or decade)." },
    { name: "view-trigger", description: "The title button; switches to the next wider view." },
    { name: "range-text", description: "The visible month or year, as text." },
    { name: "next-trigger", description: "Shows the next month (or year, or decade)." },
    { name: "table", description: 'The role="grid" of days, months or years.' },
    { name: "table-head", description: "The grid's header row group." },
    { name: "table-header", description: "One weekday's name." },
    { name: "table-body", description: "The grid's rows of cells." },
    { name: "table-row", description: "One week (or one row of months or years)." },
    { name: "table-cell", description: "One cell; takes the day, month or year as value." },
    {
      name: "table-cell-trigger",
      description: "The day's button; carries data-selected, data-today, data-in-range.",
    },
    { name: "month-select", description: "Optional; a native select for the month." },
    { name: "year-select", description: "Optional; a native select for the year." },
    {
      name: "preset-trigger",
      description: 'Optional; a button that picks a preset range, like "Last 7 days".',
    },
  ],
  variants: datePickerRecipe.variants,
  examples: {
    react: [
      {
        title: "One date, typed or picked from a calendar",
        code: [
          'import { DatePicker, Portal } from "@moderno-ui/react";',
          "",
          "<DatePicker.Root>",
          "  <DatePicker.Label>Due date</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {(datePicker) => (",
          "              <>",
          "                <DatePicker.ViewControl>",
          "                  <DatePicker.PrevTrigger>‹</DatePicker.PrevTrigger>",
          "                  <DatePicker.RangeText />",
          "                  <DatePicker.NextTrigger>›</DatePicker.NextTrigger>",
          "                </DatePicker.ViewControl>",
          "                <DatePicker.Table>",
          "                  <DatePicker.TableHead>",
          "                    <DatePicker.TableRow>",
          "                      {datePicker.weekDays.map((weekDay, i) => (",
          "                        <DatePicker.TableHeader key={i}>{weekDay.short}</DatePicker.TableHeader>",
          "                      ))}",
          "                    </DatePicker.TableRow>",
          "                  </DatePicker.TableHead>",
          "                  <DatePicker.TableBody>",
          "                    {datePicker.weeks.map((week, i) => (",
          "                      <DatePicker.TableRow key={i}>",
          "                        {week.map((day, j) => (",
          "                          <DatePicker.TableCell key={j} value={day}>",
          "                            <DatePicker.TableCellTrigger>{day.day}</DatePicker.TableCellTrigger>",
          "                          </DatePicker.TableCell>",
          "                        ))}",
          "                      </DatePicker.TableRow>",
          "                    ))}",
          "                  </DatePicker.TableBody>",
          "                </DatePicker.Table>",
          "              </>",
          "            )}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
      {
        title: "A small range picker formatted for Spanish",
        code: [
          'import { DatePicker, Portal, parseDate } from "@moderno-ui/react";',
          "",
          "<DatePicker.Root",
          '  size="sm"',
          '  selectionMode="range"',
          '  locale="es-ES"',
          '  defaultValue={[parseDate("2024-05-06"), parseDate("2024-05-10")]}',
          ">",
          "  <DatePicker.Label>Trip</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input index={0} />",
          "    <DatePicker.Input index={1} />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {(datePicker) => (",
          "              <DatePicker.Table>",
          "                <DatePicker.TableBody>",
          "                  {datePicker.weeks.map((week, i) => (",
          "                    <DatePicker.TableRow key={i}>",
          "                      {week.map((day, j) => (",
          "                        <DatePicker.TableCell key={j} value={day}>",
          "                          <DatePicker.TableCellTrigger>{day.day}</DatePicker.TableCellTrigger>",
          "                        </DatePicker.TableCell>",
          "                      ))}",
          "                    </DatePicker.TableRow>",
          "                  ))}",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            )}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "One date, typed or picked from a calendar",
        code: [
          '<script setup lang="ts">',
          'import { DatePicker, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <DatePicker.Root>",
          "    <DatePicker.Label>Due date</DatePicker.Label>",
          "    <DatePicker.Control>",
          "      <DatePicker.Input />",
          '      <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "    </DatePicker.Control>",
          "    <Portal>",
          "      <DatePicker.Positioner>",
          "        <DatePicker.Content>",
          '          <DatePicker.View view="day">',
          '            <DatePicker.Context v-slot="datePicker">',
          "              <DatePicker.ViewControl>",
          "                <DatePicker.PrevTrigger>‹</DatePicker.PrevTrigger>",
          "                <DatePicker.RangeText />",
          "                <DatePicker.NextTrigger>›</DatePicker.NextTrigger>",
          "              </DatePicker.ViewControl>",
          "              <DatePicker.Table>",
          "                <DatePicker.TableHead>",
          "                  <DatePicker.TableRow>",
          '                    <DatePicker.TableHeader v-for="(weekDay, i) in datePicker.weekDays" :key="i">',
          "                      {{ weekDay.short }}",
          "                    </DatePicker.TableHeader>",
          "                  </DatePicker.TableRow>",
          "                </DatePicker.TableHead>",
          "                <DatePicker.TableBody>",
          '                  <DatePicker.TableRow v-for="(week, i) in datePicker.weeks" :key="i">',
          '                    <DatePicker.TableCell v-for="(day, j) in week" :key="j" :value="day">',
          "                      <DatePicker.TableCellTrigger>{{ day.day }}</DatePicker.TableCellTrigger>",
          "                    </DatePicker.TableCell>",
          "                  </DatePicker.TableRow>",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            </DatePicker.Context>",
          "          </DatePicker.View>",
          "        </DatePicker.Content>",
          "      </DatePicker.Positioner>",
          "    </Portal>",
          "  </DatePicker.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A small range picker formatted for Spanish",
        code: [
          '<script setup lang="ts">',
          'import { DatePicker, Portal, parseDate } from "@moderno-ui/vue";',
          "",
          'const trip = [parseDate("2024-05-06"), parseDate("2024-05-10")];',
          "</script>",
          "",
          "<template>",
          '  <DatePicker.Root size="sm" selection-mode="range" locale="es-ES" :default-value="trip">',
          "    <DatePicker.Label>Trip</DatePicker.Label>",
          "    <DatePicker.Control>",
          '      <DatePicker.Input :index="0" />',
          '      <DatePicker.Input :index="1" />',
          '      <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "    </DatePicker.Control>",
          "    <Portal>",
          "      <DatePicker.Positioner>",
          "        <DatePicker.Content>",
          '          <DatePicker.View view="day">',
          '            <DatePicker.Context v-slot="datePicker">',
          "              <DatePicker.Table>",
          "                <DatePicker.TableBody>",
          '                  <DatePicker.TableRow v-for="(week, i) in datePicker.weeks" :key="i">',
          '                    <DatePicker.TableCell v-for="(day, j) in week" :key="j" :value="day">',
          "                      <DatePicker.TableCellTrigger>{{ day.day }}</DatePicker.TableCellTrigger>",
          "                    </DatePicker.TableCell>",
          "                  </DatePicker.TableRow>",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            </DatePicker.Context>",
          "          </DatePicker.View>",
          "        </DatePicker.Content>",
          "      </DatePicker.Positioner>",
          "    </Portal>",
          "  </DatePicker.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "One date, typed or picked from a calendar",
        code: [
          '<script lang="ts">',
          '  import { DatePicker, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<DatePicker.Root>",
          "  <DatePicker.Label>Due date</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {#snippet render(datePicker)}",
          "              <DatePicker.ViewControl>",
          "                <DatePicker.PrevTrigger>‹</DatePicker.PrevTrigger>",
          "                <DatePicker.RangeText />",
          "                <DatePicker.NextTrigger>›</DatePicker.NextTrigger>",
          "              </DatePicker.ViewControl>",
          "              <DatePicker.Table>",
          "                <DatePicker.TableHead>",
          "                  <DatePicker.TableRow>",
          "                    {#each datePicker().weekDays as weekDay, i (i)}",
          "                      <DatePicker.TableHeader>{weekDay.short}</DatePicker.TableHeader>",
          "                    {/each}",
          "                  </DatePicker.TableRow>",
          "                </DatePicker.TableHead>",
          "                <DatePicker.TableBody>",
          "                  {#each datePicker().weeks as week, i (i)}",
          "                    <DatePicker.TableRow>",
          "                      {#each week as day, j (j)}",
          "                        <DatePicker.TableCell value={day}>",
          "                          <DatePicker.TableCellTrigger>{day.day}</DatePicker.TableCellTrigger>",
          "                        </DatePicker.TableCell>",
          "                      {/each}",
          "                    </DatePicker.TableRow>",
          "                  {/each}",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            {/snippet}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
      {
        title: "A small range picker formatted for Spanish",
        code: [
          '<script lang="ts">',
          '  import { DatePicker, Portal, parseDate } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<DatePicker.Root",
          '  size="sm"',
          '  selectionMode="range"',
          '  locale="es-ES"',
          '  defaultValue={[parseDate("2024-05-06"), parseDate("2024-05-10")]}',
          ">",
          "  <DatePicker.Label>Trip</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input index={0} />",
          "    <DatePicker.Input index={1} />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {#snippet render(datePicker)}",
          "              <DatePicker.Table>",
          "                <DatePicker.TableBody>",
          "                  {#each datePicker().weeks as week, i (i)}",
          "                    <DatePicker.TableRow>",
          "                      {#each week as day, j (j)}",
          "                        <DatePicker.TableCell value={day}>",
          "                          <DatePicker.TableCellTrigger>{day.day}</DatePicker.TableCellTrigger>",
          "                        </DatePicker.TableCell>",
          "                      {/each}",
          "                    </DatePicker.TableRow>",
          "                  {/each}",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            {/snippet}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "One date, typed or picked from a calendar",
        code: [
          'import { Index } from "solid-js";',
          'import { DatePicker, Portal } from "@moderno-ui/solid";',
          "",
          "<DatePicker.Root>",
          "  <DatePicker.Label>Due date</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {(datePicker) => (",
          "              <>",
          "                <DatePicker.ViewControl>",
          "                  <DatePicker.PrevTrigger>‹</DatePicker.PrevTrigger>",
          "                  <DatePicker.RangeText />",
          "                  <DatePicker.NextTrigger>›</DatePicker.NextTrigger>",
          "                </DatePicker.ViewControl>",
          "                <DatePicker.Table>",
          "                  <DatePicker.TableHead>",
          "                    <DatePicker.TableRow>",
          "                      <Index each={datePicker().weekDays}>",
          "                        {(weekDay) => <DatePicker.TableHeader>{weekDay().short}</DatePicker.TableHeader>}",
          "                      </Index>",
          "                    </DatePicker.TableRow>",
          "                  </DatePicker.TableHead>",
          "                  <DatePicker.TableBody>",
          "                    <Index each={datePicker().weeks}>",
          "                      {(week) => (",
          "                        <DatePicker.TableRow>",
          "                          <Index each={week()}>",
          "                            {(day) => (",
          "                              <DatePicker.TableCell value={day()}>",
          "                                <DatePicker.TableCellTrigger>{day().day}</DatePicker.TableCellTrigger>",
          "                              </DatePicker.TableCell>",
          "                            )}",
          "                          </Index>",
          "                        </DatePicker.TableRow>",
          "                      )}",
          "                    </Index>",
          "                  </DatePicker.TableBody>",
          "                </DatePicker.Table>",
          "              </>",
          "            )}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
      {
        title: "A small range picker formatted for Spanish",
        code: [
          'import { Index } from "solid-js";',
          'import { DatePicker, Portal, parseDate } from "@moderno-ui/solid";',
          "",
          "<DatePicker.Root",
          '  size="sm"',
          '  selectionMode="range"',
          '  locale="es-ES"',
          '  defaultValue={[parseDate("2024-05-06"), parseDate("2024-05-10")]}',
          ">",
          "  <DatePicker.Label>Trip</DatePicker.Label>",
          "  <DatePicker.Control>",
          "    <DatePicker.Input index={0} />",
          "    <DatePicker.Input index={1} />",
          '    <DatePicker.Trigger aria-label="Open calendar">▾</DatePicker.Trigger>',
          "  </DatePicker.Control>",
          "  <Portal>",
          "    <DatePicker.Positioner>",
          "      <DatePicker.Content>",
          '        <DatePicker.View view="day">',
          "          <DatePicker.Context>",
          "            {(datePicker) => (",
          "              <DatePicker.Table>",
          "                <DatePicker.TableBody>",
          "                  <Index each={datePicker().weeks}>",
          "                    {(week) => (",
          "                      <DatePicker.TableRow>",
          "                        <Index each={week()}>",
          "                          {(day) => (",
          "                            <DatePicker.TableCell value={day()}>",
          "                              <DatePicker.TableCellTrigger>{day().day}</DatePicker.TableCellTrigger>",
          "                            </DatePicker.TableCell>",
          "                          )}",
          "                        </Index>",
          "                      </DatePicker.TableRow>",
          "                    )}",
          "                  </Index>",
          "                </DatePicker.TableBody>",
          "              </DatePicker.Table>",
          "            )}",
          "          </DatePicker.Context>",
          "        </DatePicker.View>",
          "      </DatePicker.Content>",
          "    </DatePicker.Positioner>",
          "  </Portal>",
          "</DatePicker.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
