import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Dialog",
  slug: "dialog",
  scope: "dialog",
  parts: [
    { name: "backdrop" },
    { name: "positioner" },
    { name: "content" },
    { name: "title" },
    { name: "description" },
  ],
  examples: {
    react: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/react";',
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Confirmation dialog",
        code: [
          '<script setup lang="ts">',
          'import { Dialog, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Dialog.Root>",
          "    <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "    <Portal>",
          "      <Dialog.Backdrop />",
          "      <Dialog.Positioner>",
          "        <Dialog.Content>",
          "          <Dialog.Title>Delete account</Dialog.Title>",
          "          <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "          <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "        </Dialog.Content>",
          "      </Dialog.Positioner>",
          "    </Portal>",
          "  </Dialog.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Confirmation dialog",
        code: [
          '<script lang="ts">',
          '  import { Dialog, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/solid";',
          "",
          "function ConfirmDialog() {",
          "  return (",
          "    <Dialog.Root>",
          "      <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "      <Portal>",
          "        <Dialog.Backdrop />",
          "        <Dialog.Positioner>",
          "          <Dialog.Content>",
          "            <Dialog.Title>Delete account</Dialog.Title>",
          "            <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "            <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "          </Dialog.Content>",
          "        </Dialog.Positioner>",
          "      </Portal>",
          "    </Dialog.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
