import { drawerRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Drawer",
  slug: "drawer",
  scope: "drawer",
  props: { file: "src/drawer.tsx", type: "DrawerRootProps" },
  parts: [
    { name: "trigger", description: "Opens the drawer; focus returns to it on close." },
    { name: "backdrop", description: "The --overlay scrim behind the drawer." },
    {
      name: "positioner",
      description: "Covers the viewport and pins the content to its edge; carries data-placement.",
    },
    {
      name: "content",
      description: 'The role="dialog" panel; carries data-placement from the Root.',
    },
    { name: "title", description: "The panel's accessible name (aria-labelledby)." },
    { name: "description", description: "Wired to the content's aria-describedby." },
    {
      name: "close-trigger",
      description: "Closes the drawer; bare, an icon button in the top corner.",
    },
  ],
  variants: drawerRecipe.variants,
  examples: {
    react: [
      {
        title: "Drawer from the right with a title, description and close button",
        code: [
          'import { Button, Drawer, Portal } from "@moderno-ui/react";',
          "",
          "<Drawer.Root>",
          "  <Drawer.Trigger asChild>",
          "    <Button>Filters</Button>",
          "  </Drawer.Trigger>",
          "  <Portal>",
          "    <Drawer.Backdrop />",
          "    <Drawer.Positioner>",
          "      <Drawer.Content>",
          "        <Drawer.Title>Filters</Drawer.Title>",
          "        <Drawer.Description>Narrow the list of orders.</Drawer.Description>",
          '        <Drawer.CloseTrigger aria-label="Close">×</Drawer.CloseTrigger>',
          "      </Drawer.Content>",
          "    </Drawer.Positioner>",
          "  </Portal>",
          "</Drawer.Root>",
        ].join("\n"),
      },
      {
        title: "Bottom drawer of actions",
        code: [
          'import { Button, Drawer, Portal } from "@moderno-ui/react";',
          "",
          '<Drawer.Root placement="bottom">',
          "  <Drawer.Trigger asChild>",
          '    <Button variant="outline">Share</Button>',
          "  </Drawer.Trigger>",
          "  <Portal>",
          "    <Drawer.Backdrop />",
          "    <Drawer.Positioner>",
          "      <Drawer.Content>",
          "        <Drawer.Title>Share</Drawer.Title>",
          "        <Drawer.Description>Send this page to your team.</Drawer.Description>",
          "      </Drawer.Content>",
          "    </Drawer.Positioner>",
          "  </Portal>",
          "</Drawer.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Drawer from the right with a title, description and close button",
        code: [
          '<script setup lang="ts">',
          'import { Button, Drawer, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Drawer.Root>",
          "    <Drawer.Trigger as-child>",
          "      <Button>Filters</Button>",
          "    </Drawer.Trigger>",
          "    <Portal>",
          "      <Drawer.Backdrop />",
          "      <Drawer.Positioner>",
          "        <Drawer.Content>",
          "          <Drawer.Title>Filters</Drawer.Title>",
          "          <Drawer.Description>Narrow the list of orders.</Drawer.Description>",
          '          <Drawer.CloseTrigger aria-label="Close">×</Drawer.CloseTrigger>',
          "        </Drawer.Content>",
          "      </Drawer.Positioner>",
          "    </Portal>",
          "  </Drawer.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Drawer from the right with a title, description and close button",
        code: [
          '<script lang="ts">',
          '  import { Button, Drawer, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Drawer.Root>",
          "  <Drawer.Trigger>",
          "    {#snippet asChild(triggerProps)}",
          "      <Button {...triggerProps()}>Filters</Button>",
          "    {/snippet}",
          "  </Drawer.Trigger>",
          "  <Portal>",
          "    <Drawer.Backdrop />",
          "    <Drawer.Positioner>",
          "      <Drawer.Content>",
          "        <Drawer.Title>Filters</Drawer.Title>",
          "        <Drawer.Description>Narrow the list of orders.</Drawer.Description>",
          '        <Drawer.CloseTrigger aria-label="Close">×</Drawer.CloseTrigger>',
          "      </Drawer.Content>",
          "    </Drawer.Positioner>",
          "  </Portal>",
          "</Drawer.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Drawer from the right with a title, description and close button",
        code: [
          'import { Button, Drawer, Portal } from "@moderno-ui/solid";',
          "",
          "<Drawer.Root>",
          "  <Drawer.Trigger",
          "    asChild={(triggerProps) => <Button {...triggerProps()}>Filters</Button>}",
          "  />",
          "  <Portal>",
          "    <Drawer.Backdrop />",
          "    <Drawer.Positioner>",
          "      <Drawer.Content>",
          "        <Drawer.Title>Filters</Drawer.Title>",
          "        <Drawer.Description>Narrow the list of orders.</Drawer.Description>",
          '        <Drawer.CloseTrigger aria-label="Close">×</Drawer.CloseTrigger>',
          "      </Drawer.Content>",
          "    </Drawer.Positioner>",
          "  </Portal>",
          "</Drawer.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
