import { editableRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Editable",
  slug: "editable",
  scope: "editable",
  props: { file: "src/editable.tsx", type: "ModernoEditableRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one editable value." },
    { name: "label", description: "Optional; names the text and the input." },
    { name: "area", description: "Holds the text and the input, one in place of the other." },
    {
      name: "preview",
      description: "The value as text, a button; double click, Enter or F2 starts an edit.",
    },
    { name: "input", description: "The input that replaces the text while the user edits." },
    { name: "control", description: "Optional; holds the edit, save and cancel buttons." },
    { name: "edit-trigger", description: "A button that starts an edit; hidden while editing." },
    { name: "submit-trigger", description: "A button that saves; shown while editing." },
    { name: "cancel-trigger", description: "A button that cancels; shown while editing." },
  ],
  variants: editableRecipe.variants,
  examples: {
    react: [
      {
        title: "A layer name the user renames in place",
        code: [
          'import { Editable } from "@moderno-ui/react";',
          "",
          "<Editable.Root value={name} onValueChange={(e) => setName(e.value)}>",
          "  <Editable.Label>Layer name</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "</Editable.Root>",
        ].join("\n"),
      },
      {
        title: "Edit, save and cancel buttons, saved only on Enter or Save",
        code: [
          'import { Editable } from "@moderno-ui/react";',
          "",
          '<Editable.Root defaultValue="Intro" submitMode="enter" onValueCommit={(e) => rename(e.value)}>',
          "  <Editable.Label>Slide title</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "  <Editable.Control>",
          "    <Editable.EditTrigger>Edit</Editable.EditTrigger>",
          "    <Editable.SubmitTrigger>Save</Editable.SubmitTrigger>",
          "    <Editable.CancelTrigger>Cancel</Editable.CancelTrigger>",
          "  </Editable.Control>",
          "</Editable.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A layer name the user renames in place",
        code: [
          '<script setup lang="ts">',
          'import { Editable } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Editable.Root v-model="name">',
          "    <Editable.Label>Layer name</Editable.Label>",
          "    <Editable.Area>",
          "      <Editable.Input />",
          "      <Editable.Preview />",
          "    </Editable.Area>",
          "  </Editable.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Edit, save and cancel buttons, saved only on Enter or Save",
        code: [
          '<script setup lang="ts">',
          'import { Editable } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Editable.Root default-value="Intro" submit-mode="enter" @value-commit="(e) => rename(e.value)">',
          "    <Editable.Label>Slide title</Editable.Label>",
          "    <Editable.Area>",
          "      <Editable.Input />",
          "      <Editable.Preview />",
          "    </Editable.Area>",
          "    <Editable.Control>",
          "      <Editable.EditTrigger>Edit</Editable.EditTrigger>",
          "      <Editable.SubmitTrigger>Save</Editable.SubmitTrigger>",
          "      <Editable.CancelTrigger>Cancel</Editable.CancelTrigger>",
          "    </Editable.Control>",
          "  </Editable.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A layer name the user renames in place",
        code: [
          '<script lang="ts">',
          '  import { Editable } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Editable.Root bind:value={name}>",
          "  <Editable.Label>Layer name</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "</Editable.Root>",
        ].join("\n"),
      },
      {
        title: "Edit, save and cancel buttons, saved only on Enter or Save",
        code: [
          '<script lang="ts">',
          '  import { Editable } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Editable.Root defaultValue="Intro" submitMode="enter" onValueCommit={(e) => rename(e.value)}>',
          "  <Editable.Label>Slide title</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "  <Editable.Control>",
          "    <Editable.EditTrigger>Edit</Editable.EditTrigger>",
          "    <Editable.SubmitTrigger>Save</Editable.SubmitTrigger>",
          "    <Editable.CancelTrigger>Cancel</Editable.CancelTrigger>",
          "  </Editable.Control>",
          "</Editable.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A layer name the user renames in place",
        code: [
          'import { Editable } from "@moderno-ui/solid";',
          "",
          "<Editable.Root value={name()} onValueChange={(e) => setName(e.value)}>",
          "  <Editable.Label>Layer name</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "</Editable.Root>",
        ].join("\n"),
      },
      {
        title: "Edit, save and cancel buttons, saved only on Enter or Save",
        code: [
          'import { Editable } from "@moderno-ui/solid";',
          "",
          '<Editable.Root defaultValue="Intro" submitMode="enter" onValueCommit={(e) => rename(e.value)}>',
          "  <Editable.Label>Slide title</Editable.Label>",
          "  <Editable.Area>",
          "    <Editable.Input />",
          "    <Editable.Preview />",
          "  </Editable.Area>",
          "  <Editable.Control>",
          "    <Editable.EditTrigger>Edit</Editable.EditTrigger>",
          "    <Editable.SubmitTrigger>Save</Editable.SubmitTrigger>",
          "    <Editable.CancelTrigger>Cancel</Editable.CancelTrigger>",
          "  </Editable.Control>",
          "</Editable.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
