import { fieldRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Field",
  slug: "field",
  scope: "field",
  props: { file: "src/field.tsx", type: "ModernoFieldRootProps" },
  parts: [
    { name: "root" },
    { name: "label" },
    { name: "input" },
    { name: "textarea" },
    { name: "helper-text" },
    { name: "error-text" },
    { name: "required-indicator" },
  ],
  variants: fieldRecipe.variants,
  examples: {
    react: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          "<Field.Root invalid={hasError}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "defineProps<{ invalid?: boolean }>();",
          "</script>",
          "",
          "<template>",
          '  <Field.Root :invalid="invalid">',
          "    <Field.Label>Email</Field.Label>",
          '    <Field.Input placeholder="you@example.com" />',
          "    <Field.HelperText>We never share it.</Field.HelperText>",
          "    <Field.ErrorText>Email is required.</Field.ErrorText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Field.Root size="lg">',
          "    <Field.Label>Bio</Field.Label>",
          '    <Field.Textarea placeholder="Tell us about yourself" />',
          "    <Field.HelperText>A short introduction.</Field.HelperText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "  let { invalid = false }: { invalid?: boolean } = $props();",
          "</script>",
          "",
          "<Field.Root {invalid}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function EmailField(props: { invalid?: boolean }) {",
          "  return (",
          "    <Field.Root invalid={props.invalid}>",
          "      <Field.Label>Email</Field.Label>",
          '      <Field.Input placeholder="you@example.com" />',
          "      <Field.HelperText>We never share it.</Field.HelperText>",
          "      <Field.ErrorText>Email is required.</Field.ErrorText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function BioField() {",
          "  return (",
          '    <Field.Root size="lg">',
          "      <Field.Label>Bio</Field.Label>",
          '      <Field.Textarea placeholder="Tell us about yourself" />',
          "      <Field.HelperText>A short introduction.</Field.HelperText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
