import { fileUploadRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "FileUpload",
  slug: "file-upload",
  scope: "file-upload",
  props: { file: "src/file-upload.tsx", type: "FileUploadProps" },
  parts: [
    { name: "root", description: "Carries size; holds the drop zone and the lists." },
    {
      name: "dropzone",
      description: 'The drop zone, role="button"; data-dragging while a file is over it.',
    },
    { name: "dropzone-icon", description: "The upload glyph in the drop zone." },
    { name: "dropzone-title", description: "The zone's title: the label prop, or the prompt." },
    { name: "dropzone-hint", description: "What it takes: types, largest file, how many." },
    {
      name: "item-group",
      description: 'One list; data-type="accepted", or "rejected" for files turned away.',
    },
    { name: "item", description: "One file's row; data-type as its list's." },
    { name: "item-preview", description: "The thumbnail box: an image, or a file glyph." },
    { name: "item-preview-image", description: "An image file's thumbnail." },
    { name: "item-name", description: "The file's name, truncated in the middle." },
    { name: "item-name-full", description: "The whole name, visually hidden, for screen readers." },
    { name: "item-name-start", description: "The start of the name; gives way to an ellipsis." },
    { name: "item-name-end", description: "The end of the name and its extension; always shown." },
    { name: "item-size-text", description: "The file's size." },
    { name: "item-error", description: "Why a rejected file was turned away." },
    { name: "item-delete-trigger", description: 'The remove button, named "Remove <file>".' },
  ],
  variants: fileUploadRecipe.variants,
  examples: {
    react: [
      {
        title: "A logo upload in a form field",
        code: [
          'import { Field, FileUpload } from "@moderno-ui/react";',
          "",
          "<Field.Root>",
          "  <Field.Label>Logo</Field.Label>",
          "  <FileUpload",
          '    accept={["image/svg+xml", "image/png"]}',
          "    maxFileSize={2_000_000}",
          "    onFileChange={(details) => setLogo(details.acceptedFiles[0])}",
          "  />",
          "  <Field.HelperText>A square logo works best.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Several font files",
        code: [
          'import { FileUpload } from "@moderno-ui/react";',
          "",
          '<FileUpload label="Upload fonts" accept={[".otf", ".woff2"]} maxFiles={4} />',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A logo upload in a form field",
        code: [
          '<script setup lang="ts">',
          'import { ref } from "vue";',
          'import { Field, FileUpload } from "@moderno-ui/vue";',
          "",
          "const files = ref<File[]>([]);",
          "</script>",
          "",
          "<template>",
          "  <Field.Root>",
          "    <Field.Label>Logo</Field.Label>",
          "    <FileUpload",
          '      v-model:accepted-files="files"',
          "      :accept=\"['image/svg+xml', 'image/png']\"",
          '      :max-file-size="2_000_000"',
          "    />",
          "    <Field.HelperText>A square logo works best.</Field.HelperText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Several font files",
        code: [
          '<script setup lang="ts">',
          'import { FileUpload } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <FileUpload label="Upload fonts" :accept="[\'.otf\', \'.woff2\']" :max-files="4" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A logo upload in a form field",
        code: [
          '<script lang="ts">',
          '  import { Field, FileUpload } from "@moderno-ui/svelte";',
          "",
          "  let files = $state<File[]>([]);",
          "</script>",
          "",
          "<Field.Root>",
          "  <Field.Label>Logo</Field.Label>",
          "  <FileUpload",
          "    bind:acceptedFiles={files}",
          '    accept={["image/svg+xml", "image/png"]}',
          "    maxFileSize={2_000_000}",
          "  />",
          "  <Field.HelperText>A square logo works best.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Several font files",
        code: [
          '<script lang="ts">',
          '  import { FileUpload } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<FileUpload label="Upload fonts" accept={[".otf", ".woff2"]} maxFiles={4} />',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A logo upload in a form field",
        code: [
          'import { Field, FileUpload } from "@moderno-ui/solid";',
          "",
          "<Field.Root>",
          "  <Field.Label>Logo</Field.Label>",
          "  <FileUpload",
          '    accept={["image/svg+xml", "image/png"]}',
          "    maxFileSize={2_000_000}",
          "    onFileChange={(details) => setLogo(details.acceptedFiles[0])}",
          "  />",
          "  <Field.HelperText>A square logo works best.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Several font files",
        code: [
          'import { FileUpload } from "@moderno-ui/solid";',
          "",
          '<FileUpload label="Upload fonts" accept={[".otf", ".woff2"]} maxFiles={4} />',
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
