import { menuRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Menu",
  slug: "menu",
  scope: "menu",
  props: { file: "src/menu.tsx", type: "ModernoMenuRootProps" },
  parts: [
    { name: "trigger", description: "The button that opens the menu; carries size." },
    { name: "indicator", description: "Optional; an arrow in the trigger that turns while open." },
    {
      name: "context-trigger",
      description: "Optional; an area that opens the menu on right-click.",
    },
    {
      name: "positioner",
      description: "Places the content; under 40rem, the bottom sheet's scrim.",
    },
    { name: "content", description: "The menu surface; carries size." },
    { name: "arrow", description: "Optional; points at the trigger." },
    { name: "arrow-tip", description: "The arrow's visible tip." },
    { name: "item", description: "One action; takes a unique value." },
    { name: "item-text", description: "The label of a checkbox or radio item." },
    { name: "item-indicator", description: "Shown while a checkbox or radio item is checked." },
    { name: "item-group", description: "Groups items under a label." },
    { name: "item-group-label", description: "The name of a group." },
    { name: "separator", description: "A line between groups." },
    { name: "trigger-item", description: "An item that opens a submenu." },
  ],
  variants: menuRecipe.variants,
  examples: {
    react: [
      {
        title: "Actions menu with a group and a separator",
        code: [
          'import { Menu, Portal } from "@moderno-ui/react";',
          "",
          '<Menu.Root size="sm" onSelect={(details) => console.log(details.value)}>',
          "  <Menu.Trigger>",
          "    Actions <Menu.Indicator>▾</Menu.Indicator>",
          "  </Menu.Trigger>",
          "  <Portal>",
          "    <Menu.Positioner>",
          "      <Menu.Content>",
          "        <Menu.ItemGroup>",
          "          <Menu.ItemGroupLabel>File</Menu.ItemGroupLabel>",
          '          <Menu.Item value="new">New file</Menu.Item>',
          '          <Menu.Item value="rename">Rename</Menu.Item>',
          "        </Menu.ItemGroup>",
          "        <Menu.Separator />",
          '        <Menu.Item value="delete">Delete</Menu.Item>',
          "      </Menu.Content>",
          "    </Menu.Positioner>",
          "  </Portal>",
          "</Menu.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Actions menu with a group and a separator",
        code: [
          '<script setup lang="ts">',
          'import { Menu, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Menu.Root size="sm" @select="(details) => console.log(details.value)">',
          "    <Menu.Trigger>Actions <Menu.Indicator>▾</Menu.Indicator></Menu.Trigger>",
          "    <Portal>",
          "      <Menu.Positioner>",
          "        <Menu.Content>",
          "          <Menu.ItemGroup>",
          "            <Menu.ItemGroupLabel>File</Menu.ItemGroupLabel>",
          '            <Menu.Item value="new">New file</Menu.Item>',
          '            <Menu.Item value="rename">Rename</Menu.Item>',
          "          </Menu.ItemGroup>",
          "          <Menu.Separator />",
          '          <Menu.Item value="delete">Delete</Menu.Item>',
          "        </Menu.Content>",
          "      </Menu.Positioner>",
          "    </Portal>",
          "  </Menu.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Actions menu with a group and a separator",
        code: [
          '<script lang="ts">',
          '  import { Menu, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Menu.Root size="sm" onSelect={(details) => console.log(details.value)}>',
          "  <Menu.Trigger>Actions <Menu.Indicator>▾</Menu.Indicator></Menu.Trigger>",
          "  <Portal>",
          "    <Menu.Positioner>",
          "      <Menu.Content>",
          "        <Menu.ItemGroup>",
          "          <Menu.ItemGroupLabel>File</Menu.ItemGroupLabel>",
          '          <Menu.Item value="new">New file</Menu.Item>',
          '          <Menu.Item value="rename">Rename</Menu.Item>',
          "        </Menu.ItemGroup>",
          "        <Menu.Separator />",
          '        <Menu.Item value="delete">Delete</Menu.Item>',
          "      </Menu.Content>",
          "    </Menu.Positioner>",
          "  </Portal>",
          "</Menu.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Actions menu with a group and a separator",
        code: [
          'import { Menu, Portal } from "@moderno-ui/solid";',
          "",
          "function ActionsMenu() {",
          "  return (",
          '    <Menu.Root size="sm" onSelect={(details) => console.log(details.value)}>',
          "      <Menu.Trigger>",
          "        Actions <Menu.Indicator>▾</Menu.Indicator>",
          "      </Menu.Trigger>",
          "      <Portal>",
          "        <Menu.Positioner>",
          "          <Menu.Content>",
          "            <Menu.ItemGroup>",
          "              <Menu.ItemGroupLabel>File</Menu.ItemGroupLabel>",
          '              <Menu.Item value="new">New file</Menu.Item>',
          '              <Menu.Item value="rename">Rename</Menu.Item>',
          "            </Menu.ItemGroup>",
          "            <Menu.Separator />",
          '            <Menu.Item value="delete">Delete</Menu.Item>',
          "          </Menu.Content>",
          "        </Menu.Positioner>",
          "      </Portal>",
          "    </Menu.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
