import { numberInputRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "NumberInput",
  slug: "number-input",
  scope: "number-input",
  props: { file: "src/number-input.tsx", type: "ModernoNumberInputRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one number field." },
    { name: "label", description: "Optional; names the field. Clicking it focuses the input." },
    { name: "control", description: "The bordered box; holds the input and the steppers." },
    { name: "input", description: "The text box, role=spinbutton; arrow keys step it." },
    { name: "decrement-trigger", description: "A button that steps the value down." },
    { name: "increment-trigger", description: "A button that steps the value up." },
    {
      name: "scrubber",
      description: "Optional; a handle the user drags sideways to change the value.",
    },
    { name: "value-text", description: "Optional; the formatted value, outside the box." },
  ],
  variants: numberInputRecipe.variants,
  examples: {
    react: [
      {
        title: "A quantity between 1 and 10",
        code: [
          'import { NumberInput } from "@moderno-ui/react";',
          "",
          "<NumberInput.Root value={quantity} onValueChange={(e) => setQuantity(e.value)} min={1} max={10}>",
          "  <NumberInput.Label>Quantity</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
      {
        title: "A price formatted as currency",
        code: [
          'import { NumberInput } from "@moderno-ui/react";',
          "",
          '<NumberInput.Root defaultValue="1250" step={50} formatOptions={{ style: "currency", currency: "USD" }}>',
          "  <NumberInput.Label>Price</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A quantity between 1 and 10",
        code: [
          '<script setup lang="ts">',
          'import { NumberInput } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <NumberInput.Root v-model="quantity" :min="1" :max="10">',
          "    <NumberInput.Label>Quantity</NumberInput.Label>",
          "    <NumberInput.Control>",
          "      <NumberInput.Input />",
          "      <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "      <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "    </NumberInput.Control>",
          "  </NumberInput.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A price formatted as currency",
        code: [
          '<script setup lang="ts">',
          'import { NumberInput } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <NumberInput.Root default-value="1250" :step="50" :format-options="{ style: \'currency\', currency: \'USD\' }">',
          "    <NumberInput.Label>Price</NumberInput.Label>",
          "    <NumberInput.Control>",
          "      <NumberInput.Input />",
          "      <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "      <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "    </NumberInput.Control>",
          "  </NumberInput.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A quantity between 1 and 10",
        code: [
          '<script lang="ts">',
          '  import { NumberInput } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<NumberInput.Root value={quantity} onValueChange={(e) => (quantity = e.value)} min={1} max={10}>",
          "  <NumberInput.Label>Quantity</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
      {
        title: "A price formatted as currency",
        code: [
          '<script lang="ts">',
          '  import { NumberInput } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<NumberInput.Root defaultValue="1250" step={50} formatOptions={{ style: "currency", currency: "USD" }}>',
          "  <NumberInput.Label>Price</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A quantity between 1 and 10",
        code: [
          'import { NumberInput } from "@moderno-ui/solid";',
          "",
          "<NumberInput.Root value={quantity()} onValueChange={(e) => setQuantity(e.value)} min={1} max={10}>",
          "  <NumberInput.Label>Quantity</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
      {
        title: "A price formatted as currency",
        code: [
          'import { NumberInput } from "@moderno-ui/solid";',
          "",
          '<NumberInput.Root defaultValue="1250" step={50} formatOptions={{ style: "currency", currency: "USD" }}>',
          "  <NumberInput.Label>Price</NumberInput.Label>",
          "  <NumberInput.Control>",
          "    <NumberInput.Input />",
          "    <NumberInput.DecrementTrigger>−</NumberInput.DecrementTrigger>",
          "    <NumberInput.IncrementTrigger>+</NumberInput.IncrementTrigger>",
          "  </NumberInput.Control>",
          "</NumberInput.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
