import { paginationRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Pagination",
  slug: "pagination",
  scope: "pagination",
  props: { file: "src/pagination.tsx", type: "ModernoPaginationRootProps" },
  parts: [
    { name: "root", description: "The <nav> landmark; carries size and holds the row." },
    { name: "first-trigger", description: "Optional; a button that goes to the first page." },
    { name: "prev-trigger", description: "A button that goes one page back. Off on page 1." },
    {
      name: "item",
      description: "One page button, from the Context's pages; the current one is marked.",
    },
    { name: "ellipsis", description: "Stands for the pages skipped between two items." },
    { name: "next-trigger", description: "A button that goes one page on. Off on the last." },
    { name: "last-trigger", description: "Optional; a button that goes to the last page." },
  ],
  variants: paginationRecipe.variants,
  examples: {
    react: [
      {
        title: "Results split into pages, with prev and next",
        code: [
          'import { Pagination } from "@moderno-ui/react";',
          "",
          "<Pagination.Root count={200} pageSize={20}>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {(pagination) =>",
          "      pagination.pages.map((page, index) =>",
          '        page.type === "page" ? (',
          "          <Pagination.Item key={index} {...page}>{page.value}</Pagination.Item>",
          "        ) : (",
          "          <Pagination.Ellipsis key={index} index={index}>…</Pagination.Ellipsis>",
          "        ),",
          "      )",
          "    }",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
      {
        title: "A controlled page, with first and last",
        code: [
          'import { Pagination } from "@moderno-ui/react";',
          "",
          "<Pagination.Root count={200} pageSize={20} page={page} onPageChange={(e) => setPage(e.page)}>",
          "  <Pagination.FirstTrigger>«</Pagination.FirstTrigger>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {(pagination) =>",
          "      pagination.pages.map((page, index) =>",
          '        page.type === "page" ? (',
          "          <Pagination.Item key={index} {...page}>{page.value}</Pagination.Item>",
          "        ) : (",
          "          <Pagination.Ellipsis key={index} index={index}>…</Pagination.Ellipsis>",
          "        ),",
          "      )",
          "    }",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "  <Pagination.LastTrigger>»</Pagination.LastTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Results split into pages, with prev and next",
        code: [
          '<script setup lang="ts">',
          'import { Pagination } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Pagination.Root :count="200" :page-size="20">',
          "    <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          '    <Pagination.Context v-slot="{ pages }">',
          '      <template v-for="(page, index) in pages" :key="index">',
          '        <Pagination.Item v-if="page.type === \'page\'" v-bind="page">{{ page.value }}</Pagination.Item>',
          '        <Pagination.Ellipsis v-else :index="index">…</Pagination.Ellipsis>',
          "      </template>",
          "    </Pagination.Context>",
          "    <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "  </Pagination.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A controlled page, with first and last",
        code: [
          '<script setup lang="ts">',
          'import { Pagination } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Pagination.Root v-model:page="page" :count="200" :page-size="20">',
          "    <Pagination.FirstTrigger>«</Pagination.FirstTrigger>",
          "    <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          '    <Pagination.Context v-slot="{ pages }">',
          '      <template v-for="(page, index) in pages" :key="index">',
          '        <Pagination.Item v-if="page.type === \'page\'" v-bind="page">{{ page.value }}</Pagination.Item>',
          '        <Pagination.Ellipsis v-else :index="index">…</Pagination.Ellipsis>',
          "      </template>",
          "    </Pagination.Context>",
          "    <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "    <Pagination.LastTrigger>»</Pagination.LastTrigger>",
          "  </Pagination.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Results split into pages, with prev and next",
        code: [
          '<script lang="ts">',
          '  import { Pagination } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Pagination.Root count={200} pageSize={20}>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {#snippet render(pagination)}",
          "      {#each pagination().pages as page, index (index)}",
          '        {#if page.type === "page"}',
          "          <Pagination.Item {...page}>{page.value}</Pagination.Item>",
          "        {:else}",
          "          <Pagination.Ellipsis {index}>…</Pagination.Ellipsis>",
          "        {/if}",
          "      {/each}",
          "    {/snippet}",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
      {
        title: "A controlled page, with first and last",
        code: [
          '<script lang="ts">',
          '  import { Pagination } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Pagination.Root count={200} pageSize={20} page={page} onPageChange={(e) => (page = e.page)}>",
          "  <Pagination.FirstTrigger>«</Pagination.FirstTrigger>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {#snippet render(pagination)}",
          "      {#each pagination().pages as page, index (index)}",
          '        {#if page.type === "page"}',
          "          <Pagination.Item {...page}>{page.value}</Pagination.Item>",
          "        {:else}",
          "          <Pagination.Ellipsis {index}>…</Pagination.Ellipsis>",
          "        {/if}",
          "      {/each}",
          "    {/snippet}",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "  <Pagination.LastTrigger>»</Pagination.LastTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Results split into pages, with prev and next",
        code: [
          'import { For } from "solid-js";',
          'import { Pagination } from "@moderno-ui/solid";',
          "",
          "<Pagination.Root count={200} pageSize={20}>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {(pagination) => (",
          "      <For each={pagination().pages}>",
          "        {(page, index) =>",
          '          page.type === "page" ? (',
          "            <Pagination.Item {...page}>{page.value}</Pagination.Item>",
          "          ) : (",
          "            <Pagination.Ellipsis index={index()}>…</Pagination.Ellipsis>",
          "          )",
          "        }",
          "      </For>",
          "    )}",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
      {
        title: "A controlled page, with first and last",
        code: [
          'import { For } from "solid-js";',
          'import { Pagination } from "@moderno-ui/solid";',
          "",
          "<Pagination.Root count={200} pageSize={20} page={page()} onPageChange={(e) => setPage(e.page)}>",
          "  <Pagination.FirstTrigger>«</Pagination.FirstTrigger>",
          "  <Pagination.PrevTrigger>‹</Pagination.PrevTrigger>",
          "  <Pagination.Context>",
          "    {(pagination) => (",
          "      <For each={pagination().pages}>",
          "        {(page, index) =>",
          '          page.type === "page" ? (',
          "            <Pagination.Item {...page}>{page.value}</Pagination.Item>",
          "          ) : (",
          "            <Pagination.Ellipsis index={index()}>…</Pagination.Ellipsis>",
          "          )",
          "        }",
          "      </For>",
          "    )}",
          "  </Pagination.Context>",
          "  <Pagination.NextTrigger>›</Pagination.NextTrigger>",
          "  <Pagination.LastTrigger>»</Pagination.LastTrigger>",
          "</Pagination.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
