import { popoverRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Popover",
  slug: "popover",
  scope: "popover",
  props: { file: "src/popover.tsx", type: "ModernoPopoverRootProps" },
  parts: [
    {
      name: "trigger",
      description: "Opens and closes the popover; the content is anchored to it.",
    },
    { name: "indicator", description: "Optional, inside the trigger; turns over while open." },
    { name: "anchor", description: "Optional; anchors the content to another element." },
    {
      name: "positioner",
      description: "Placed by Ark beside the trigger; never style its layout.",
    },
    {
      name: "content",
      description: 'The role="dialog" surface; carries data-size from the Root.',
    },
    { name: "arrow", description: "Optional, first in the content; Ark places it." },
    { name: "arrow-tip", description: "Inside the arrow; the point, edged in --border." },
    { name: "title", description: "The content's accessible name (aria-labelledby)." },
    { name: "description", description: "Wired to the content's aria-describedby." },
    { name: "close-trigger", description: "The icon button in the content's top corner." },
  ],
  variants: popoverRecipe.variants,
  examples: {
    react: [
      {
        title: "Popover with an arrow, title, description and close button",
        code: [
          'import { Button, Popover, Portal } from "@moderno-ui/react";',
          "",
          "<Popover.Root>",
          "  <Popover.Trigger asChild>",
          "    <Button>Share</Button>",
          "  </Popover.Trigger>",
          "  <Portal>",
          "    <Popover.Positioner>",
          "      <Popover.Content>",
          "        <Popover.Arrow>",
          "          <Popover.ArrowTip />",
          "        </Popover.Arrow>",
          "        <Popover.Title>Share this page</Popover.Title>",
          "        <Popover.Description>Anyone with the link can view it.</Popover.Description>",
          '        <Popover.CloseTrigger aria-label="Close">×</Popover.CloseTrigger>',
          "      </Popover.Content>",
          "    </Popover.Positioner>",
          "  </Portal>",
          "</Popover.Root>",
        ].join("\n"),
      },
      {
        title: "Small popover placed to the right",
        code: [
          'import { Button, Popover, Portal } from "@moderno-ui/react";',
          "",
          '<Popover.Root size="sm" positioning={{ placement: "right" }}>',
          "  <Popover.Trigger asChild>",
          '    <Button variant="outline">Help</Button>',
          "  </Popover.Trigger>",
          "  <Portal>",
          "    <Popover.Positioner>",
          "      <Popover.Content>",
          "        <Popover.Title>Billing cycle</Popover.Title>",
          "        <Popover.Description>You are charged on the 1st.</Popover.Description>",
          "      </Popover.Content>",
          "    </Popover.Positioner>",
          "  </Portal>",
          "</Popover.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Popover with an arrow, title, description and close button",
        code: [
          '<script setup lang="ts">',
          'import { Button, Popover, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Popover.Root>",
          "    <Popover.Trigger as-child>",
          "      <Button>Share</Button>",
          "    </Popover.Trigger>",
          "    <Portal>",
          "      <Popover.Positioner>",
          "        <Popover.Content>",
          "          <Popover.Arrow>",
          "            <Popover.ArrowTip />",
          "          </Popover.Arrow>",
          "          <Popover.Title>Share this page</Popover.Title>",
          "          <Popover.Description>Anyone with the link can view it.</Popover.Description>",
          '          <Popover.CloseTrigger aria-label="Close">×</Popover.CloseTrigger>',
          "        </Popover.Content>",
          "      </Popover.Positioner>",
          "    </Portal>",
          "  </Popover.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Popover with an arrow, title, description and close button",
        code: [
          '<script lang="ts">',
          '  import { Button, Popover, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Popover.Root>",
          "  <Popover.Trigger>",
          "    {#snippet asChild(triggerProps)}",
          "      <Button {...triggerProps()}>Share</Button>",
          "    {/snippet}",
          "  </Popover.Trigger>",
          "  <Portal>",
          "    <Popover.Positioner>",
          "      <Popover.Content>",
          "        <Popover.Arrow>",
          "          <Popover.ArrowTip />",
          "        </Popover.Arrow>",
          "        <Popover.Title>Share this page</Popover.Title>",
          "        <Popover.Description>Anyone with the link can view it.</Popover.Description>",
          '        <Popover.CloseTrigger aria-label="Close">×</Popover.CloseTrigger>',
          "      </Popover.Content>",
          "    </Popover.Positioner>",
          "  </Portal>",
          "</Popover.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Popover with an arrow, title, description and close button",
        code: [
          'import { Button, Popover, Portal } from "@moderno-ui/solid";',
          "",
          "<Popover.Root>",
          "  <Popover.Trigger",
          "    asChild={(triggerProps) => <Button {...triggerProps()}>Share</Button>}",
          "  />",
          "  <Portal>",
          "    <Popover.Positioner>",
          "      <Popover.Content>",
          "        <Popover.Arrow>",
          "          <Popover.ArrowTip />",
          "        </Popover.Arrow>",
          "        <Popover.Title>Share this page</Popover.Title>",
          "        <Popover.Description>Anyone with the link can view it.</Popover.Description>",
          '        <Popover.CloseTrigger aria-label="Close">×</Popover.CloseTrigger>',
          "      </Popover.Content>",
          "    </Popover.Positioner>",
          "  </Portal>",
          "</Popover.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
