import { progressRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Progress",
  slug: "progress",
  scope: "progress",
  props: { file: "src/progress.tsx", type: "ModernoProgressRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds a linear or a circular progress." },
    { name: "label", description: "Optional; names what is in progress." },
    { name: "value-text", description: "Optional; the percentage, or your own text." },
    { name: "track", description: "The linear progressbar; holds the range." },
    { name: "range", description: "The filled part of the track, as wide as the value." },
    { name: "circle", description: "The circular progressbar, an <svg>." },
    { name: "circle-track", description: "The full ring behind the range." },
    { name: "circle-range", description: "The arc drawn as far as the value." },
    { name: "view", description: "Optional; shows its children in one state only." },
  ],
  variants: progressRecipe.variants,
  examples: {
    react: [
      {
        title: "A labelled bar with the percentage",
        code: [
          'import { Progress } from "@moderno-ui/react";',
          "",
          "<Progress.Root value={uploaded}>",
          "  <Progress.Label>Uploading photos</Progress.Label>",
          "  <Progress.ValueText />",
          "  <Progress.Track>",
          "    <Progress.Range />",
          "  </Progress.Track>",
          "</Progress.Root>",
        ].join("\n"),
      },
      {
        title: "A circle that spins while the amount is unknown",
        code: [
          'import { Progress } from "@moderno-ui/react";',
          "",
          "<Progress.Root value={null}>",
          "  <Progress.Circle>",
          "    <Progress.CircleTrack />",
          "    <Progress.CircleRange />",
          "  </Progress.Circle>",
          "</Progress.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A labelled bar with the percentage",
        code: [
          '<script setup lang="ts">',
          'import { Progress } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Progress.Root :model-value="uploaded">',
          "    <Progress.Label>Uploading photos</Progress.Label>",
          "    <Progress.ValueText />",
          "    <Progress.Track>",
          "      <Progress.Range />",
          "    </Progress.Track>",
          "  </Progress.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A circle that spins while the amount is unknown",
        code: [
          '<script setup lang="ts">',
          'import { Progress } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Progress.Root :model-value="null">',
          "    <Progress.Circle>",
          "      <Progress.CircleTrack />",
          "      <Progress.CircleRange />",
          "    </Progress.Circle>",
          "  </Progress.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A labelled bar with the percentage",
        code: [
          '<script lang="ts">',
          '  import { Progress } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Progress.Root value={uploaded}>",
          "  <Progress.Label>Uploading photos</Progress.Label>",
          "  <Progress.ValueText />",
          "  <Progress.Track>",
          "    <Progress.Range />",
          "  </Progress.Track>",
          "</Progress.Root>",
        ].join("\n"),
      },
      {
        title: "A circle that spins while the amount is unknown",
        code: [
          '<script lang="ts">',
          '  import { Progress } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Progress.Root value={null}>",
          "  <Progress.Circle>",
          "    <Progress.CircleTrack />",
          "    <Progress.CircleRange />",
          "  </Progress.Circle>",
          "</Progress.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A labelled bar with the percentage",
        code: [
          'import { Progress } from "@moderno-ui/solid";',
          "",
          "<Progress.Root value={uploaded}>",
          "  <Progress.Label>Uploading photos</Progress.Label>",
          "  <Progress.ValueText />",
          "  <Progress.Track>",
          "    <Progress.Range />",
          "  </Progress.Track>",
          "</Progress.Root>",
        ].join("\n"),
      },
      {
        title: "A circle that spins while the amount is unknown",
        code: [
          'import { Progress } from "@moderno-ui/solid";',
          "",
          "<Progress.Root defaultValue={null}>",
          "  <Progress.Circle>",
          "    <Progress.CircleTrack />",
          "    <Progress.CircleRange />",
          "  </Progress.Circle>",
          "</Progress.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
