import { radioGroupRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "RadioGroup",
  slug: "radio-group",
  scope: "radio-group",
  props: { file: "src/radio-group.tsx", type: "ModernoRadioGroupRootProps" },
  parts: [
    { name: "root" },
    { name: "label", description: "The group's label; it names the radiogroup." },
    { name: "item", description: "One option: a <label> around its radio; a card in a tile." },
    {
      name: "item-media",
      description:
        "Moderno's slot for a tile's image or other content, at the root's aspectRatio; its image takes alt=\"\" unless the item has no item-text.",
    },
    { name: "item-control", description: "The radio circle; a tile's check badge." },
    { name: "item-text", description: "The option's label; names its radio." },
    {
      name: "item-description",
      description: "Moderno's hint under an option's label; goes inside item-text.",
    },
    { name: "indicator", description: "Ark's sliding highlight; unstyled by default." },
  ],
  // `columns` is a number prop, not a recipe variant: it lands as
  // `data-columns` on the root, so it is absent from `variants`.
  variants: radioGroupRecipe.variants,
  examples: {
    react: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          'import { RadioGroup } from "@moderno-ui/react";',
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
      {
        title: "Pick a layout by its thumbnail (tiles)",
        code: [
          'import { RadioGroup } from "@moderno-ui/react";',
          "",
          '<RadioGroup.Root variant="tile" columns={3} defaultValue="title" onValueChange={save}>',
          "  <RadioGroup.Label>Layout</RadioGroup.Label>",
          "  {layouts.map((layout) => (",
          "    <RadioGroup.Item key={layout.value} value={layout.value}>",
          "      <RadioGroup.ItemMedia>",
          '        <img src={layout.thumbnail} alt="" />',
          "      </RadioGroup.ItemMedia>",
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>{layout.label}</RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          "  ))}",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          '<script setup lang="ts">',
          'import { RadioGroup } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <RadioGroup.Root default-value="standard" @value-change="save">',
          "    <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '    <RadioGroup.Item value="standard">',
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>",
          "        Standard",
          "        <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "      </RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          '    <RadioGroup.Item value="express">',
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>",
          "        Express",
          "        <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "      </RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          "  </RadioGroup.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Pick a layout by its thumbnail (tiles)",
        code: [
          '<script setup lang="ts">',
          'import { RadioGroup } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <RadioGroup.Root variant="tile" :columns="3" default-value="title" @value-change="save">',
          "    <RadioGroup.Label>Layout</RadioGroup.Label>",
          '    <RadioGroup.Item v-for="layout in layouts" :key="layout.value" :value="layout.value">',
          "      <RadioGroup.ItemMedia>",
          '        <img :src="layout.thumbnail" alt="" />',
          "      </RadioGroup.ItemMedia>",
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>{{ layout.label }}</RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          "  </RadioGroup.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          '<script lang="ts">',
          '  import { RadioGroup } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
      {
        title: "Pick a layout by its thumbnail (tiles)",
        code: [
          '<script lang="ts">',
          '  import { RadioGroup } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<RadioGroup.Root variant="tile" columns={3} defaultValue="title" onValueChange={save}>',
          "  <RadioGroup.Label>Layout</RadioGroup.Label>",
          "  {#each layouts as layout (layout.value)}",
          "    <RadioGroup.Item value={layout.value}>",
          "      <RadioGroup.ItemMedia>",
          '        <img src={layout.thumbnail} alt="" />',
          "      </RadioGroup.ItemMedia>",
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>{layout.label}</RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          "  {/each}",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          'import { RadioGroup } from "@moderno-ui/solid";',
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
      {
        title: "Pick a layout by its thumbnail (tiles)",
        code: [
          'import { For } from "solid-js";',
          'import { RadioGroup } from "@moderno-ui/solid";',
          "",
          '<RadioGroup.Root variant="tile" columns={3} defaultValue="title" onValueChange={save}>',
          "  <RadioGroup.Label>Layout</RadioGroup.Label>",
          "  <For each={layouts}>",
          "    {(layout) => (",
          "      <RadioGroup.Item value={layout.value}>",
          "        <RadioGroup.ItemMedia>",
          '          <img src={layout.thumbnail} alt="" />',
          "        </RadioGroup.ItemMedia>",
          "        <RadioGroup.ItemControl />",
          "        <RadioGroup.ItemText>{layout.label}</RadioGroup.ItemText>",
          "        <RadioGroup.ItemHiddenInput />",
          "      </RadioGroup.Item>",
          "    )}",
          "  </For>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
