import { selectRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Select",
  slug: "select",
  scope: "select",
  props: { file: "src/select.tsx", type: "ModernoSelectRootProps" },
  parts: [
    { name: "root" },
    { name: "label" },
    { name: "trigger" },
    { name: "content" },
    { name: "item" },
  ],
  variants: selectRecipe.variants,
  examples: {
    react: [
      {
        title: "Framework picker",
        code: [
          'import { Select, Portal, createListCollection } from "@moderno-ui/react";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          '<Select.Root collection={collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {collection.items.map((item) => (",
          "          <Select.Item key={item.value} item={item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        ))}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Framework picker",
        code: [
          '<script setup lang="ts">',
          'import { Select, Portal, createListCollection } from "@moderno-ui/vue";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "</script>",
          "",
          "<template>",
          '  <Select.Root :collection="collection" size="sm">',
          "    <Select.Label>Framework</Select.Label>",
          "    <Select.Control>",
          "      <Select.Trigger>",
          '        <Select.ValueText placeholder="Pick one" />',
          "        <Select.Indicator>▼</Select.Indicator>",
          "      </Select.Trigger>",
          "    </Select.Control>",
          "    <Portal>",
          "      <Select.Positioner>",
          "        <Select.Content>",
          '          <Select.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Select.ItemText>{{ item.label }}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        </Select.Content>",
          "      </Select.Positioner>",
          "    </Portal>",
          "  </Select.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Framework picker",
        code: [
          '<script lang="ts">',
          '  import { Select, Portal, createListCollection } from "@moderno-ui/svelte";',
          "",
          "  const collection = createListCollection({",
          "    items: [",
          '      { label: "React", value: "react" },',
          '      { label: "Vue", value: "vue" },',
          '      { label: "Svelte", value: "svelte" },',
          "    ],",
          "  });",
          "</script>",
          "",
          '<Select.Root {collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {#each collection.items as item (item.value)}",
          "          <Select.Item {item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        {/each}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Framework picker",
        code: [
          'import { For } from "solid-js";',
          'import { Select, Portal, createListCollection } from "@moderno-ui/solid";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          "function FrameworkPicker() {",
          "  return (",
          '    <Select.Root collection={collection} size="sm">',
          "      <Select.Label>Framework</Select.Label>",
          "      <Select.Control>",
          "        <Select.Trigger>",
          '          <Select.ValueText placeholder="Pick one" />',
          "          <Select.Indicator>▼</Select.Indicator>",
          "        </Select.Trigger>",
          "      </Select.Control>",
          "      <Portal>",
          "        <Select.Positioner>",
          "          <Select.Content>",
          "            <For each={collection.items}>",
          "              {(item) => (",
          "                <Select.Item item={item}>",
          "                  <Select.ItemText>{item.label}</Select.ItemText>",
          "                  <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "                </Select.Item>",
          "              )}",
          "            </For>",
          "          </Select.Content>",
          "        </Select.Positioner>",
          "      </Portal>",
          "    </Select.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
