import { sliderRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Slider",
  slug: "slider",
  scope: "slider",
  props: { file: "src/slider.tsx", type: "ModernoSliderRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one slider, single or range." },
    { name: "label", description: "Optional; names the value. Clicking it focuses the thumb." },
    { name: "value-text", description: "Optional; the value, or both ends of a range." },
    { name: "control", description: "The area you click or drag in; holds track and thumbs." },
    { name: "track", description: "The full line of possible values; holds the range." },
    { name: "range", description: "The filled part of the track, up to or between thumbs." },
    { name: "thumb", description: "The handle, role=slider; one per value, with its index." },
    {
      name: "dragging-indicator",
      description: "Optional, inside a thumb; the value in a bubble while dragging.",
    },
    { name: "marker-group", description: "Optional; holds the marks under the track." },
    { name: "marker", description: "A mark at one value, with its own text." },
  ],
  variants: sliderRecipe.variants,
  examples: {
    react: [
      {
        title: "A volume slider with marks",
        code: [
          'import { Slider } from "@moderno-ui/react";',
          "",
          "<Slider.Root value={volume} onValueChange={(e) => setVolume(e.value)}>",
          "  <Slider.Label>Volume</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "  <Slider.MarkerGroup>",
          "    <Slider.Marker value={0}>0</Slider.Marker>",
          "    <Slider.Marker value={50}>50</Slider.Marker>",
          "    <Slider.Marker value={100}>100</Slider.Marker>",
          "  </Slider.MarkerGroup>",
          "</Slider.Root>",
        ].join("\n"),
      },
      {
        title: "A price range between two thumbs",
        code: [
          'import { Slider } from "@moderno-ui/react";',
          "",
          "<Slider.Root defaultValue={[20, 80]}>",
          "  <Slider.Label>Price</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "    <Slider.Thumb index={1}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "</Slider.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A volume slider with marks",
        code: [
          '<script setup lang="ts">',
          'import { Slider } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Slider.Root v-model="volume">',
          "    <Slider.Label>Volume</Slider.Label>",
          "    <Slider.ValueText />",
          "    <Slider.Control>",
          "      <Slider.Track>",
          "        <Slider.Range />",
          "      </Slider.Track>",
          '      <Slider.Thumb :index="0">',
          "        <Slider.HiddenInput />",
          "      </Slider.Thumb>",
          "    </Slider.Control>",
          "    <Slider.MarkerGroup>",
          '      <Slider.Marker :value="0">0</Slider.Marker>',
          '      <Slider.Marker :value="50">50</Slider.Marker>',
          '      <Slider.Marker :value="100">100</Slider.Marker>',
          "    </Slider.MarkerGroup>",
          "  </Slider.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A price range between two thumbs",
        code: [
          '<script setup lang="ts">',
          'import { Slider } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Slider.Root :default-value="[20, 80]">',
          "    <Slider.Label>Price</Slider.Label>",
          "    <Slider.ValueText />",
          "    <Slider.Control>",
          "      <Slider.Track>",
          "        <Slider.Range />",
          "      </Slider.Track>",
          '      <Slider.Thumb :index="0">',
          "        <Slider.HiddenInput />",
          "      </Slider.Thumb>",
          '      <Slider.Thumb :index="1">',
          "        <Slider.HiddenInput />",
          "      </Slider.Thumb>",
          "    </Slider.Control>",
          "  </Slider.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A volume slider with marks",
        code: [
          '<script lang="ts">',
          '  import { Slider } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Slider.Root value={volume} onValueChange={(e) => (volume = e.value)}>",
          "  <Slider.Label>Volume</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "  <Slider.MarkerGroup>",
          "    <Slider.Marker value={0}>0</Slider.Marker>",
          "    <Slider.Marker value={50}>50</Slider.Marker>",
          "    <Slider.Marker value={100}>100</Slider.Marker>",
          "  </Slider.MarkerGroup>",
          "</Slider.Root>",
        ].join("\n"),
      },
      {
        title: "A price range between two thumbs",
        code: [
          '<script lang="ts">',
          '  import { Slider } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Slider.Root defaultValue={[20, 80]}>",
          "  <Slider.Label>Price</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "    <Slider.Thumb index={1}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "</Slider.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A volume slider with marks",
        code: [
          'import { Slider } from "@moderno-ui/solid";',
          "",
          "<Slider.Root value={volume()} onValueChange={(e) => setVolume(e.value)}>",
          "  <Slider.Label>Volume</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "  <Slider.MarkerGroup>",
          "    <Slider.Marker value={0}>0</Slider.Marker>",
          "    <Slider.Marker value={50}>50</Slider.Marker>",
          "    <Slider.Marker value={100}>100</Slider.Marker>",
          "  </Slider.MarkerGroup>",
          "</Slider.Root>",
        ].join("\n"),
      },
      {
        title: "A price range between two thumbs",
        code: [
          'import { Slider } from "@moderno-ui/solid";',
          "",
          "<Slider.Root defaultValue={[20, 80]}>",
          "  <Slider.Label>Price</Slider.Label>",
          "  <Slider.ValueText />",
          "  <Slider.Control>",
          "    <Slider.Track>",
          "      <Slider.Range />",
          "    </Slider.Track>",
          "    <Slider.Thumb index={0}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "    <Slider.Thumb index={1}>",
          "      <Slider.HiddenInput />",
          "    </Slider.Thumb>",
          "  </Slider.Control>",
          "</Slider.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
