import { splitterRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Splitter",
  slug: "splitter",
  scope: "splitter",
  props: { file: "src/splitter.tsx", type: "ModernoSplitterRootProps" },
  parts: [
    { name: "root", description: "Carries variant; lays the panels out in a row or a column." },
    { name: "panel", description: "One resizable panel, with the id it has in panels." },
    {
      name: "resize-trigger",
      description: 'The handle between two panels, role="separator"; id is "before:after".',
    },
    {
      name: "resize-trigger-indicator",
      description: "Optional, inside a trigger; the grip drawn on the rule.",
    },
  ],
  variants: splitterRecipe.variants,
  examples: {
    react: [
      {
        title: "Two panels with a handle between them",
        code: [
          'import { Splitter } from "@moderno-ui/react";',
          "",
          "<Splitter.Root",
          '  panels={[{ id: "files", minSize: 20 }, { id: "editor", minSize: 30 }]}',
          "  defaultSize={[30, 70]}",
          ">",
          '  <Splitter.Panel id="files">Files</Splitter.Panel>',
          '  <Splitter.ResizeTrigger id="files:editor" aria-label="Resize files and editor">',
          "    <Splitter.ResizeTriggerIndicator />",
          "  </Splitter.ResizeTrigger>",
          '  <Splitter.Panel id="editor">Editor</Splitter.Panel>',
          "</Splitter.Root>",
        ].join("\n"),
      },
      {
        title: "Stacked panels in a box, the lower one collapsible",
        code: [
          'import { Splitter } from "@moderno-ui/react";',
          "",
          "<Splitter.Root",
          '  variant="enclosed"',
          '  orientation="vertical"',
          '  panels={[{ id: "code" }, { id: "console", minSize: 20, collapsible: true }]}',
          "  defaultSize={[75, 25]}",
          ">",
          '  <Splitter.Panel id="code">Code</Splitter.Panel>',
          '  <Splitter.ResizeTrigger id="code:console" aria-label="Resize code and console">',
          "    <Splitter.ResizeTriggerIndicator />",
          "  </Splitter.ResizeTrigger>",
          '  <Splitter.Panel id="console">Console</Splitter.Panel>',
          "</Splitter.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Two panels with a handle between them",
        code: [
          '<script setup lang="ts">',
          'import { Splitter } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Splitter.Root",
          "    :panels=\"[{ id: 'files', minSize: 20 }, { id: 'editor', minSize: 30 }]\"",
          '    :default-size="[30, 70]"',
          "  >",
          '    <Splitter.Panel id="files">Files</Splitter.Panel>',
          '    <Splitter.ResizeTrigger id="files:editor" aria-label="Resize files and editor">',
          "      <Splitter.ResizeTriggerIndicator />",
          "    </Splitter.ResizeTrigger>",
          '    <Splitter.Panel id="editor">Editor</Splitter.Panel>',
          "  </Splitter.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Two panels with a handle between them",
        code: [
          '<script lang="ts">',
          '  import { Splitter } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Splitter.Root",
          '  panels={[{ id: "files", minSize: 20 }, { id: "editor", minSize: 30 }]}',
          "  defaultSize={[30, 70]}",
          ">",
          '  <Splitter.Panel id="files">Files</Splitter.Panel>',
          '  <Splitter.ResizeTrigger id="files:editor" aria-label="Resize files and editor">',
          "    <Splitter.ResizeTriggerIndicator />",
          "  </Splitter.ResizeTrigger>",
          '  <Splitter.Panel id="editor">Editor</Splitter.Panel>',
          "</Splitter.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Two panels with a handle between them",
        code: [
          'import { Splitter } from "@moderno-ui/solid";',
          "",
          "<Splitter.Root",
          '  panels={[{ id: "files", minSize: 20 }, { id: "editor", minSize: 30 }]}',
          "  defaultSize={[30, 70]}",
          ">",
          '  <Splitter.Panel id="files">Files</Splitter.Panel>',
          '  <Splitter.ResizeTrigger id="files:editor" aria-label="Resize files and editor">',
          "    <Splitter.ResizeTriggerIndicator />",
          "  </Splitter.ResizeTrigger>",
          '  <Splitter.Panel id="editor">Editor</Splitter.Panel>',
          "</Splitter.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
