import { tagsInputRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "TagsInput",
  slug: "tags-input",
  scope: "tags-input",
  props: { file: "src/tags-input.tsx", type: "ModernoTagsInputRootProps" },
  parts: [
    { name: "root", description: "Carries size; holds one tags field." },
    { name: "label", description: "Optional; names the field. Clicking it focuses the input." },
    { name: "control", description: "The bordered box; holds the tags and the input." },
    { name: "item", description: "One tag, from the Context's value; takes index and value." },
    { name: "item-preview", description: "The tag's chip; double click it to edit the tag." },
    { name: "item-text", description: "The tag's text inside the chip." },
    { name: "item-delete-trigger", description: "A button in the chip that removes the tag." },
    { name: "item-input", description: "The box that replaces the chip while the tag is edited." },
    {
      name: "input",
      description: "The text box; Enter or the delimiter turns its text into a tag.",
    },
    { name: "clear-trigger", description: "Optional; a button that removes every tag." },
  ],
  variants: tagsInputRecipe.variants,
  examples: {
    react: [
      {
        title: "Tags the user types, with a button to remove each",
        code: [
          'import { TagsInput } from "@moderno-ui/react";',
          "",
          "<TagsInput.Root value={tags} onValueChange={(e) => setTags(e.value)}>",
          "  <TagsInput.Label>Frameworks</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {(tagsInput) =>",
          "        tagsInput.value.map((value, index) => (",
          "          <TagsInput.Item key={index} index={index} value={value}>",
          "            <TagsInput.ItemPreview>",
          "              <TagsInput.ItemText>{value}</TagsInput.ItemText>",
          "              <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "            </TagsInput.ItemPreview>",
          "            <TagsInput.ItemInput />",
          "          </TagsInput.Item>",
          "        ))",
          "      }",
          "    </TagsInput.Context>",
          '    <TagsInput.Input placeholder="Add a framework" />',
          "  </TagsInput.Control>",
          "  <TagsInput.HiddenInput />",
          "</TagsInput.Root>",
        ].join("\n"),
      },
      {
        title: "At most three small tags, with a clear button",
        code: [
          'import { TagsInput } from "@moderno-ui/react";',
          "",
          '<TagsInput.Root size="sm" max={3} defaultValue={["design"]}>',
          "  <TagsInput.Label>Topics</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {(tagsInput) =>",
          "        tagsInput.value.map((value, index) => (",
          "          <TagsInput.Item key={index} index={index} value={value}>",
          "            <TagsInput.ItemPreview>",
          "              <TagsInput.ItemText>{value}</TagsInput.ItemText>",
          "              <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "            </TagsInput.ItemPreview>",
          "            <TagsInput.ItemInput />",
          "          </TagsInput.Item>",
          "        ))",
          "      }",
          "    </TagsInput.Context>",
          "    <TagsInput.Input />",
          "    <TagsInput.ClearTrigger>×</TagsInput.ClearTrigger>",
          "  </TagsInput.Control>",
          "</TagsInput.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Tags the user types, with a button to remove each",
        code: [
          '<script setup lang="ts">',
          'import { TagsInput } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <TagsInput.Root v-model="tags">',
          "    <TagsInput.Label>Frameworks</TagsInput.Label>",
          "    <TagsInput.Control>",
          '      <TagsInput.Context v-slot="{ value }">',
          '        <TagsInput.Item v-for="(tag, index) in value" :key="index" :index="index" :value="tag">',
          "          <TagsInput.ItemPreview>",
          "            <TagsInput.ItemText>{{ tag }}</TagsInput.ItemText>",
          "            <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "          </TagsInput.ItemPreview>",
          "          <TagsInput.ItemInput />",
          "        </TagsInput.Item>",
          "      </TagsInput.Context>",
          '      <TagsInput.Input placeholder="Add a framework" />',
          "    </TagsInput.Control>",
          "    <TagsInput.HiddenInput />",
          "  </TagsInput.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "At most three small tags, with a clear button",
        code: [
          '<script setup lang="ts">',
          'import { TagsInput } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <TagsInput.Root size="sm" :max="3" :default-value="[\'design\']">',
          "    <TagsInput.Label>Topics</TagsInput.Label>",
          "    <TagsInput.Control>",
          '      <TagsInput.Context v-slot="{ value }">',
          '        <TagsInput.Item v-for="(tag, index) in value" :key="index" :index="index" :value="tag">',
          "          <TagsInput.ItemPreview>",
          "            <TagsInput.ItemText>{{ tag }}</TagsInput.ItemText>",
          "            <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "          </TagsInput.ItemPreview>",
          "          <TagsInput.ItemInput />",
          "        </TagsInput.Item>",
          "      </TagsInput.Context>",
          "      <TagsInput.Input />",
          "      <TagsInput.ClearTrigger>×</TagsInput.ClearTrigger>",
          "    </TagsInput.Control>",
          "  </TagsInput.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Tags the user types, with a button to remove each",
        code: [
          '<script lang="ts">',
          '  import { TagsInput } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<TagsInput.Root value={tags} onValueChange={(e) => (tags = e.value)}>",
          "  <TagsInput.Label>Frameworks</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {#snippet render(tagsInput)}",
          "        {#each tagsInput().value as value, index (index)}",
          "          <TagsInput.Item {index} {value}>",
          "            <TagsInput.ItemPreview>",
          "              <TagsInput.ItemText>{value}</TagsInput.ItemText>",
          "              <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "            </TagsInput.ItemPreview>",
          "            <TagsInput.ItemInput />",
          "          </TagsInput.Item>",
          "        {/each}",
          "      {/snippet}",
          "    </TagsInput.Context>",
          '    <TagsInput.Input placeholder="Add a framework" />',
          "  </TagsInput.Control>",
          "  <TagsInput.HiddenInput />",
          "</TagsInput.Root>",
        ].join("\n"),
      },
      {
        title: "At most three small tags, with a clear button",
        code: [
          '<script lang="ts">',
          '  import { TagsInput } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<TagsInput.Root size="sm" max={3} defaultValue={["design"]}>',
          "  <TagsInput.Label>Topics</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {#snippet render(tagsInput)}",
          "        {#each tagsInput().value as value, index (index)}",
          "          <TagsInput.Item {index} {value}>",
          "            <TagsInput.ItemPreview>",
          "              <TagsInput.ItemText>{value}</TagsInput.ItemText>",
          "              <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "            </TagsInput.ItemPreview>",
          "            <TagsInput.ItemInput />",
          "          </TagsInput.Item>",
          "        {/each}",
          "      {/snippet}",
          "    </TagsInput.Context>",
          "    <TagsInput.Input />",
          "    <TagsInput.ClearTrigger>×</TagsInput.ClearTrigger>",
          "  </TagsInput.Control>",
          "</TagsInput.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Tags the user types, with a button to remove each",
        code: [
          'import { Index } from "solid-js";',
          'import { TagsInput } from "@moderno-ui/solid";',
          "",
          "<TagsInput.Root value={tags()} onValueChange={(e) => setTags(e.value)}>",
          "  <TagsInput.Label>Frameworks</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {(tagsInput) => (",
          "        <Index each={tagsInput().value}>",
          "          {(value, index) => (",
          "            <TagsInput.Item index={index} value={value()}>",
          "              <TagsInput.ItemPreview>",
          "                <TagsInput.ItemText>{value()}</TagsInput.ItemText>",
          "                <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "              </TagsInput.ItemPreview>",
          "              <TagsInput.ItemInput />",
          "            </TagsInput.Item>",
          "          )}",
          "        </Index>",
          "      )}",
          "    </TagsInput.Context>",
          '    <TagsInput.Input placeholder="Add a framework" />',
          "  </TagsInput.Control>",
          "  <TagsInput.HiddenInput />",
          "</TagsInput.Root>",
        ].join("\n"),
      },
      {
        title: "At most three small tags, with a clear button",
        code: [
          'import { Index } from "solid-js";',
          'import { TagsInput } from "@moderno-ui/solid";',
          "",
          '<TagsInput.Root size="sm" max={3} defaultValue={["design"]}>',
          "  <TagsInput.Label>Topics</TagsInput.Label>",
          "  <TagsInput.Control>",
          "    <TagsInput.Context>",
          "      {(tagsInput) => (",
          "        <Index each={tagsInput().value}>",
          "          {(value, index) => (",
          "            <TagsInput.Item index={index} value={value()}>",
          "              <TagsInput.ItemPreview>",
          "                <TagsInput.ItemText>{value()}</TagsInput.ItemText>",
          "                <TagsInput.ItemDeleteTrigger>×</TagsInput.ItemDeleteTrigger>",
          "              </TagsInput.ItemPreview>",
          "              <TagsInput.ItemInput />",
          "            </TagsInput.Item>",
          "          )}",
          "        </Index>",
          "      )}",
          "    </TagsInput.Context>",
          "    <TagsInput.Input />",
          "    <TagsInput.ClearTrigger>×</TagsInput.ClearTrigger>",
          "  </TagsInput.Control>",
          "</TagsInput.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
