import { toastRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Toast",
  slug: "toast",
  scope: "toast",
  props: { file: "src/toast.tsx", type: "ModernoToastRootProps" },
  parts: [
    {
      name: "group",
      description: "The Toaster: a polite live region Ark pins to the toaster's placement.",
    },
    {
      name: "root",
      description: 'One toast, role="status"; carries data-size and Ark\'s data-type.',
    },
    { name: "title", description: "The toast's accessible name (aria-labelledby)." },
    { name: "description", description: "Wired to the toast's aria-describedby." },
    {
      name: "action-trigger",
      description: "Optional button under the text; runs the action and dismisses.",
    },
    { name: "close-trigger", description: "The icon button in the toast's top corner." },
  ],
  variants: toastRecipe.variants,
  examples: {
    react: [
      {
        title: "A toaster, and a toast created from a button",
        code: [
          'import { Button, Toast, Toaster, createToaster } from "@moderno-ui/react";',
          "",
          'const toaster = createToaster({ placement: "bottom-end" });',
          "",
          "<>",
          "  <Button",
          '    onClick={() => toaster.success({ title: "Saved", description: "Your changes are live." })}',
          "  >",
          "    Save",
          "  </Button>",
          "  <Toaster toaster={toaster}>",
          "    {(toast) => (",
          "      <Toast.Root>",
          "        <Toast.Title>{toast.title}</Toast.Title>",
          "        <Toast.Description>{toast.description}</Toast.Description>",
          '        <Toast.CloseTrigger aria-label="Dismiss">×</Toast.CloseTrigger>',
          "      </Toast.Root>",
          "    )}",
          "  </Toaster>",
          "</>",
        ].join("\n"),
      },
      {
        title: "Small toast with an action",
        code: [
          'import { Toast, Toaster, createToaster } from "@moderno-ui/react";',
          "",
          'const toaster = createToaster({ placement: "top" });',
          'toaster.create({ title: "Message archived", action: { label: "Undo", onClick: restore } });',
          "",
          "<Toaster toaster={toaster}>",
          "  {(toast) => (",
          '    <Toast.Root size="sm">',
          "      <Toast.Title>{toast.title}</Toast.Title>",
          "      {toast.action && <Toast.ActionTrigger>{toast.action.label}</Toast.ActionTrigger>}",
          "    </Toast.Root>",
          "  )}",
          "</Toaster>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A toaster, and a toast created from a button",
        code: [
          '<script setup lang="ts">',
          'import { Button, Toast, Toaster, createToaster } from "@moderno-ui/vue";',
          "",
          'const toaster = createToaster({ placement: "bottom-end" });',
          "</script>",
          "",
          "<template>",
          "  <Button @click=\"toaster.success({ title: 'Saved', description: 'Your changes are live.' })\">",
          "    Save",
          "  </Button>",
          '  <Toaster :toaster="toaster" v-slot="toast">',
          "    <Toast.Root>",
          "      <Toast.Title>{{ toast.title }}</Toast.Title>",
          "      <Toast.Description>{{ toast.description }}</Toast.Description>",
          '      <Toast.CloseTrigger aria-label="Dismiss">×</Toast.CloseTrigger>',
          "    </Toast.Root>",
          "  </Toaster>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A toaster, and a toast created from script",
        code: [
          '<script lang="ts">',
          '  import { Toast, Toaster, createToaster } from "@moderno-ui/svelte";',
          "",
          '  const toaster = createToaster({ placement: "bottom-end" });',
          "",
          "  export function notifySaved() {",
          '    toaster.success({ title: "Saved", description: "Your changes are live." });',
          "  }",
          "</script>",
          "",
          "<Toaster {toaster}>",
          "  {#snippet children(toast)}",
          "    <Toast.Root>",
          "      <Toast.Title>{toast().title}</Toast.Title>",
          "      <Toast.Description>{toast().description}</Toast.Description>",
          '      <Toast.CloseTrigger aria-label="Dismiss">×</Toast.CloseTrigger>',
          "    </Toast.Root>",
          "  {/snippet}",
          "</Toaster>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A toaster, and a toast created from a button",
        code: [
          'import { Button, Toast, Toaster, createToaster } from "@moderno-ui/solid";',
          "",
          'const toaster = createToaster({ placement: "bottom-end" });',
          "",
          "<>",
          "  <Button",
          '    onClick={() => toaster.success({ title: "Saved", description: "Your changes are live." })}',
          "  >",
          "    Save",
          "  </Button>",
          "  <Toaster toaster={toaster}>",
          "    {(toast) => (",
          "      <Toast.Root>",
          "        <Toast.Title>{toast().title}</Toast.Title>",
          "        <Toast.Description>{toast().description}</Toast.Description>",
          '        <Toast.CloseTrigger aria-label="Dismiss">×</Toast.CloseTrigger>',
          "      </Toast.Root>",
          "    )}",
          "  </Toaster>",
          "</>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
