import { tooltipRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Tooltip",
  slug: "tooltip",
  scope: "tooltip",
  props: { file: "src/tooltip.tsx", type: "ModernoTooltipRootProps" },
  parts: [
    { name: "trigger", description: "The element the tooltip describes; hover or focus shows it." },
    { name: "positioner", description: "Places the content next to the trigger." },
    { name: "content", description: "The label itself, role tooltip; carries size." },
    { name: "arrow", description: "Optional; points the content at the trigger." },
    { name: "arrow-tip", description: "The visible tip inside the arrow." },
  ],
  variants: tooltipRecipe.variants,
  examples: {
    react: [
      {
        title: "Button with a tooltip",
        code: [
          'import { Button, Portal, Tooltip } from "@moderno-ui/react";',
          "",
          "<Tooltip.Root>",
          "  <Tooltip.Trigger asChild>",
          '    <Button variant="outline" >Save</Button>',
          "  </Tooltip.Trigger>",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>",
          "        <Tooltip.Arrow>",
          "          <Tooltip.ArrowTip />",
          "        </Tooltip.Arrow>",
          "        Save your changes",
          "      </Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
      {
        title: "Small tooltip on the right, shown at once",
        code: [
          'import { Button, Portal, Tooltip } from "@moderno-ui/react";',
          "",
          '<Tooltip.Root size="sm" openDelay={0} positioning={{ placement: "right" }}>',
          "  <Tooltip.Trigger asChild>",
          '    <Button variant="ghost">Share</Button>',
          "  </Tooltip.Trigger>",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>Copy a link</Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Button with a tooltip",
        code: [
          '<script setup lang="ts">',
          'import { Button, Portal, Tooltip } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Tooltip.Root>",
          "    <Tooltip.Trigger as-child>",
          '      <Button variant="outline" >Save</Button>',
          "    </Tooltip.Trigger>",
          "    <Portal>",
          "      <Tooltip.Positioner>",
          "        <Tooltip.Content>",
          "          <Tooltip.Arrow>",
          "            <Tooltip.ArrowTip />",
          "          </Tooltip.Arrow>",
          "          Save your changes",
          "        </Tooltip.Content>",
          "      </Tooltip.Positioner>",
          "    </Portal>",
          "  </Tooltip.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Small tooltip on the right, shown at once",
        code: [
          '<script setup lang="ts">',
          'import { Button, Portal, Tooltip } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Tooltip.Root size="sm" :open-delay="0" :positioning="{ placement: \'right\' }">',
          "    <Tooltip.Trigger as-child>",
          '      <Button variant="ghost">Share</Button>',
          "    </Tooltip.Trigger>",
          "    <Portal>",
          "      <Tooltip.Positioner>",
          "        <Tooltip.Content>Copy a link</Tooltip.Content>",
          "      </Tooltip.Positioner>",
          "    </Portal>",
          "  </Tooltip.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Button with a tooltip",
        code: [
          '<script lang="ts">',
          '  import { Button, Portal, Tooltip } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Tooltip.Root>",
          "  <Tooltip.Trigger>",
          "    {#snippet asChild(triggerProps)}",
          '      <Button variant="outline" {...triggerProps()}>Save</Button>',
          "    {/snippet}",
          "  </Tooltip.Trigger>",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>",
          "        <Tooltip.Arrow>",
          "          <Tooltip.ArrowTip />",
          "        </Tooltip.Arrow>",
          "        Save your changes",
          "      </Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
      {
        title: "Small tooltip on the right, shown at once",
        code: [
          '<script lang="ts">',
          '  import { Button, Portal, Tooltip } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Tooltip.Root size="sm" openDelay={0} positioning={{ placement: "right" }}>',
          "  <Tooltip.Trigger>",
          "    {#snippet asChild(triggerProps)}",
          '      <Button variant="ghost" {...triggerProps()}>Share</Button>',
          "    {/snippet}",
          "  </Tooltip.Trigger>",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>Copy a link</Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Button with a tooltip",
        code: [
          'import { Button, Portal, Tooltip } from "@moderno-ui/solid";',
          "",
          "<Tooltip.Root>",
          "  <Tooltip.Trigger",
          "    asChild={(triggerProps) => (",
          '      <Button {...triggerProps()} variant="outline">',
          "        Save",
          "      </Button>",
          "    )}",
          "  />",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>",
          "        <Tooltip.Arrow>",
          "          <Tooltip.ArrowTip />",
          "        </Tooltip.Arrow>",
          "        Save your changes",
          "      </Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
      {
        title: "Small tooltip on the right, shown at once",
        code: [
          'import { Button, Portal, Tooltip } from "@moderno-ui/solid";',
          "",
          '<Tooltip.Root size="sm" openDelay={0} positioning={{ placement: "right" }}>',
          "  <Tooltip.Trigger",
          "    asChild={(triggerProps) => (",
          '      <Button {...triggerProps()} variant="ghost">',
          "        Share",
          "      </Button>",
          "    )}",
          "  />",
          "  <Portal>",
          "    <Tooltip.Positioner>",
          "      <Tooltip.Content>Copy a link</Tooltip.Content>",
          "    </Tooltip.Positioner>",
          "  </Portal>",
          "</Tooltip.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
