import { toolbarRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "Toolbar",
  slug: "toolbar",
  scope: "toolbar",
  props: { file: "src/toolbar.tsx", type: "ToolbarRootProps" },
  parts: [
    { name: "root", description: "role toolbar, one Tab stop; carries size and orientation." },
    { name: "button", description: "One action; with a label it is icon-only and has a tooltip." },
    { name: "toggle", description: "A button that stays pressed (aria-pressed, data-state)." },
    { name: "group", description: "A run of related items, role group." },
    { name: "separator", description: "A rule between groups, across the toolbar." },
  ],
  variants: toolbarRecipe.variants,
  examples: {
    react: [
      {
        title: "Canvas tools with a pressed toggle and a separator",
        code: [
          'import { Toolbar } from "@moderno-ui/react";',
          "",
          '<Toolbar.Root aria-label="Canvas tools">',
          '  <Toolbar.Button label="Undo" shortcut="⌘Z" onClick={undo}>',
          "    <UndoIcon />",
          "  </Toolbar.Button>",
          '  <Toolbar.Button label="Redo" shortcut="⇧⌘Z" disabled={!canRedo} onClick={redo}>',
          "    <RedoIcon />",
          "  </Toolbar.Button>",
          "  <Toolbar.Separator />",
          '  <Toolbar.Group aria-label="Text style">',
          '    <Toolbar.Toggle label="Bold" pressed={bold} onPressedChange={setBold}>',
          "      <BoldIcon />",
          "    </Toolbar.Toggle>",
          "  </Toolbar.Group>",
          "</Toolbar.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Canvas tools with a pressed toggle and a separator",
        code: [
          '<script setup lang="ts">',
          'import { Toolbar } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Toolbar.Root aria-label="Canvas tools">',
          '    <Toolbar.Button label="Undo" shortcut="⌘Z" @click="undo">',
          "      <UndoIcon />",
          "    </Toolbar.Button>",
          '    <Toolbar.Button label="Redo" shortcut="⇧⌘Z" :disabled="!canRedo" @click="redo">',
          "      <RedoIcon />",
          "    </Toolbar.Button>",
          "    <Toolbar.Separator />",
          '    <Toolbar.Group aria-label="Text style">',
          '      <Toolbar.Toggle v-model:pressed="bold" label="Bold">',
          "        <BoldIcon />",
          "      </Toolbar.Toggle>",
          "    </Toolbar.Group>",
          "  </Toolbar.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Canvas tools with a pressed toggle and a separator",
        code: [
          '<script lang="ts">',
          '  import { Toolbar } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Toolbar.Root aria-label="Canvas tools">',
          '  <Toolbar.Button label="Undo" shortcut="⌘Z" onclick={undo}>',
          "    <UndoIcon />",
          "  </Toolbar.Button>",
          '  <Toolbar.Button label="Redo" shortcut="⇧⌘Z" disabled={!canRedo} onclick={redo}>',
          "    <RedoIcon />",
          "  </Toolbar.Button>",
          "  <Toolbar.Separator />",
          '  <Toolbar.Group aria-label="Text style">',
          '    <Toolbar.Toggle label="Bold" bind:pressed={bold}>',
          "      <BoldIcon />",
          "    </Toolbar.Toggle>",
          "  </Toolbar.Group>",
          "</Toolbar.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Canvas tools with a pressed toggle and a separator",
        code: [
          'import { Toolbar } from "@moderno-ui/solid";',
          "",
          '<Toolbar.Root aria-label="Canvas tools">',
          '  <Toolbar.Button label="Undo" shortcut="⌘Z" onClick={undo}>',
          "    <UndoIcon />",
          "  </Toolbar.Button>",
          '  <Toolbar.Button label="Redo" shortcut="⇧⌘Z" disabled={!canRedo()} onClick={redo}>',
          "    <RedoIcon />",
          "  </Toolbar.Button>",
          "  <Toolbar.Separator />",
          '  <Toolbar.Group aria-label="Text style">',
          '    <Toolbar.Toggle label="Bold" pressed={bold()} onPressedChange={setBold}>',
          "      <BoldIcon />",
          "    </Toolbar.Toggle>",
          "  </Toolbar.Group>",
          "</Toolbar.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
