import { vectorPadRecipe } from "@moderno-ui/core";
import type { ComponentDefinition } from "../component-definition.ts";

export default {
  name: "VectorPad",
  slug: "vector-pad",
  scope: "vector-pad",
  props: { file: "src/vector-pad.tsx", type: "VectorPadRootProps" },
  parts: [
    {
      name: "root",
      description:
        "A group named by the label. Carries size and the handle's place as --vector-pad-x / --vector-pad-y.",
    },
    {
      name: "label",
      description: "Optional; names the pad and the fields. Clicking it focuses the handle.",
    },
    {
      name: "control",
      description:
        "The square pad you press or drag on; holds the grid, the crosshair and the handle.",
    },
    { name: "grid", description: "Optional; lines every quarter of the pad." },
    { name: "crosshair", description: "Optional; lines through the pad's centre." },
    {
      name: "thumb",
      description: 'The handle, role=slider, that says both values ("X 20, Y -10"); takes focus.',
    },
  ],
  variants: vectorPadRecipe.variants,
  examples: {
    react: [
      {
        title: "An offset pad with a number field per axis",
        code: [
          'import { VectorPad } from "@moderno-ui/react";',
          "",
          "<VectorPad.Root value={offset} onValueChange={(e) => setOffset(e.value)}>",
          "  <VectorPad.Label>Shadow offset</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Grid />",
          "    <VectorPad.Crosshair />",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
      {
        title: "A position from 0 to 100, with y growing downward as on screen",
        code: [
          'import { VectorPad } from "@moderno-ui/react";',
          "",
          "<VectorPad.Root min={0} max={100} defaultValue={{ x: 50, y: 50 }} invertY>",
          "  <VectorPad.Label>Focal point</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "An offset pad with a number field per axis",
        code: [
          '<script setup lang="ts">',
          'import { ref } from "vue";',
          'import { VectorPad } from "@moderno-ui/vue";',
          "",
          "const offset = ref({ x: 0, y: 0 });",
          "</script>",
          "",
          "<template>",
          '  <VectorPad.Root v-model="offset">',
          "    <VectorPad.Label>Shadow offset</VectorPad.Label>",
          "    <VectorPad.Control>",
          "      <VectorPad.Grid />",
          "      <VectorPad.Crosshair />",
          "      <VectorPad.Thumb />",
          "    </VectorPad.Control>",
          '    <VectorPad.Input axis="x" />',
          '    <VectorPad.Input axis="y" />',
          "  </VectorPad.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "A position from 0 to 100, with y growing downward as on screen",
        code: [
          '<script setup lang="ts">',
          'import { VectorPad } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <VectorPad.Root :min="0" :max="100" :default-value="{ x: 50, y: 50 }" invert-y>',
          "    <VectorPad.Label>Focal point</VectorPad.Label>",
          "    <VectorPad.Control>",
          "      <VectorPad.Thumb />",
          "    </VectorPad.Control>",
          '    <VectorPad.Input axis="x" />',
          '    <VectorPad.Input axis="y" />',
          "  </VectorPad.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "An offset pad with a number field per axis",
        code: [
          '<script lang="ts">',
          '  import { VectorPad } from "@moderno-ui/svelte";',
          "",
          "  let offset = $state({ x: 0, y: 0 });",
          "</script>",
          "",
          "<VectorPad.Root bind:value={offset}>",
          "  <VectorPad.Label>Shadow offset</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Grid />",
          "    <VectorPad.Crosshair />",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
      {
        title: "A position from 0 to 100, with y growing downward as on screen",
        code: [
          '<script lang="ts">',
          '  import { VectorPad } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<VectorPad.Root min={0} max={100} defaultValue={{ x: 50, y: 50 }} invertY>",
          "  <VectorPad.Label>Focal point</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "An offset pad with a number field per axis",
        code: [
          'import { VectorPad } from "@moderno-ui/solid";',
          "",
          "<VectorPad.Root value={offset()} onValueChange={(e) => setOffset(e.value)}>",
          "  <VectorPad.Label>Shadow offset</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Grid />",
          "    <VectorPad.Crosshair />",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
      {
        title: "A position from 0 to 100, with y growing downward as on screen",
        code: [
          'import { VectorPad } from "@moderno-ui/solid";',
          "",
          "<VectorPad.Root min={0} max={100} defaultValue={{ x: 50, y: 50 }} invertY>",
          "  <VectorPad.Label>Focal point</VectorPad.Label>",
          "  <VectorPad.Control>",
          "    <VectorPad.Thumb />",
          "  </VectorPad.Control>",
          '  <VectorPad.Input axis="x" />',
          '  <VectorPad.Input axis="y" />',
          "</VectorPad.Root>",
        ].join("\n"),
      },
    ],
  },
} satisfies ComponentDefinition;
