#!/usr/bin/env node
/**
 * `pnpm theme:build` — compile the neutral defaults, then every theme under
 * registry/themes/ (or the dirs passed as args).
 *
 * The neutral defaults come first: packages/css/src/tokens.dtcg.json compiles
 * into packages/css/src/tokens.css, validated like a theme plus every extended
 * slot required (a theme inherits those from here). Each theme's DESIGN.md
 * reads the defaults from that same DTCG file, never from the generated
 * tokens.css, so nothing here reads its own output.
 *
 * For each theme: reads tokens.dtcg.json, writes theme.css and DESIGN.md
 * beside it, prints WCAG AA contrast warnings, and exits non-zero on any
 * validation error so CI fails on an invalid schema.
 *
 * DESIGN.md is regenerated whole except for its brand notes, which are read
 * back from the current file and kept verbatim. Nothing else downstream of a
 * tokens.dtcg.json is edited by hand.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { defaultsFrom, readBrandNotes, renderDesignMd } from "./design-md.ts";
import { compileTheme, ThemeValidationError } from "./index.ts";

const NEUTRAL_DTCG = resolve("packages/css/src/tokens.dtcg.json");
const NEUTRAL_CSS = resolve("packages/css/src/tokens.css");

function themeDirs(args: string[]): string[] {
  if (args.length > 0) return args.map((a) => resolve(a));
  const root = resolve("registry/themes");
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => join(root, e.name));
}

function main(): number {
  const dirs = themeDirs(process.argv.slice(2));
  if (dirs.length === 0) {
    console.error("theme:build — no themes found under registry/themes/");
    return 1;
  }

  let neutral: unknown;
  try {
    neutral = JSON.parse(readFileSync(NEUTRAL_DTCG, "utf8"));
    const { css, warnings } = compileTheme(neutral, { neutral: true });
    writeFileSync(NEUTRAL_CSS, banner(NEUTRAL_DTCG) + css);
    console.log(`✓ ${rel(NEUTRAL_CSS)}`);
    for (const w of warnings) console.warn(`  ⚠ ${w}`);
  } catch (err) {
    // Every theme inherits from the neutral defaults: without them, stop.
    console.error(`✗ ${rel(NEUTRAL_DTCG)}: ${(err as Error).message}`);
    return 1;
  }

  const defaults = defaultsFrom(neutral);
  let failed = 0;
  for (const dir of dirs) {
    const input = join(dir, "tokens.dtcg.json");
    if (!existsSync(input)) {
      console.error(`✗ ${dir}: missing tokens.dtcg.json`);
      failed++;
      continue;
    }
    try {
      const doc = JSON.parse(readFileSync(input, "utf8"));
      const { css, warnings } = compileTheme(doc);
      const out = join(dir, "theme.css");
      writeFileSync(out, banner(input) + css);
      console.log(`✓ ${rel(out)}`);
      for (const w of warnings) console.warn(`  ⚠ ${w}`);

      const designMd = join(dir, "DESIGN.md");
      const brandNotes = existsSync(designMd)
        ? readBrandNotes(readFileSync(designMd, "utf8"))
        : null;
      writeFileSync(designMd, renderDesignMd(doc, defaults, { brandNotes }));
      console.log(`✓ ${rel(designMd)}${brandNotes === null ? " (drafted brand notes)" : ""}`);
    } catch (err) {
      failed++;
      if (err instanceof ThemeValidationError) {
        console.error(`✗ ${rel(input)}: ${err.message}`);
      } else {
        console.error(`✗ ${rel(input)}: ${(err as Error).message}`);
      }
    }
  }
  return failed > 0 ? 1 : 0;
}

function banner(input: string): string {
  return `/* Generated by @moderno-ui/theme-compile from ${rel(input)}. Do not edit by hand. */\n`;
}

function rel(p: string): string {
  return p.replace(resolve(".") + "/", "");
}

process.exit(main());
