#!/usr/bin/env node
/**
 * `pnpm theme:build` — compile every theme under registry/themes/ (or the dirs
 * passed as args). Reads tokens.dtcg.json, writes theme.css beside it, prints
 * WCAG AA contrast warnings, and exits non-zero on any validation error so CI
 * fails on an invalid schema.
 *
 * Compiling the default theme also re-renders DESIGN.md's front matter from its
 * tokens.dtcg.json, since DESIGN.md describes that theme. Nothing downstream of
 * a tokens.dtcg.json is edited by hand.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { defaultsFrom, readMeta, renderFrontMatter, withFrontMatter } from "./design-md.ts";
import { compileTheme, ThemeValidationError } from "./index.ts";

/** The theme DESIGN.md describes. */
const DEFAULT_THEME = "theme-moderno";
const DESIGN_MD = resolve("DESIGN.md");
const TOKENS_CSS = resolve("packages/tokens/src/tokens.css");

function themeDirs(args: string[]): string[] {
  if (args.length > 0) return args.map((a) => resolve(a));
  const root = resolve("registry/themes");
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => join(root, e.name));
}

function main(): number {
  const dirs = themeDirs(process.argv.slice(2));
  if (dirs.length === 0) {
    console.error("theme:build — no themes found under registry/themes/");
    return 1;
  }

  let failed = 0;
  for (const dir of dirs) {
    const input = join(dir, "tokens.dtcg.json");
    if (!existsSync(input)) {
      console.error(`✗ ${dir}: missing tokens.dtcg.json`);
      failed++;
      continue;
    }
    try {
      const doc = JSON.parse(readFileSync(input, "utf8"));
      const { css, warnings } = compileTheme(doc);
      const out = join(dir, "theme.css");
      writeFileSync(out, banner(input) + css);
      console.log(`✓ ${rel(out)}`);
      for (const w of warnings) console.warn(`  ⚠ ${w}`);
      if (basename(dir) === DEFAULT_THEME) {
        const markdown = readFileSync(DESIGN_MD, "utf8");
        const defaults = defaultsFrom(readFileSync(TOKENS_CSS, "utf8"));
        const frontMatter = renderFrontMatter(doc, defaults, readMeta(markdown));
        writeFileSync(DESIGN_MD, withFrontMatter(markdown, frontMatter));
        console.log(`✓ ${rel(DESIGN_MD)} front matter`);
      }
    } catch (err) {
      failed++;
      if (err instanceof ThemeValidationError) {
        console.error(`✗ ${rel(input)}: ${err.message}`);
      } else {
        console.error(`✗ ${rel(input)}: ${(err as Error).message}`);
      }
    }
  }
  return failed > 0 ? 1 : 0;
}

function banner(input: string): string {
  return `/* Generated by @moderno-ui/theme-compile from ${rel(input)}. Do not edit by hand. */\n`;
}

function rel(p: string): string {
  return p.replace(resolve(".") + "/", "");
}

process.exit(main());
