// Generated by pnpm gen (core-machines) from packages/core/src/machines/*/index.ts. Do not edit by hand.
/**
 * Component machines — the behaviour Ark does not ship, as Zag 1.x machines
 * (ADR-0010).
 *
 * Each machine sits in `machines/<slug>/` with Zag's own file split
 * (`<slug>.anatomy.ts`, `<slug>.types.ts`, `<slug>.machine.ts`,
 * `<slug>.connect.ts`) and an `index.ts` that re-exports them. It is exported
 * here as one namespace, so a binding reads it like a Zag package:
 * `useMachine(toolbar.machine, props)`, then
 * `toolbar.connect(service, normalizeProps)`.
 */

export * as sortableList from "./machines/sortable-list/index.js";
export * as toolbar from "./machines/toolbar/index.js";
export * as vectorPad from "./machines/vector-pad/index.js";
