// Generated by pnpm gen (core-recipes) from packages/core/src/recipes/*.ts. Do not edit by hand.
/**
 * Component recipes — the variant tables shared by every framework binding.
 *
 * A recipe is just a `cva` instance: it maps public props to deterministic
 * `data-*` attributes on a component's root part. Recipes live in `@moderno-ui/core`
 * (not in the React/Vue/Svelte/Solid packages) so all bindings resolve variants
 * identically — the framework only differs in how it spreads the attributes onto
 * markup. `components.css` styles those attributes; the recipe and the stylesheet
 * are the two halves of one contract.
 *
 * Visual states that Ark already tracks (invalid, disabled, highlighted, open)
 * are NOT recipe variants — they surface as Ark's own `data-*` attributes and
 * are styled directly. Recipes only carry the choices a consumer makes via props.
 *
 * Each component's recipe sits in `recipes/<slug>.ts` with the variant unions
 * derived from it. Bindings import those names instead of re-deriving them from
 * the recipe tables, so a recipe change ripples to every framework through this
 * seam.
 */

export * from "./recipes/accordion.js";
export * from "./recipes/alert.js";
export * from "./recipes/avatar.js";
export * from "./recipes/badge.js";
export * from "./recipes/button.js";
export * from "./recipes/callout.js";
export * from "./recipes/card.js";
export * from "./recipes/checkbox.js";
export * from "./recipes/chip.js";
export * from "./recipes/divider.js";
export * from "./recipes/field.js";
export * from "./recipes/indicator.js";
export * from "./recipes/number-input.js";
export * from "./recipes/pagination.js";
export * from "./recipes/pin-input.js";
export * from "./recipes/progress.js";
export * from "./recipes/radio-group.js";
export * from "./recipes/select.js";
export * from "./recipes/skeleton.js";
export * from "./recipes/slider.js";
export * from "./recipes/spinner.js";
export * from "./recipes/switch.js";
export * from "./recipes/tabs.js";
export * from "./recipes/toggle.js";
export * from "./recipes/toggle-group.js";
