// Generated by pnpm gen (react-playground) from packages/react/playground/sections/*.tsx. Do not edit by hand.
/**
 * SSR playground — the reusable harness that validates Moderno's second
 * guarantee: server-render + hydrate with zero React warnings.
 *
 * It mounts one section per component, each in its default (closed) state.
 * A section lives in `sections/<slug>.tsx` and says which SSR hazard its
 * component exercises; `test/ssr/<slug>.test.tsx` asserts that section's
 * server string on its own.
 *
 * The same tree is `renderToString`-ed on the server and `hydrateRoot`-ed on the
 * client. `open` mounts the Dialog and Select popovers so the SSR test can
 * exercise the harder hazard the spec calls out — portal content + `useId`-based
 * `aria-controls`/`aria-activedescendant` wiring must still hydrate clean.
 * Phases 3–4 reuse this shape for the other frameworks.
 */
import AccordionSection from "./sections/accordion.js";
import AlertSection from "./sections/alert.js";
import AvatarSection from "./sections/avatar.js";
import BadgeSection from "./sections/badge.js";
import ButtonSection from "./sections/button.js";
import CalloutSection from "./sections/callout.js";
import CardSection from "./sections/card.js";
import ChartsSection from "./sections/charts.js";
import CheckboxSection from "./sections/checkbox.js";
import ChipSection from "./sections/chip.js";
import DialogSection from "./sections/dialog.js";
import DividerSection from "./sections/divider.js";
import FieldSection from "./sections/field.js";
import IndicatorSection from "./sections/indicator.js";
import NumberInputSection from "./sections/number-input.js";
import PaginationSection from "./sections/pagination.js";
import PinInputSection from "./sections/pin-input.js";
import ProgressSection from "./sections/progress.js";
import RadioGroupSection from "./sections/radio-group.js";
import SelectSection from "./sections/select.js";
import SkeletonSection from "./sections/skeleton.js";
import SliderSection from "./sections/slider.js";
import SpinnerSection from "./sections/spinner.js";
import SwitchSection from "./sections/switch.js";
import TabsSection from "./sections/tabs.js";
import ToggleSection from "./sections/toggle.js";
import ToggleGroupSection from "./sections/toggle-group.js";

export interface AppProps {
  /** Mount the Dialog + Select popovers open (exercises the portal/id path). */
  open?: boolean;
}

export function App({ open = false }: AppProps) {
  return (
    <main>
      <AccordionSection open={open} />
      <AlertSection open={open} />
      <AvatarSection open={open} />
      <BadgeSection open={open} />
      <ButtonSection open={open} />
      <CalloutSection open={open} />
      <CardSection open={open} />
      <ChartsSection open={open} />
      <CheckboxSection open={open} />
      <ChipSection open={open} />
      <DialogSection open={open} />
      <DividerSection open={open} />
      <FieldSection open={open} />
      <IndicatorSection open={open} />
      <NumberInputSection open={open} />
      <PaginationSection open={open} />
      <PinInputSection open={open} />
      <ProgressSection open={open} />
      <RadioGroupSection open={open} />
      <SelectSection open={open} />
      <SkeletonSection open={open} />
      <SliderSection open={open} />
      <SpinnerSection open={open} />
      <SwitchSection open={open} />
      <TabsSection open={open} />
      <ToggleSection open={open} />
      <ToggleGroupSection open={open} />
    </main>
  );
}
