import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import postcss, { type Declaration, type Rule } from "postcss";
import { CONTRACT, EXTENDED_SLOTS } from "@moderno-ui/css/contract";
import { compileTheme, ThemeValidationError } from "../src/index.ts";

/**
 * The neutral defaults are authored like a theme (ADR-0008, decision 3):
 * packages/css/src/tokens.dtcg.json is the hand-edited source, and
 * `pnpm theme:build` compiles it into packages/css/src/tokens.css.
 */
const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const source = "packages/css/src/tokens.dtcg.json";
const read = (path: string) => readFileSync(`${repoRoot}${path}`, "utf8");
const neutral = () => JSON.parse(read(source));

/**
 * What every contract slot resolves to on `<html>` in light mode (`:root`)
 * and dark mode (`<html class="dark">`: `:root` plus `.dark`, which has the
 * same specificity and comes later).
 */
function resolved(css: string): { light: Map<string, string>; dark: Map<string, string> } {
  const bySelector = new Map<string, Map<string, string>>();
  postcss.parse(css).walkRules((rule: Rule) => {
    const decls = bySelector.get(rule.selector) ?? new Map<string, string>();
    rule.walkDecls((decl: Declaration) => {
      if (decl.prop.startsWith("--")) decls.set(decl.prop.slice(2), decl.value);
    });
    bySelector.set(rule.selector, decls);
  });
  expect([...bySelector.keys()].sort()).toEqual([".dark", ":root"]);
  const light = bySelector.get(":root")!;
  return { light, dark: new Map([...light, ...bySelector.get(".dark")!]) };
}

describe("the neutral defaults", () => {
  it("compile as a brand-less theme with every slot, clearing WCAG AA in both scopes", () => {
    const { warnings } = compileTheme(neutral(), { neutral: true });
    expect(warnings).toEqual([]);
  });

  it("committed tokens.css matches a fresh compile of tokens.dtcg.json", () => {
    const banner = `/* Generated by @moderno-ui/theme-compile from ${source}. Do not edit by hand. */\n`;
    const { css } = compileTheme(neutral(), { neutral: true });
    expect(read("packages/css/src/tokens.css"), "run `pnpm theme:build`").toBe(banner + css);
  });

  it("define every contract slot in the light scope and nothing outside the contract", () => {
    const doc = neutral();
    const names = CONTRACT.map((s) => s.name);
    expect(Object.keys(doc.light).sort()).toEqual([...names].sort());
    for (const slot of Object.keys(doc.dark)) expect(names).toContain(slot);
  });

  /**
   * Like a theme, the dark scope overrides an extended slot only where dark
   * mode changes it: repeating the light value would be a second copy of it.
   */
  it("override an extended slot in the dark scope only with a different value", () => {
    const doc = neutral();
    const repeated = EXTENDED_SLOTS.filter(
      (slot) => doc.dark[slot] !== undefined && doc.dark[slot].$value === doc.light[slot].$value,
    );
    expect(repeated, "drop these from the dark scope").toEqual([]);
  });

  it("keep the reason for a value as a one-line $description", () => {
    const doc = neutral();
    for (const scope of ["light", "dark"] as const) {
      for (const [slot, token] of Object.entries(doc[scope] as Record<string, object>)) {
        if (!("$description" in token)) continue;
        const description = (token as { $description: unknown }).$description;
        expect(typeof description, `${scope}.${slot}`).toBe("string");
        expect((description as string).trim(), `${scope}.${slot}`).not.toBe("");
        expect(description, `${scope}.${slot}`).not.toMatch(/\n/);
      }
    }
  });

  /**
   * #250 replaced a hand-written tokens.css with one compiled from
   * tokens.dtcg.json. The fixture is that hand-written file, byte for byte, so
   * this proves the switch changed no value in either mode. Once a neutral
   * value changes on purpose, delete this test and its fixture.
   */
  it("resolve every slot to the value the hand-written tokens.css had (#250)", () => {
    const before = resolved(
      readFileSync(
        fileURLToPath(new URL("fixtures/tokens.before-250.css", import.meta.url)),
        "utf8",
      ),
    );
    const after = resolved(read("packages/css/src/tokens.css"));
    for (const scope of ["light", "dark"] as const) {
      for (const { name } of CONTRACT) {
        expect(before[scope].get(name), `${scope} --${name} before`).toBeDefined();
        expect(after[scope].get(name), `${scope} --${name}`).toBe(before[scope].get(name));
      }
      expect([...after[scope].keys()].sort()).toEqual([...before[scope].keys()].sort());
    }
  });
});

describe("compileTheme — neutral mode", () => {
  it("requires every extended slot in the light scope, which a theme may omit", () => {
    const doc = neutral();
    delete doc.light["container-md"];
    delete doc.dark["container-md"];
    expect(() => compileTheme(doc)).not.toThrow();
    expect(() => compileTheme(doc, { neutral: true })).toThrow(ThemeValidationError);
    expect(() => compileTheme(doc, { neutral: true })).toThrow(/light.*container-md/);
  });

  it("lets the dark scope inherit an extended slot from the light one", () => {
    const doc = neutral();
    delete doc.dark.overlay;
    expect(() => compileTheme(doc, { neutral: true })).not.toThrow();
  });

  it("still requires the slots every theme defines in both scopes", () => {
    const doc = neutral();
    delete doc.dark.radius;
    expect(() => compileTheme(doc, { neutral: true })).toThrow(/dark.*radius/);
  });

  it("warns on a failing contrast pair, as for a theme", () => {
    const doc = neutral();
    doc.light["muted-foreground"].$value = "oklch(0.92 0 0)";
    const { warnings } = compileTheme(doc, { neutral: true });
    expect(warnings.join("\n")).toMatch(/light: --muted-foreground on --muted/);
  });

  it("rejects a brand: the defaults paint :root and .dark", () => {
    const doc = neutral();
    doc.$extensions = { "style.moderno.theme": { name: "neutral", brand: "acme" } };
    expect(() => compileTheme(doc, { neutral: true })).toThrow(/brand/);
  });
});
