import { existsSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { compileTheme } from "../src/index.ts";

/**
 * Guards the real registry themes: each must validate, and its committed
 * theme.css must be exactly what theme-compile regenerates (no drift). Mirrors
 * the banner the bin writes so the comparison is byte-for-byte.
 */
const themesRoot = fileURLToPath(new URL("../../../registry/themes", import.meta.url));
const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));

const themeNames = existsSync(themesRoot)
  ? readdirSync(themesRoot, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  : [];

describe("registry themes compile and stay in sync", () => {
  it("ships at least theme-moderno and theme-contrast", () => {
    expect(themeNames).toEqual(expect.arrayContaining(["theme-moderno", "theme-contrast"]));
  });

  it.each(themeNames)("%s: committed theme.css matches a fresh compile", (name) => {
    const dir = `${themesRoot}/${name}`;
    const input = `${dir}/tokens.dtcg.json`;
    const doc = JSON.parse(readFileSync(input, "utf8"));
    const { css } = compileTheme(doc);

    const rel = input.replace(repoRoot, "");
    const banner = `/* Generated by @moderno/theme-compile from ${rel}. Do not edit by hand. */\n`;
    const committed = readFileSync(`${dir}/theme.css`, "utf8");
    expect(committed).toBe(banner + css);
  });
});
