import { existsSync, readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import postcss, { type Declaration, type Rule } from "postcss";
import { CONTRAST_PAIRS, EXTENDED_SLOTS } from "@moderno-ui/tokens/contract";
import { contrastRatio } from "../src/color.ts";
import { defaultsFrom, readMeta, renderFrontMatter, withFrontMatter } from "../src/design-md.ts";
import { compileTheme } from "../src/index.ts";

/**
 * Guards the real registry themes: each must validate, and its committed
 * theme.css must be exactly what theme-compile regenerates (no drift). Mirrors
 * the banner the bin writes so the comparison is byte-for-byte.
 */
const themesRoot = fileURLToPath(new URL("../../../registry/themes", import.meta.url));
const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));

const themeNames = existsSync(themesRoot)
  ? readdirSync(themesRoot, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  : [];

/** Neutral defaults every theme inherits when it does not express a slot. */
const tokensCss = readFileSync(
  fileURLToPath(new URL("../../../packages/tokens/src/tokens.css", import.meta.url)),
  "utf8",
);

function declsFor(selector: string): Map<string, string> {
  const out = new Map<string, string>();
  postcss.parse(tokensCss).walkRules((rule: Rule) => {
    if (rule.selector !== selector) return;
    rule.walkDecls((decl: Declaration) => {
      if (decl.prop.startsWith("--")) out.set(decl.prop.slice(2), decl.value);
    });
  });
  return out;
}

const defaults = {
  light: declsFor(":root"),
  // `.dark` only overrides what changes there; the rest falls back to `:root`.
  dark: new Map([...declsFor(":root"), ...declsFor(".dark")]),
};

describe("DESIGN.md describes the default theme", () => {
  it("its front matter is exactly what theme-moderno's tokens.dtcg.json renders", () => {
    const doc = JSON.parse(readFileSync(`${themesRoot}/theme-moderno/tokens.dtcg.json`, "utf8"));
    const markdown = readFileSync(`${repoRoot}DESIGN.md`, "utf8");
    const fresh = renderFrontMatter(doc, defaultsFrom(tokensCss), readMeta(markdown));
    expect(withFrontMatter(markdown, fresh), "run `pnpm theme:build`").toBe(markdown);
  });
});

describe("registry themes compile and stay in sync", () => {
  it("ships at least theme-moderno and theme-contrast", () => {
    expect(themeNames).toEqual(expect.arrayContaining(["theme-moderno", "theme-contrast"]));
  });

  /**
   * A theme folder alone already shows up in the docs switcher and the Theme
   * Builder, so a missing registry.json entry would pass unnoticed while
   * `moderno add` cannot install the theme.
   */
  // theme-compile only warns, so without this a failing pair ships with a warning in the log.
  it.each(themeNames)("%s: clears WCAG AA on every contract pair", (name) => {
    const doc = JSON.parse(readFileSync(`${themesRoot}/${name}/tokens.dtcg.json`, "utf8"));
    expect(compileTheme(doc).warnings).toEqual([]);
  });

  it("the neutral defaults clear WCAG AA on every contract pair, in both scopes", () => {
    const failing: string[] = [];
    for (const scope of ["light", "dark"] as const) {
      for (const [fg, bg] of CONTRAST_PAIRS) {
        const ratio = contrastRatio(defaults[scope].get(fg)!, defaults[scope].get(bg)!);
        if (ratio < 4.5) failing.push(`${scope}: --${fg} on --${bg} is ${ratio.toFixed(2)}:1`);
      }
    }
    expect(failing).toEqual([]);
  });

  it.each(themeNames)("%s: is listed in registry.json with its theme.css", (name) => {
    const manifest = JSON.parse(readFileSync(`${repoRoot}registry/registry.json`, "utf8"));
    const item = manifest.items.find((i: { name: string }) => i.name === name);
    expect(item, `add a "${name}" item to registry/registry.json`).toBeDefined();
    expect(item.type).toBe("registry:theme");
    expect(item.files.map((f: { path: string }) => f.path)).toContain(`themes/${name}/theme.css`);
  });

  it.each(themeNames)("%s: committed theme.css matches a fresh compile", (name) => {
    const dir = `${themesRoot}/${name}`;
    const input = `${dir}/tokens.dtcg.json`;
    const doc = JSON.parse(readFileSync(input, "utf8"));
    const { css } = compileTheme(doc);

    const rel = input.replace(repoRoot, "");
    const banner = `/* Generated by @moderno-ui/theme-compile from ${rel}. Do not edit by hand. */\n`;
    const committed = readFileSync(`${dir}/theme.css`, "utf8");
    expect(committed).toBe(banner + css);
  });

  /**
   * Extended slots are optional — a theme overrides only what its brand
   * actually changes (CONTRACT.md). A theme that pins one to the value it would
   * have inherited opts silently out of the default: move `--container-md` in
   * tokens.css and every consumer who installed that theme keeps the old width,
   * with nothing to flag the disagreement. Redundant is therefore wrong, not
   * merely verbose.
   */
  it.each(themeNames)("%s: expresses no extended slot it would inherit anyway", (name) => {
    const doc = JSON.parse(readFileSync(`${themesRoot}/${name}/tokens.dtcg.json`, "utf8"));
    const redundant: string[] = [];
    for (const scope of ["light", "dark"] as const) {
      for (const slot of EXTENDED_SLOTS) {
        const value = doc[scope]?.[slot]?.$value;
        if (typeof value === "string" && value === defaults[scope].get(slot)) {
          redundant.push(`${scope}.--${slot}`);
        }
      }
    }
    expect(redundant, "drop these to inherit the neutral default").toEqual([]);
  });
});
