/**
 * Curated, framework-specific usage snippets for `moderno.agent.json`'s
 * `components[].examples` (schema: `docs/prd/phase-7/moderno.agent.schema.json`).
 *
 * Unlike `props`/`parts`/`variants` (identical across bindings by contract,
 * resolved once against the canonical React source in `agent-manifest.ts`),
 * example *syntax* is inherently framework-specific — a Vue template isn't a
 * JSX snippet with the tags renamed. So this is a hand-authored table, one
 * entry per (component, framework), verified against each binding's own test
 * fixtures so the snippets stay real, working usage rather than aspirational
 * markup. `@moderno/mcp`'s `get_examples` tool reads these straight off the
 * built manifest — no separate example store to keep in sync.
 */
import type { AgentExample, Framework } from "./agent-manifest.ts";

export const AGENT_EXAMPLES: Record<string, Partial<Record<Framework, AgentExample[]>>> = {
  Button: {
    react: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno/react";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Primary and outline",
        code: [
          '<script setup lang="ts">',
          'import { Button } from "@moderno/vue";',
          "</script>",
          "",
          "<template>",
          '  <Button variant="primary">Save</Button>',
          '  <Button variant="outline">Cancel</Button>',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Primary and outline",
        code: [
          '<script lang="ts">',
          '  import { Button } from "@moderno/svelte";',
          "</script>",
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno/solid";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
  },

  Field: {
    react: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno/react";',
          "",
          "<Field.Root invalid={hasError}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno/vue";',
          "defineProps<{ invalid?: boolean }>();",
          "</script>",
          "",
          "<template>",
          '  <Field.Root :invalid="invalid">',
          "    <Field.Label>Email</Field.Label>",
          '    <Field.Input placeholder="you@example.com" />',
          "    <Field.HelperText>We never share it.</Field.HelperText>",
          "    <Field.ErrorText>Email is required.</Field.ErrorText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno/svelte";',
          "  let { invalid = false }: { invalid?: boolean } = $props();",
          "</script>",
          "",
          "<Field.Root {invalid}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno/solid";',
          "",
          "function EmailField(props: { invalid?: boolean }) {",
          "  return (",
          "    <Field.Root invalid={props.invalid}>",
          "      <Field.Label>Email</Field.Label>",
          '      <Field.Input placeholder="you@example.com" />',
          "      <Field.HelperText>We never share it.</Field.HelperText>",
          "      <Field.ErrorText>Email is required.</Field.ErrorText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Dialog: {
    react: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno/react";',
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Confirmation dialog",
        code: [
          '<script setup lang="ts">',
          'import { Dialog, Portal } from "@moderno/vue";',
          "</script>",
          "",
          "<template>",
          "  <Dialog.Root>",
          "    <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "    <Portal>",
          "      <Dialog.Backdrop />",
          "      <Dialog.Positioner>",
          "        <Dialog.Content>",
          "          <Dialog.Title>Delete account</Dialog.Title>",
          "          <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "          <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "        </Dialog.Content>",
          "      </Dialog.Positioner>",
          "    </Portal>",
          "  </Dialog.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Confirmation dialog",
        code: [
          '<script lang="ts">',
          '  import { Dialog, Portal } from "@moderno/svelte";',
          "</script>",
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno/solid";',
          "",
          "function ConfirmDialog() {",
          "  return (",
          "    <Dialog.Root>",
          "      <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "      <Portal>",
          "        <Dialog.Backdrop />",
          "        <Dialog.Positioner>",
          "          <Dialog.Content>",
          "            <Dialog.Title>Delete account</Dialog.Title>",
          "            <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "            <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "          </Dialog.Content>",
          "        </Dialog.Positioner>",
          "      </Portal>",
          "    </Dialog.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Select: {
    react: [
      {
        title: "Framework picker",
        code: [
          'import { Select, Portal, createListCollection } from "@moderno/react";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          '<Select.Root collection={collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {collection.items.map((item) => (",
          "          <Select.Item key={item.value} item={item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        ))}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Framework picker",
        code: [
          '<script setup lang="ts">',
          'import { Select, Portal, createListCollection } from "@moderno/vue";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "</script>",
          "",
          "<template>",
          '  <Select.Root :collection="collection" size="sm">',
          "    <Select.Label>Framework</Select.Label>",
          "    <Select.Control>",
          "      <Select.Trigger>",
          '        <Select.ValueText placeholder="Pick one" />',
          "        <Select.Indicator>▼</Select.Indicator>",
          "      </Select.Trigger>",
          "    </Select.Control>",
          "    <Portal>",
          "      <Select.Positioner>",
          "        <Select.Content>",
          '          <Select.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Select.ItemText>{{ item.label }}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        </Select.Content>",
          "      </Select.Positioner>",
          "    </Portal>",
          "  </Select.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Framework picker",
        code: [
          '<script lang="ts">',
          '  import { Select, Portal, createListCollection } from "@moderno/svelte";',
          "",
          "  const collection = createListCollection({",
          "    items: [",
          '      { label: "React", value: "react" },',
          '      { label: "Vue", value: "vue" },',
          '      { label: "Svelte", value: "svelte" },',
          "    ],",
          "  });",
          "</script>",
          "",
          '<Select.Root {collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {#each collection.items as item (item.value)}",
          "          <Select.Item {item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        {/each}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Framework picker",
        code: [
          'import { For } from "solid-js";',
          'import { Select, Portal, createListCollection } from "@moderno/solid";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          "function FrameworkPicker() {",
          "  return (",
          '    <Select.Root collection={collection} size="sm">',
          "      <Select.Label>Framework</Select.Label>",
          "      <Select.Control>",
          "        <Select.Trigger>",
          '          <Select.ValueText placeholder="Pick one" />',
          "          <Select.Indicator>▼</Select.Indicator>",
          "        </Select.Trigger>",
          "      </Select.Control>",
          "      <Portal>",
          "        <Select.Positioner>",
          "          <Select.Content>",
          "            <For each={collection.items}>",
          "              {(item) => (",
          "                <Select.Item item={item}>",
          "                  <Select.ItemText>{item.label}</Select.ItemText>",
          "                  <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "                </Select.Item>",
          "              )}",
          "            </For>",
          "          </Select.Content>",
          "        </Select.Positioner>",
          "      </Portal>",
          "    </Select.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },
};
