/**
 * Curated, framework-specific usage snippets for `moderno.agent.json`'s
 * `components[].examples` (schema: `docs/prd/phase-7/moderno.agent.schema.json`).
 *
 * Unlike `props`/`parts`/`variants` (identical across bindings by contract,
 * resolved once against the canonical React source in `agent-manifest.ts`),
 * example *syntax* is inherently framework-specific — a Vue template isn't a
 * JSX snippet with the tags renamed. So this is a hand-authored table, one
 * entry per (component, framework), verified against each binding's own test
 * fixtures so the snippets stay real, working usage rather than aspirational
 * markup. `@moderno-ui/mcp`'s `get_examples` tool reads these straight off the
 * built manifest — no separate example store to keep in sync.
 */
import type { AgentExample, Framework } from "./agent-manifest.ts";

export const AGENT_EXAMPLES: Record<string, Partial<Record<Framework, AgentExample[]>>> = {
  Button: {
    react: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno-ui/react";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Primary and outline",
        code: [
          '<script setup lang="ts">',
          'import { Button } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Button variant="primary">Save</Button>',
          '  <Button variant="outline">Cancel</Button>',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Primary and outline",
        code: [
          '<script lang="ts">',
          '  import { Button } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno-ui/solid";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
  },

  Alert: {
    react: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/react";',
          'import { TriangleAlert } from "lucide-react";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Warning with an action",
        code: [
          '<script setup lang="ts">',
          'import { Alert, Button } from "@moderno-ui/vue";',
          'import { TriangleAlert } from "lucide-vue-next";',
          "</script>",
          "",
          "<template>",
          '  <Alert.Root variant="warning">',
          "    <Alert.Icon>",
          "      <TriangleAlert aria-hidden />",
          "    </Alert.Icon>",
          "    <Alert.Content>",
          "      <Alert.Title>Card expiring</Alert.Title>",
          "      <Alert.Description>Your card expires next month.</Alert.Description>",
          "      <Alert.Action>",
          '        <Button size="sm" variant="outline">Update card</Button>',
          "      </Alert.Action>",
          "    </Alert.Content>",
          "  </Alert.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Warning with an action",
        code: [
          '<script lang="ts">',
          '  import { Alert, Button } from "@moderno-ui/svelte";',
          '  import { TriangleAlert } from "@lucide/svelte";',
          "</script>",
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">Update card</Button>',
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/solid";',
          'import { TriangleAlert } from "lucide-solid";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
  },

  Field: {
    react: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          "<Field.Root invalid={hasError}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "defineProps<{ invalid?: boolean }>();",
          "</script>",
          "",
          "<template>",
          '  <Field.Root :invalid="invalid">',
          "    <Field.Label>Email</Field.Label>",
          '    <Field.Input placeholder="you@example.com" />',
          "    <Field.HelperText>We never share it.</Field.HelperText>",
          "    <Field.ErrorText>Email is required.</Field.ErrorText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Field.Root size="lg">',
          "    <Field.Label>Bio</Field.Label>",
          '    <Field.Textarea placeholder="Tell us about yourself" />',
          "    <Field.HelperText>A short introduction.</Field.HelperText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "  let { invalid = false }: { invalid?: boolean } = $props();",
          "</script>",
          "",
          "<Field.Root {invalid}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function EmailField(props: { invalid?: boolean }) {",
          "  return (",
          "    <Field.Root invalid={props.invalid}>",
          "      <Field.Label>Email</Field.Label>",
          '      <Field.Input placeholder="you@example.com" />',
          "      <Field.HelperText>We never share it.</Field.HelperText>",
          "      <Field.ErrorText>Email is required.</Field.ErrorText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function BioField() {",
          "  return (",
          '    <Field.Root size="lg">',
          "      <Field.Label>Bio</Field.Label>",
          '      <Field.Textarea placeholder="Tell us about yourself" />',
          "      <Field.HelperText>A short introduction.</Field.HelperText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Checkbox: {
    react: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          'import { Checkbox } from "@moderno-ui/react";',
          "",
          '<Checkbox.Root size="md" defaultChecked="indeterminate">',
          "  <Checkbox.Control>",
          "    <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "    <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "  </Checkbox.Control>",
          "  <Checkbox.Label>Email me updates</Checkbox.Label>",
          "  <Checkbox.HiddenInput />",
          "</Checkbox.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          '<script setup lang="ts">',
          'import { Checkbox } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Checkbox.Root size="md" default-checked="indeterminate">',
          "    <Checkbox.Control>",
          "      <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "      <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "    </Checkbox.Control>",
          "    <Checkbox.Label>Email me updates</Checkbox.Label>",
          "    <Checkbox.HiddenInput />",
          "  </Checkbox.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          '<script lang="ts">',
          '  import { Checkbox } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Checkbox.Root size="md" defaultChecked="indeterminate">',
          "  <Checkbox.Control>",
          "    <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "    <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "  </Checkbox.Control>",
          "  <Checkbox.Label>Email me updates</Checkbox.Label>",
          "  <Checkbox.HiddenInput />",
          "</Checkbox.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          'import { Checkbox } from "@moderno-ui/solid";',
          "",
          "function SubscribeCheckbox() {",
          "  return (",
          '    <Checkbox.Root size="md" defaultChecked="indeterminate">',
          "      <Checkbox.Control>",
          "        <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "        <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "      </Checkbox.Control>",
          "      <Checkbox.Label>Email me updates</Checkbox.Label>",
          "      <Checkbox.HiddenInput />",
          "    </Checkbox.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Dialog: {
    react: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/react";',
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Confirmation dialog",
        code: [
          '<script setup lang="ts">',
          'import { Dialog, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Dialog.Root>",
          "    <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "    <Portal>",
          "      <Dialog.Backdrop />",
          "      <Dialog.Positioner>",
          "        <Dialog.Content>",
          "          <Dialog.Title>Delete account</Dialog.Title>",
          "          <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "          <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "        </Dialog.Content>",
          "      </Dialog.Positioner>",
          "    </Portal>",
          "  </Dialog.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Confirmation dialog",
        code: [
          '<script lang="ts">',
          '  import { Dialog, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/solid";',
          "",
          "function ConfirmDialog() {",
          "  return (",
          "    <Dialog.Root>",
          "      <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "      <Portal>",
          "        <Dialog.Backdrop />",
          "        <Dialog.Positioner>",
          "          <Dialog.Content>",
          "            <Dialog.Title>Delete account</Dialog.Title>",
          "            <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "            <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "          </Dialog.Content>",
          "        </Dialog.Positioner>",
          "      </Portal>",
          "    </Dialog.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Select: {
    react: [
      {
        title: "Framework picker",
        code: [
          'import { Select, Portal, createListCollection } from "@moderno-ui/react";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          '<Select.Root collection={collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {collection.items.map((item) => (",
          "          <Select.Item key={item.value} item={item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        ))}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Framework picker",
        code: [
          '<script setup lang="ts">',
          'import { Select, Portal, createListCollection } from "@moderno-ui/vue";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "</script>",
          "",
          "<template>",
          '  <Select.Root :collection="collection" size="sm">',
          "    <Select.Label>Framework</Select.Label>",
          "    <Select.Control>",
          "      <Select.Trigger>",
          '        <Select.ValueText placeholder="Pick one" />',
          "        <Select.Indicator>▼</Select.Indicator>",
          "      </Select.Trigger>",
          "    </Select.Control>",
          "    <Portal>",
          "      <Select.Positioner>",
          "        <Select.Content>",
          '          <Select.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Select.ItemText>{{ item.label }}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        </Select.Content>",
          "      </Select.Positioner>",
          "    </Portal>",
          "  </Select.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Framework picker",
        code: [
          '<script lang="ts">',
          '  import { Select, Portal, createListCollection } from "@moderno-ui/svelte";',
          "",
          "  const collection = createListCollection({",
          "    items: [",
          '      { label: "React", value: "react" },',
          '      { label: "Vue", value: "vue" },',
          '      { label: "Svelte", value: "svelte" },',
          "    ],",
          "  });",
          "</script>",
          "",
          '<Select.Root {collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {#each collection.items as item (item.value)}",
          "          <Select.Item {item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        {/each}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Framework picker",
        code: [
          'import { For } from "solid-js";',
          'import { Select, Portal, createListCollection } from "@moderno-ui/solid";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          "function FrameworkPicker() {",
          "  return (",
          '    <Select.Root collection={collection} size="sm">',
          "      <Select.Label>Framework</Select.Label>",
          "      <Select.Control>",
          "        <Select.Trigger>",
          '          <Select.ValueText placeholder="Pick one" />',
          "          <Select.Indicator>▼</Select.Indicator>",
          "        </Select.Trigger>",
          "      </Select.Control>",
          "      <Portal>",
          "        <Select.Positioner>",
          "          <Select.Content>",
          "            <For each={collection.items}>",
          "              {(item) => (",
          "                <Select.Item item={item}>",
          "                  <Select.ItemText>{item.label}</Select.ItemText>",
          "                  <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "                </Select.Item>",
          "              )}",
          "            </For>",
          "          </Select.Content>",
          "        </Select.Positioner>",
          "      </Portal>",
          "    </Select.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  LineChart: {
    react: [
      {
        title: "Two-series line chart",
        code: [
          'import { LineChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "<LineChart width={520} height={260} series={series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Two-series line chart",
        code: [
          '<script setup lang="ts">',
          'import { LineChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <LineChart :width="520" :height="260" :series="series" :x-ticks="3" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Two-series line chart",
        code: [
          '<script lang="ts">',
          '  import { LineChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "  ];",
          "</script>",
          "",
          "<LineChart width={520} height={260} {series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Two-series line chart",
        code: [
          'import { LineChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "function SessionsChart() {",
          "  return <LineChart width={520} height={260} series={series} xTicks={3} yTicks={5} />;",
          "}",
        ].join("\n"),
      },
    ],
  },

  AreaChart: {
    react: [
      {
        title: "Single-series area chart",
        code: [
          'import { AreaChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "",
          "<AreaChart width={520} height={260} series={series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Single-series area chart",
        code: [
          '<script setup lang="ts">',
          'import { AreaChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <AreaChart :width="520" :height="260" :series="series" :x-ticks="3" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Single-series area chart",
        code: [
          '<script lang="ts">',
          '  import { AreaChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "  ];",
          "</script>",
          "",
          "<AreaChart width={520} height={260} {series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Single-series area chart",
        code: [
          'import { AreaChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "",
          "function RevenueChart() {",
          "  return <AreaChart width={520} height={260} series={series} xTicks={3} yTicks={5} />;",
          "}",
        ].join("\n"),
      },
    ],
  },

  BarChart: {
    react: [
      {
        title: "Categorical bar chart",
        code: [
          'import { BarChart } from "@moderno-ui/react";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "",
          "<BarChart width={520} height={260} categories={categories} series={series} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Categorical bar chart",
        code: [
          '<script setup lang="ts">',
          'import { BarChart } from "@moderno-ui/vue";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "</script>",
          "",
          "<template>",
          '  <BarChart :width="520" :height="260" :categories="categories" :series="series" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Categorical bar chart",
        code: [
          '<script lang="ts">',
          '  import { BarChart } from "@moderno-ui/svelte";',
          "",
          '  const categories = ["Q1", "Q2", "Q3"];',
          '  const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "</script>",
          "",
          "<BarChart width={520} height={260} {categories} {series} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Categorical bar chart",
        code: [
          'import { BarChart } from "@moderno-ui/solid";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "",
          "function RevenueByQuarter() {",
          "  return (",
          "    <BarChart width={520} height={260} categories={categories} series={series} yTicks={5} />",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  ScatterChart: {
    react: [
      {
        title: "Scatter plot",
        code: [
          'import { ScatterChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "<ScatterChart width={520} height={260} series={series} radius={4} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Scatter plot",
        code: [
          '<script setup lang="ts">',
          'import { ScatterChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <ScatterChart :width="520" :height="260" :series="series" :radius="4" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Scatter plot",
        code: [
          '<script lang="ts">',
          '  import { ScatterChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "  ];",
          "</script>",
          "",
          "<ScatterChart width={520} height={260} {series} radius={4} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Scatter plot",
        code: [
          'import { ScatterChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "function SamplesChart() {",
          "  return <ScatterChart width={520} height={260} series={series} radius={4} />;",
          "}",
        ].join("\n"),
      },
    ],
  },
};
