/**
 * Curated, framework-specific usage snippets for `moderno.agent.json`'s
 * `components[].examples` (schema: `docs/prd/phase-7/moderno.agent.schema.json`).
 *
 * Unlike `props`/`parts`/`variants` (identical across bindings by contract,
 * resolved once against the canonical React source in `agent-manifest.ts`),
 * example *syntax* is inherently framework-specific — a Vue template isn't a
 * JSX snippet with the tags renamed. So this is a hand-authored table, one
 * entry per (component, framework), verified against each binding's own test
 * fixtures so the snippets stay real, working usage rather than aspirational
 * markup. `@moderno-ui/mcp`'s `get_examples` tool reads these straight off the
 * built manifest — no separate example store to keep in sync.
 */
import type { AgentExample, Framework } from "./agent-manifest.ts";

export const AGENT_EXAMPLES: Record<string, Partial<Record<Framework, AgentExample[]>>> = {
  Button: {
    react: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno-ui/react";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Primary and outline",
        code: [
          '<script setup lang="ts">',
          'import { Button } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Button variant="primary">Save</Button>',
          '  <Button variant="outline">Cancel</Button>',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Primary and outline",
        code: [
          '<script lang="ts">',
          '  import { Button } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Primary and outline",
        code: [
          'import { Button } from "@moderno-ui/solid";',
          "",
          '<Button variant="primary">Save</Button>',
          '<Button variant="outline">Cancel</Button>',
        ].join("\n"),
      },
    ],
  },

  Alert: {
    react: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/react";',
          'import { TriangleAlert } from "lucide-react";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Warning with an action",
        code: [
          '<script setup lang="ts">',
          'import { Alert, Button } from "@moderno-ui/vue";',
          'import { TriangleAlert } from "lucide-vue-next";',
          "</script>",
          "",
          "<template>",
          '  <Alert.Root variant="warning">',
          "    <Alert.Icon>",
          "      <TriangleAlert aria-hidden />",
          "    </Alert.Icon>",
          "    <Alert.Content>",
          "      <Alert.Title>Card expiring</Alert.Title>",
          "      <Alert.Description>Your card expires next month.</Alert.Description>",
          "      <Alert.Action>",
          '        <Button size="sm" variant="outline">Update card</Button>',
          "      </Alert.Action>",
          "    </Alert.Content>",
          "  </Alert.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Warning with an action",
        code: [
          '<script lang="ts">',
          '  import { Alert, Button } from "@moderno-ui/svelte";',
          '  import { TriangleAlert } from "@lucide/svelte";',
          "</script>",
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">Update card</Button>',
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Warning with an action",
        code: [
          'import { Alert, Button } from "@moderno-ui/solid";',
          'import { TriangleAlert } from "lucide-solid";',
          "",
          '<Alert.Root variant="warning">',
          "  <Alert.Icon>",
          "    <TriangleAlert aria-hidden />",
          "  </Alert.Icon>",
          "  <Alert.Content>",
          "    <Alert.Title>Card expiring</Alert.Title>",
          "    <Alert.Description>Your card expires next month.</Alert.Description>",
          "    <Alert.Action>",
          '      <Button size="sm" variant="outline">',
          "        Update card",
          "      </Button>",
          "    </Alert.Action>",
          "  </Alert.Content>",
          "</Alert.Root>",
        ].join("\n"),
      },
    ],
  },

  Card: {
    react: [
      {
        title: "Report card with a footer action",
        code: [
          'import { Button, Card } from "@moderno-ui/react";',
          "",
          '<Card.Root variant="outline" size="md">',
          "  <Card.Header>",
          "    <Card.Title>Monthly report</Card.Title>",
          "    <Card.Description>Revenue across every channel.</Card.Description>",
          "  </Card.Header>",
          "  <Card.Content>Up 12% on last month.</Card.Content>",
          "  <Card.Footer>",
          '    <Button variant="outline" size="sm">Export</Button>',
          "  </Card.Footer>",
          "</Card.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Report card with a footer action",
        code: [
          '<script setup lang="ts">',
          'import { Button, Card } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Card.Root variant="outline" size="md">',
          "    <Card.Header>",
          "      <Card.Title>Monthly report</Card.Title>",
          "      <Card.Description>Revenue across every channel.</Card.Description>",
          "    </Card.Header>",
          "    <Card.Content>Up 12% on last month.</Card.Content>",
          "    <Card.Footer>",
          '      <Button variant="outline" size="sm">Export</Button>',
          "    </Card.Footer>",
          "  </Card.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Report card with a footer action",
        code: [
          '<script lang="ts">',
          '  import { Button, Card } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Card.Root variant="outline" size="md">',
          "  <Card.Header>",
          "    <Card.Title>Monthly report</Card.Title>",
          "    <Card.Description>Revenue across every channel.</Card.Description>",
          "  </Card.Header>",
          "  <Card.Content>Up 12% on last month.</Card.Content>",
          "  <Card.Footer>",
          '    <Button variant="outline" size="sm">Export</Button>',
          "  </Card.Footer>",
          "</Card.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Report card with a footer action",
        code: [
          'import { Button, Card } from "@moderno-ui/solid";',
          "",
          '<Card.Root variant="outline" size="md">',
          "  <Card.Header>",
          "    <Card.Title>Monthly report</Card.Title>",
          "    <Card.Description>Revenue across every channel.</Card.Description>",
          "  </Card.Header>",
          "  <Card.Content>Up 12% on last month.</Card.Content>",
          "  <Card.Footer>",
          '    <Button variant="outline" size="sm">Export</Button>',
          "  </Card.Footer>",
          "</Card.Root>",
        ].join("\n"),
      },
    ],
  },

  Divider: {
    react: [
      {
        title: "Plain rule and a captioned one",
        code: [
          'import { Divider } from "@moderno-ui/react";',
          "",
          "<Divider />",
          "<Divider>Or continue with</Divider>",
          '<Divider orientation="vertical" />',
          '<Divider orientation="vertical">or</Divider>',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Plain rule and a captioned one",
        code: [
          '<script setup lang="ts">',
          'import { Divider } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Divider />",
          "  <Divider>Or continue with</Divider>",
          '  <Divider orientation="vertical" />',
          '  <Divider orientation="vertical">or</Divider>',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Plain rule and a captioned one",
        code: [
          '<script lang="ts">',
          '  import { Divider } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Divider />",
          "<Divider>Or continue with</Divider>",
          '<Divider orientation="vertical" />',
          '<Divider orientation="vertical">or</Divider>',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Plain rule and a captioned one",
        code: [
          'import { Divider } from "@moderno-ui/solid";',
          "",
          "<Divider />",
          "<Divider>Or continue with</Divider>",
          '<Divider orientation="vertical" />',
          '<Divider orientation="vertical">or</Divider>',
        ].join("\n"),
      },
    ],
  },

  Badge: {
    react: [
      {
        title: "Status badges, one with a dot",
        code: [
          'import { Badge } from "@moderno-ui/react";',
          "",
          "<Badge>Draft</Badge>",
          '<Badge variant="success" dot>Paid</Badge>',
          '<Badge variant="error" size="sm">Overdue</Badge>',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Status badges, one with a dot",
        code: [
          '<script setup lang="ts">',
          'import { Badge } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Badge>Draft</Badge>",
          '  <Badge variant="success" dot>Paid</Badge>',
          '  <Badge variant="error" size="sm">Overdue</Badge>',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Status badges, one with a dot",
        code: [
          '<script lang="ts">',
          '  import { Badge } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Badge>Draft</Badge>",
          '<Badge variant="success" dot>Paid</Badge>',
          '<Badge variant="error" size="sm">Overdue</Badge>',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Status badges, one with a dot",
        code: [
          'import { Badge } from "@moderno-ui/solid";',
          "",
          "<Badge>Draft</Badge>",
          '<Badge variant="success" dot>Paid</Badge>',
          '<Badge variant="error" size="sm">Overdue</Badge>',
        ].join("\n"),
      },
    ],
  },

  Chip: {
    react: [
      {
        title: "A removable chip that leaves the list",
        code: [
          'import { Chip } from "@moderno-ui/react";',
          "",
          "{tags.map((tag) => (",
          "  <Chip key={tag} removable removeLabel={`Remove ${tag}`} onRemove={() => remove(tag)}>",
          "    {tag}",
          "  </Chip>",
          "))}",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A removable chip that leaves the list",
        code: [
          '<script setup lang="ts">',
          'import { Chip } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Chip",
          '    v-for="tag in tags"',
          '    :key="tag"',
          "    removable",
          '    :remove-label="`Remove ${tag}`"',
          '    @remove="remove(tag)"',
          "  >",
          "    {{ tag }}",
          "  </Chip>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A removable chip that leaves the list",
        code: [
          '<script lang="ts">',
          '  import { Chip } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "{#each tags as tag (tag)}",
          "  <Chip removable removeLabel={`Remove ${tag}`} onRemove={() => remove(tag)}>{tag}</Chip>",
          "{/each}",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A removable chip that leaves the list",
        code: [
          'import { For } from "solid-js";',
          'import { Chip } from "@moderno-ui/solid";',
          "",
          "<For each={tags()}>",
          "  {(tag) => (",
          "    <Chip removable removeLabel={`Remove ${tag}`} onRemove={() => remove(tag)}>",
          "      {tag}",
          "    </Chip>",
          "  )}",
          "</For>",
        ].join("\n"),
      },
    ],
  },

  Indicator: {
    react: [
      {
        title: "A live status with a label, and a bare dot",
        code: [
          'import { Indicator } from "@moderno-ui/react";',
          "",
          '<Indicator variant="success" pulse>Online</Indicator>',
          '<Indicator variant="error" aria-label="Offline" />',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A live status with a label, and a bare dot",
        code: [
          '<script setup lang="ts">',
          'import { Indicator } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Indicator variant="success" pulse>Online</Indicator>',
          '  <Indicator variant="error" aria-label="Offline" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A live status with a label, and a bare dot",
        code: [
          '<script lang="ts">',
          '  import { Indicator } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Indicator variant="success" pulse>Online</Indicator>',
          '<Indicator variant="error" aria-label="Offline" />',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A live status with a label, and a bare dot",
        code: [
          'import { Indicator } from "@moderno-ui/solid";',
          "",
          '<Indicator variant="success" pulse>Online</Indicator>',
          '<Indicator variant="error" aria-label="Offline" />',
        ].join("\n"),
      },
    ],
  },

  Skeleton: {
    react: [
      {
        title: "A profile row while it loads",
        code: [
          'import { Skeleton } from "@moderno-ui/react";',
          "",
          '<div aria-busy="true">',
          '  <Skeleton shape="circle" />',
          "  <Skeleton />",
          '  <Skeleton style={{ width: "60%" }} />',
          "</div>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A profile row while it loads",
        code: [
          '<script setup lang="ts">',
          'import { Skeleton } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <div aria-busy="true">',
          '    <Skeleton shape="circle" />',
          "    <Skeleton />",
          '    <Skeleton style="width: 60%" />',
          "  </div>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A profile row while it loads",
        code: [
          '<script lang="ts">',
          '  import { Skeleton } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<div aria-busy="true">',
          '  <Skeleton shape="circle" />',
          "  <Skeleton />",
          '  <Skeleton style="width: 60%" />',
          "</div>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A profile row while it loads",
        code: [
          'import { Skeleton } from "@moderno-ui/solid";',
          "",
          '<div aria-busy="true">',
          '  <Skeleton shape="circle" />',
          "  <Skeleton />",
          '  <Skeleton style={{ width: "60%" }} />',
          "</div>",
        ].join("\n"),
      },
    ],
  },

  Spinner: {
    react: [
      {
        title: "A spinner that says what is loading",
        code: [
          'import { Spinner } from "@moderno-ui/react";',
          "",
          "<Spinner />",
          '<Spinner size="lg" label="Loading invoices" />',
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A spinner that says what is loading",
        code: [
          '<script setup lang="ts">',
          'import { Spinner } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Spinner />",
          '  <Spinner size="lg" label="Loading invoices" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A spinner that says what is loading",
        code: [
          '<script lang="ts">',
          '  import { Spinner } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Spinner />",
          '<Spinner size="lg" label="Loading invoices" />',
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A spinner that says what is loading",
        code: [
          'import { Spinner } from "@moderno-ui/solid";',
          "",
          "<Spinner />",
          '<Spinner size="lg" label="Loading invoices" />',
        ].join("\n"),
      },
    ],
  },

  Callout: {
    react: [
      {
        title: "A warning note in the content",
        code: [
          'import { Callout } from "@moderno-ui/react";',
          "",
          '<Callout.Root variant="warning">',
          "  <Callout.Content>",
          "    <Callout.Title>Renaming breaks old links</Callout.Title>",
          "    <Callout.Description>Share the new address with your team.</Callout.Description>",
          "  </Callout.Content>",
          "</Callout.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A warning note in the content",
        code: [
          '<script setup lang="ts">',
          'import { Callout } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Callout.Root variant="warning">',
          "    <Callout.Content>",
          "      <Callout.Title>Renaming breaks old links</Callout.Title>",
          "      <Callout.Description>Share the new address with your team.</Callout.Description>",
          "    </Callout.Content>",
          "  </Callout.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A warning note in the content",
        code: [
          '<script lang="ts">',
          '  import { Callout } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Callout.Root variant="warning">',
          "  <Callout.Content>",
          "    <Callout.Title>Renaming breaks old links</Callout.Title>",
          "    <Callout.Description>Share the new address with your team.</Callout.Description>",
          "  </Callout.Content>",
          "</Callout.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A warning note in the content",
        code: [
          'import { Callout } from "@moderno-ui/solid";',
          "",
          '<Callout.Root variant="warning">',
          "  <Callout.Content>",
          "    <Callout.Title>Renaming breaks old links</Callout.Title>",
          "    <Callout.Description>Share the new address with your team.</Callout.Description>",
          "  </Callout.Content>",
          "</Callout.Root>",
        ].join("\n"),
      },
    ],
  },

  Field: {
    react: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          "<Field.Root invalid={hasError}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/react";',
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "defineProps<{ invalid?: boolean }>();",
          "</script>",
          "",
          "<template>",
          '  <Field.Root :invalid="invalid">',
          "    <Field.Label>Email</Field.Label>",
          '    <Field.Input placeholder="you@example.com" />',
          "    <Field.HelperText>We never share it.</Field.HelperText>",
          "    <Field.ErrorText>Email is required.</Field.ErrorText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script setup lang="ts">',
          'import { Field } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Field.Root size="lg">',
          "    <Field.Label>Bio</Field.Label>",
          '    <Field.Textarea placeholder="Tell us about yourself" />',
          "    <Field.HelperText>A short introduction.</Field.HelperText>",
          "  </Field.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Email field with helper and error text",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "  let { invalid = false }: { invalid?: boolean } = $props();",
          "</script>",
          "",
          "<Field.Root {invalid}>",
          "  <Field.Label>Email</Field.Label>",
          '  <Field.Input placeholder="you@example.com" />',
          "  <Field.HelperText>We never share it.</Field.HelperText>",
          "  <Field.ErrorText>Email is required.</Field.ErrorText>",
          "</Field.Root>",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          '<script lang="ts">',
          '  import { Field } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Field.Root size="lg">',
          "  <Field.Label>Bio</Field.Label>",
          '  <Field.Textarea placeholder="Tell us about yourself" />',
          "  <Field.HelperText>A short introduction.</Field.HelperText>",
          "</Field.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Email field with helper and error text",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function EmailField(props: { invalid?: boolean }) {",
          "  return (",
          "    <Field.Root invalid={props.invalid}>",
          "      <Field.Label>Email</Field.Label>",
          '      <Field.Input placeholder="you@example.com" />',
          "      <Field.HelperText>We never share it.</Field.HelperText>",
          "      <Field.ErrorText>Email is required.</Field.ErrorText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
      {
        title: "Large field with a textarea",
        code: [
          'import { Field } from "@moderno-ui/solid";',
          "",
          "function BioField() {",
          "  return (",
          '    <Field.Root size="lg">',
          "      <Field.Label>Bio</Field.Label>",
          '      <Field.Textarea placeholder="Tell us about yourself" />',
          "      <Field.HelperText>A short introduction.</Field.HelperText>",
          "    </Field.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Checkbox: {
    react: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          'import { Checkbox } from "@moderno-ui/react";',
          "",
          '<Checkbox.Root size="md" defaultChecked="indeterminate">',
          "  <Checkbox.Control>",
          "    <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "    <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "  </Checkbox.Control>",
          "  <Checkbox.Label>Email me updates</Checkbox.Label>",
          "  <Checkbox.HiddenInput />",
          "</Checkbox.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          '<script setup lang="ts">',
          'import { Checkbox } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Checkbox.Root size="md" default-checked="indeterminate">',
          "    <Checkbox.Control>",
          "      <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "      <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "    </Checkbox.Control>",
          "    <Checkbox.Label>Email me updates</Checkbox.Label>",
          "    <Checkbox.HiddenInput />",
          "  </Checkbox.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          '<script lang="ts">',
          '  import { Checkbox } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Checkbox.Root size="md" defaultChecked="indeterminate">',
          "  <Checkbox.Control>",
          "    <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "    <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "  </Checkbox.Control>",
          "  <Checkbox.Label>Email me updates</Checkbox.Label>",
          "  <Checkbox.HiddenInput />",
          "</Checkbox.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Labelled checkbox with an indeterminate state",
        code: [
          'import { Checkbox } from "@moderno-ui/solid";',
          "",
          "function SubscribeCheckbox() {",
          "  return (",
          '    <Checkbox.Root size="md" defaultChecked="indeterminate">',
          "      <Checkbox.Control>",
          "        <Checkbox.Indicator>✓</Checkbox.Indicator>",
          "        <Checkbox.Indicator indeterminate>–</Checkbox.Indicator>",
          "      </Checkbox.Control>",
          "      <Checkbox.Label>Email me updates</Checkbox.Label>",
          "      <Checkbox.HiddenInput />",
          "    </Checkbox.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Dialog: {
    react: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/react";',
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Confirmation dialog",
        code: [
          '<script setup lang="ts">',
          'import { Dialog, Portal } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          "  <Dialog.Root>",
          "    <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "    <Portal>",
          "      <Dialog.Backdrop />",
          "      <Dialog.Positioner>",
          "        <Dialog.Content>",
          "          <Dialog.Title>Delete account</Dialog.Title>",
          "          <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "          <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "        </Dialog.Content>",
          "      </Dialog.Positioner>",
          "    </Portal>",
          "  </Dialog.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Confirmation dialog",
        code: [
          '<script lang="ts">',
          '  import { Dialog, Portal } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Dialog.Root>",
          "  <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "  <Portal>",
          "    <Dialog.Backdrop />",
          "    <Dialog.Positioner>",
          "      <Dialog.Content>",
          "        <Dialog.Title>Delete account</Dialog.Title>",
          "        <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "        <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "      </Dialog.Content>",
          "    </Dialog.Positioner>",
          "  </Portal>",
          "</Dialog.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Confirmation dialog",
        code: [
          'import { Dialog, Portal } from "@moderno-ui/solid";',
          "",
          "function ConfirmDialog() {",
          "  return (",
          "    <Dialog.Root>",
          "      <Dialog.Trigger>Open dialog</Dialog.Trigger>",
          "      <Portal>",
          "        <Dialog.Backdrop />",
          "        <Dialog.Positioner>",
          "          <Dialog.Content>",
          "            <Dialog.Title>Delete account</Dialog.Title>",
          "            <Dialog.Description>This action cannot be undone.</Dialog.Description>",
          "            <Dialog.CloseTrigger>Cancel</Dialog.CloseTrigger>",
          "          </Dialog.Content>",
          "        </Dialog.Positioner>",
          "      </Portal>",
          "    </Dialog.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  Select: {
    react: [
      {
        title: "Framework picker",
        code: [
          'import { Select, Portal, createListCollection } from "@moderno-ui/react";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          '<Select.Root collection={collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {collection.items.map((item) => (",
          "          <Select.Item key={item.value} item={item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        ))}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Framework picker",
        code: [
          '<script setup lang="ts">',
          'import { Select, Portal, createListCollection } from "@moderno-ui/vue";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "</script>",
          "",
          "<template>",
          '  <Select.Root :collection="collection" size="sm">',
          "    <Select.Label>Framework</Select.Label>",
          "    <Select.Control>",
          "      <Select.Trigger>",
          '        <Select.ValueText placeholder="Pick one" />',
          "        <Select.Indicator>▼</Select.Indicator>",
          "      </Select.Trigger>",
          "    </Select.Control>",
          "    <Portal>",
          "      <Select.Positioner>",
          "        <Select.Content>",
          '          <Select.Item v-for="item in collection.items" :key="item.value" :item="item">',
          "            <Select.ItemText>{{ item.label }}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        </Select.Content>",
          "      </Select.Positioner>",
          "    </Portal>",
          "  </Select.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Framework picker",
        code: [
          '<script lang="ts">',
          '  import { Select, Portal, createListCollection } from "@moderno-ui/svelte";',
          "",
          "  const collection = createListCollection({",
          "    items: [",
          '      { label: "React", value: "react" },',
          '      { label: "Vue", value: "vue" },',
          '      { label: "Svelte", value: "svelte" },',
          "    ],",
          "  });",
          "</script>",
          "",
          '<Select.Root {collection} size="sm">',
          "  <Select.Label>Framework</Select.Label>",
          "  <Select.Control>",
          "    <Select.Trigger>",
          '      <Select.ValueText placeholder="Pick one" />',
          "      <Select.Indicator>▼</Select.Indicator>",
          "    </Select.Trigger>",
          "  </Select.Control>",
          "  <Portal>",
          "    <Select.Positioner>",
          "      <Select.Content>",
          "        {#each collection.items as item (item.value)}",
          "          <Select.Item {item}>",
          "            <Select.ItemText>{item.label}</Select.ItemText>",
          "            <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "          </Select.Item>",
          "        {/each}",
          "      </Select.Content>",
          "    </Select.Positioner>",
          "  </Portal>",
          "</Select.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Framework picker",
        code: [
          'import { For } from "solid-js";',
          'import { Select, Portal, createListCollection } from "@moderno-ui/solid";',
          "",
          "const collection = createListCollection({",
          "  items: [",
          '    { label: "React", value: "react" },',
          '    { label: "Vue", value: "vue" },',
          '    { label: "Svelte", value: "svelte" },',
          "  ],",
          "});",
          "",
          "function FrameworkPicker() {",
          "  return (",
          '    <Select.Root collection={collection} size="sm">',
          "      <Select.Label>Framework</Select.Label>",
          "      <Select.Control>",
          "        <Select.Trigger>",
          '          <Select.ValueText placeholder="Pick one" />',
          "          <Select.Indicator>▼</Select.Indicator>",
          "        </Select.Trigger>",
          "      </Select.Control>",
          "      <Portal>",
          "        <Select.Positioner>",
          "          <Select.Content>",
          "            <For each={collection.items}>",
          "              {(item) => (",
          "                <Select.Item item={item}>",
          "                  <Select.ItemText>{item.label}</Select.ItemText>",
          "                  <Select.ItemIndicator>✓</Select.ItemIndicator>",
          "                </Select.Item>",
          "              )}",
          "            </For>",
          "          </Select.Content>",
          "        </Select.Positioner>",
          "      </Portal>",
          "    </Select.Root>",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  PinInput: {
    react: [
      {
        title: "Six-digit verification code",
        code: [
          'import { PinInput } from "@moderno-ui/react";',
          "",
          "const cells = [0, 1, 2, 3, 4, 5];",
          "",
          "<PinInput.Root count={cells.length} otp onValueComplete={submit}>",
          "  <PinInput.Label>Verification code</PinInput.Label>",
          "  <PinInput.Control>",
          "    {cells.map((index) => (",
          "      <PinInput.Input key={index} index={index} />",
          "    ))}",
          "  </PinInput.Control>",
          "  <PinInput.HiddenInput />",
          "</PinInput.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Six-digit verification code",
        code: [
          '<script setup lang="ts">',
          'import { PinInput } from "@moderno-ui/vue";',
          "",
          "const cells = [0, 1, 2, 3, 4, 5];",
          "</script>",
          "",
          "<template>",
          '  <PinInput.Root :count="cells.length" otp @value-complete="submit">',
          "    <PinInput.Label>Verification code</PinInput.Label>",
          "    <PinInput.Control>",
          '      <PinInput.Input v-for="index in cells" :key="index" :index="index" />',
          "    </PinInput.Control>",
          "    <PinInput.HiddenInput />",
          "  </PinInput.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Six-digit verification code",
        code: [
          '<script lang="ts">',
          '  import { PinInput } from "@moderno-ui/svelte";',
          "",
          "  const cells = [0, 1, 2, 3, 4, 5];",
          "</script>",
          "",
          "<PinInput.Root count={cells.length} otp onValueComplete={submit}>",
          "  <PinInput.Label>Verification code</PinInput.Label>",
          "  <PinInput.Control>",
          "    {#each cells as index (index)}",
          "      <PinInput.Input {index} />",
          "    {/each}",
          "  </PinInput.Control>",
          "  <PinInput.HiddenInput />",
          "</PinInput.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Six-digit verification code",
        code: [
          'import { For } from "solid-js";',
          'import { PinInput } from "@moderno-ui/solid";',
          "",
          "const cells = [0, 1, 2, 3, 4, 5];",
          "",
          "<PinInput.Root count={cells.length} otp onValueComplete={submit}>",
          "  <PinInput.Label>Verification code</PinInput.Label>",
          "  <PinInput.Control>",
          "    <For each={cells}>{(index) => <PinInput.Input index={index} />}</For>",
          "  </PinInput.Control>",
          "  <PinInput.HiddenInput />",
          "</PinInput.Root>",
        ].join("\n"),
      },
    ],
  },

  Avatar: {
    react: [
      {
        title: "A person's picture with initials as the fallback",
        code: [
          'import { Avatar } from "@moderno-ui/react";',
          "",
          '<Avatar.Root size="lg">',
          "  <Avatar.Fallback>AL</Avatar.Fallback>",
          '  <Avatar.Image src="/ada.png" alt="Ada Lovelace" />',
          "</Avatar.Root>",
          '<Avatar.Root shape="square">',
          "  <Avatar.Fallback>MD</Avatar.Fallback>",
          "</Avatar.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A person's picture with initials as the fallback",
        code: [
          '<script setup lang="ts">',
          'import { Avatar } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Avatar.Root size="lg">',
          "    <Avatar.Fallback>AL</Avatar.Fallback>",
          '    <Avatar.Image src="/ada.png" alt="Ada Lovelace" />',
          "  </Avatar.Root>",
          '  <Avatar.Root shape="square">',
          "    <Avatar.Fallback>MD</Avatar.Fallback>",
          "  </Avatar.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A person's picture with initials as the fallback",
        code: [
          '<script lang="ts">',
          '  import { Avatar } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<Avatar.Root size="lg">',
          "  <Avatar.Fallback>AL</Avatar.Fallback>",
          '  <Avatar.Image src="/ada.png" alt="Ada Lovelace" />',
          "</Avatar.Root>",
          '<Avatar.Root shape="square">',
          "  <Avatar.Fallback>MD</Avatar.Fallback>",
          "</Avatar.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A person's picture with initials as the fallback",
        code: [
          'import { Avatar } from "@moderno-ui/solid";',
          "",
          '<Avatar.Root size="lg">',
          "  <Avatar.Fallback>AL</Avatar.Fallback>",
          '  <Avatar.Image src="/ada.png" alt="Ada Lovelace" />',
          "</Avatar.Root>",
          '<Avatar.Root shape="square">',
          "  <Avatar.Fallback>MD</Avatar.Fallback>",
          "</Avatar.Root>",
        ].join("\n"),
      },
    ],
  },

  Switch: {
    react: [
      {
        title: "An on/off setting that applies at once",
        code: [
          'import { Switch } from "@moderno-ui/react";',
          "",
          "<Switch.Root defaultChecked onCheckedChange={save}>",
          "  <Switch.Control>",
          "    <Switch.Thumb />",
          "  </Switch.Control>",
          "  <Switch.Label>Email notifications</Switch.Label>",
          "  <Switch.HiddenInput />",
          "</Switch.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "An on/off setting that applies at once",
        code: [
          '<script setup lang="ts">',
          'import { Switch } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Switch.Root default-checked @checked-change="save">',
          "    <Switch.Control>",
          "      <Switch.Thumb />",
          "    </Switch.Control>",
          "    <Switch.Label>Email notifications</Switch.Label>",
          "    <Switch.HiddenInput />",
          "  </Switch.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "An on/off setting that applies at once",
        code: [
          '<script lang="ts">',
          '  import { Switch } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Switch.Root defaultChecked onCheckedChange={save}>",
          "  <Switch.Control>",
          "    <Switch.Thumb />",
          "  </Switch.Control>",
          "  <Switch.Label>Email notifications</Switch.Label>",
          "  <Switch.HiddenInput />",
          "</Switch.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "An on/off setting that applies at once",
        code: [
          'import { Switch } from "@moderno-ui/solid";',
          "",
          "<Switch.Root defaultChecked onCheckedChange={save}>",
          "  <Switch.Control>",
          "    <Switch.Thumb />",
          "  </Switch.Control>",
          "  <Switch.Label>Email notifications</Switch.Label>",
          "  <Switch.HiddenInput />",
          "</Switch.Root>",
        ].join("\n"),
      },
    ],
  },

  RadioGroup: {
    react: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          'import { RadioGroup } from "@moderno-ui/react";',
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          '<script setup lang="ts">',
          'import { RadioGroup } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <RadioGroup.Root default-value="standard" @value-change="save">',
          "    <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '    <RadioGroup.Item value="standard">',
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>",
          "        Standard",
          "        <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "      </RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          '    <RadioGroup.Item value="express">',
          "      <RadioGroup.ItemControl />",
          "      <RadioGroup.ItemText>",
          "        Express",
          "        <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "      </RadioGroup.ItemText>",
          "      <RadioGroup.ItemHiddenInput />",
          "    </RadioGroup.Item>",
          "  </RadioGroup.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          '<script lang="ts">',
          '  import { RadioGroup } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "One option from a short list, each with a hint",
        code: [
          'import { RadioGroup } from "@moderno-ui/solid";',
          "",
          '<RadioGroup.Root defaultValue="standard" onValueChange={save}>',
          "  <RadioGroup.Label>Shipping</RadioGroup.Label>",
          '  <RadioGroup.Item value="standard">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Standard",
          "      <RadioGroup.ItemDescription>3–5 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          '  <RadioGroup.Item value="express">',
          "    <RadioGroup.ItemControl />",
          "    <RadioGroup.ItemText>",
          "      Express",
          "      <RadioGroup.ItemDescription>1–2 business days</RadioGroup.ItemDescription>",
          "    </RadioGroup.ItemText>",
          "    <RadioGroup.ItemHiddenInput />",
          "  </RadioGroup.Item>",
          "</RadioGroup.Root>",
        ].join("\n"),
      },
    ],
  },

  Toggle: {
    react: [
      {
        title: "A button that stays pressed, with an on/off indicator",
        code: [
          'import { Toggle } from "@moderno-ui/react";',
          "",
          "<Toggle.Root defaultPressed onPressedChange={save}>",
          '  <Toggle.Indicator fallback="☆">★</Toggle.Indicator>',
          "  Favorite",
          "</Toggle.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "A button that stays pressed, with an on/off indicator",
        code: [
          '<script setup lang="ts">',
          'import { Toggle } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <Toggle.Root default-pressed @pressed-change="save">',
          "    <Toggle.Indicator>",
          "      ★",
          "      <template #fallback>☆</template>",
          "    </Toggle.Indicator>",
          "    Favorite",
          "  </Toggle.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "A button that stays pressed, with an on/off indicator",
        code: [
          '<script lang="ts">',
          '  import { Toggle } from "@moderno-ui/svelte";',
          "</script>",
          "",
          "<Toggle.Root defaultPressed onPressedChange={save}>",
          "  <Toggle.Indicator>",
          "    {#snippet fallback()}☆{/snippet}",
          "    ★",
          "  </Toggle.Indicator>",
          "  Favorite",
          "</Toggle.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "A button that stays pressed, with an on/off indicator",
        code: [
          'import { Toggle } from "@moderno-ui/solid";',
          "",
          "<Toggle.Root defaultPressed onPressedChange={save}>",
          '  <Toggle.Indicator fallback="☆">★</Toggle.Indicator>',
          "  Favorite",
          "</Toggle.Root>",
        ].join("\n"),
      },
    ],
  },

  ToggleGroup: {
    react: [
      {
        title: "One pressed item, or several with multiple",
        code: [
          'import { ToggleGroup } from "@moderno-ui/react";',
          "",
          '<ToggleGroup.Root defaultValue={["left"]} onValueChange={save} aria-label="Text alignment">',
          '  <ToggleGroup.Item value="left">Left</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="center">Center</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="right">Right</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
          "",
          '<ToggleGroup.Root multiple variant="outline" aria-label="Text style">',
          '  <ToggleGroup.Item value="bold">Bold</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="italic">Italic</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "One pressed item, or several with multiple",
        code: [
          '<script setup lang="ts">',
          'import { ToggleGroup } from "@moderno-ui/vue";',
          "</script>",
          "",
          "<template>",
          '  <ToggleGroup.Root :default-value="[\'left\']" @value-change="save" aria-label="Text alignment">',
          '    <ToggleGroup.Item value="left">Left</ToggleGroup.Item>',
          '    <ToggleGroup.Item value="center">Center</ToggleGroup.Item>',
          '    <ToggleGroup.Item value="right">Right</ToggleGroup.Item>',
          "  </ToggleGroup.Root>",
          "",
          '  <ToggleGroup.Root multiple variant="outline" aria-label="Text style">',
          '    <ToggleGroup.Item value="bold">Bold</ToggleGroup.Item>',
          '    <ToggleGroup.Item value="italic">Italic</ToggleGroup.Item>',
          "  </ToggleGroup.Root>",
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "One pressed item, or several with multiple",
        code: [
          '<script lang="ts">',
          '  import { ToggleGroup } from "@moderno-ui/svelte";',
          "</script>",
          "",
          '<ToggleGroup.Root defaultValue={["left"]} onValueChange={save} aria-label="Text alignment">',
          '  <ToggleGroup.Item value="left">Left</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="center">Center</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="right">Right</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
          "",
          '<ToggleGroup.Root multiple variant="outline" aria-label="Text style">',
          '  <ToggleGroup.Item value="bold">Bold</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="italic">Italic</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "One pressed item, or several with multiple",
        code: [
          'import { ToggleGroup } from "@moderno-ui/solid";',
          "",
          '<ToggleGroup.Root defaultValue={["left"]} onValueChange={save} aria-label="Text alignment">',
          '  <ToggleGroup.Item value="left">Left</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="center">Center</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="right">Right</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
          "",
          '<ToggleGroup.Root multiple variant="outline" aria-label="Text style">',
          '  <ToggleGroup.Item value="bold">Bold</ToggleGroup.Item>',
          '  <ToggleGroup.Item value="italic">Italic</ToggleGroup.Item>',
          "</ToggleGroup.Root>",
        ].join("\n"),
      },
    ],
  },

  LineChart: {
    react: [
      {
        title: "Two-series line chart",
        code: [
          'import { LineChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "<LineChart width={520} height={260} series={series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Two-series line chart",
        code: [
          '<script setup lang="ts">',
          'import { LineChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <LineChart :width="520" :height="260" :series="series" :x-ticks="3" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Two-series line chart",
        code: [
          '<script lang="ts">',
          '  import { LineChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "  ];",
          "</script>",
          "",
          "<LineChart width={520} height={260} {series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Two-series line chart",
        code: [
          'import { LineChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Sessions", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "function SessionsChart() {",
          "  return <LineChart width={520} height={260} series={series} xTicks={3} yTicks={5} />;",
          "}",
        ].join("\n"),
      },
    ],
  },

  AreaChart: {
    react: [
      {
        title: "Single-series area chart",
        code: [
          'import { AreaChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "",
          "<AreaChart width={520} height={260} series={series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Single-series area chart",
        code: [
          '<script setup lang="ts">',
          'import { AreaChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <AreaChart :width="520" :height="260" :series="series" :x-ticks="3" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Single-series area chart",
        code: [
          '<script lang="ts">',
          '  import { AreaChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "  ];",
          "</script>",
          "",
          "<AreaChart width={520} height={260} {series} xTicks={3} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Single-series area chart",
        code: [
          'import { AreaChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Revenue", points: [{ x: 0, y: 8 }, { x: 1, y: 14 }, { x: 2, y: 11 }] },',
          "];",
          "",
          "function RevenueChart() {",
          "  return <AreaChart width={520} height={260} series={series} xTicks={3} yTicks={5} />;",
          "}",
        ].join("\n"),
      },
    ],
  },

  BarChart: {
    react: [
      {
        title: "Categorical bar chart",
        code: [
          'import { BarChart } from "@moderno-ui/react";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "",
          "<BarChart width={520} height={260} categories={categories} series={series} yTicks={5} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Categorical bar chart",
        code: [
          '<script setup lang="ts">',
          'import { BarChart } from "@moderno-ui/vue";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "</script>",
          "",
          "<template>",
          '  <BarChart :width="520" :height="260" :categories="categories" :series="series" :y-ticks="5" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Categorical bar chart",
        code: [
          '<script lang="ts">',
          '  import { BarChart } from "@moderno-ui/svelte";',
          "",
          '  const categories = ["Q1", "Q2", "Q3"];',
          '  const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "</script>",
          "",
          "<BarChart width={520} height={260} {categories} {series} yTicks={5} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Categorical bar chart",
        code: [
          'import { BarChart } from "@moderno-ui/solid";',
          "",
          'const categories = ["Q1", "Q2", "Q3"];',
          'const series = [{ name: "Revenue", values: [8, 14, 11] }];',
          "",
          "function RevenueByQuarter() {",
          "  return (",
          "    <BarChart width={520} height={260} categories={categories} series={series} yTicks={5} />",
          "  );",
          "}",
        ].join("\n"),
      },
    ],
  },

  ScatterChart: {
    react: [
      {
        title: "Scatter plot",
        code: [
          'import { ScatterChart } from "@moderno-ui/react";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "<ScatterChart width={520} height={260} series={series} radius={4} />",
        ].join("\n"),
      },
    ],
    vue: [
      {
        title: "Scatter plot",
        code: [
          '<script setup lang="ts">',
          'import { ScatterChart } from "@moderno-ui/vue";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "</script>",
          "",
          "<template>",
          '  <ScatterChart :width="520" :height="260" :series="series" :radius="4" />',
          "</template>",
        ].join("\n"),
      },
    ],
    svelte: [
      {
        title: "Scatter plot",
        code: [
          '<script lang="ts">',
          '  import { ScatterChart } from "@moderno-ui/svelte";',
          "",
          "  const series = [",
          '    { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "  ];",
          "</script>",
          "",
          "<ScatterChart width={520} height={260} {series} radius={4} />",
        ].join("\n"),
      },
    ],
    solid: [
      {
        title: "Scatter plot",
        code: [
          'import { ScatterChart } from "@moderno-ui/solid";',
          "",
          "const series = [",
          '  { name: "Samples", points: [{ x: 0, y: 12 }, { x: 1, y: 28 }, { x: 2, y: 22 }] },',
          "];",
          "",
          "function SamplesChart() {",
          "  return <ScatterChart width={520} height={260} series={series} radius={4} />;",
          "}",
        ].join("\n"),
      },
    ],
  },
};
