// Generated by pnpm gen (props-doc-components) from tooling/props-doc/src/components/*.ts. Do not edit by hand.
/**
 * Every component file in `components/`, sorted by slug, split into the lists
 * props-doc reads: `ENTRIES` (`manifest.ts`), `AGENT_COMPONENTS`
 * (`agent-manifest.ts`) and `AGENT_EXAMPLES` (`agent-examples.ts`).
 *
 * Static imports, not a glob or a `readdir`: the bins run under
 * `node --experimental-strip-types` and tsup bundles `agent-manifest` into
 * `dist`, and both only follow imports they can see.
 */
import { assembleComponents } from "./component-definition.ts";
import accordionComponent from "./components/accordion.ts";
import alertComponent from "./components/alert.ts";
import areaChartComponent from "./components/area-chart.ts";
import avatarComponent from "./components/avatar.ts";
import badgeComponent from "./components/badge.ts";
import barChartComponent from "./components/bar-chart.ts";
import buttonComponent from "./components/button.ts";
import calloutComponent from "./components/callout.ts";
import cardComponent from "./components/card.ts";
import checkboxComponent from "./components/checkbox.ts";
import chipComponent from "./components/chip.ts";
import dialogComponent from "./components/dialog.ts";
import dividerComponent from "./components/divider.ts";
import fieldComponent from "./components/field.ts";
import indicatorComponent from "./components/indicator.ts";
import lineChartComponent from "./components/line-chart.ts";
import numberInputComponent from "./components/number-input.ts";
import paginationComponent from "./components/pagination.ts";
import pinInputComponent from "./components/pin-input.ts";
import progressComponent from "./components/progress.ts";
import radioGroupComponent from "./components/radio-group.ts";
import scatterChartComponent from "./components/scatter-chart.ts";
import selectComponent from "./components/select.ts";
import skeletonComponent from "./components/skeleton.ts";
import sliderComponent from "./components/slider.ts";
import spinnerComponent from "./components/spinner.ts";
import switchComponent from "./components/switch.ts";
import tabsComponent from "./components/tabs.ts";
import toggleComponent from "./components/toggle.ts";
import toggleGroupComponent from "./components/toggle-group.ts";

export const { ENTRIES, AGENT_COMPONENTS, AGENT_EXAMPLES } = assembleComponents([
  accordionComponent,
  alertComponent,
  areaChartComponent,
  avatarComponent,
  badgeComponent,
  barChartComponent,
  buttonComponent,
  calloutComponent,
  cardComponent,
  checkboxComponent,
  chipComponent,
  dialogComponent,
  dividerComponent,
  fieldComponent,
  indicatorComponent,
  lineChartComponent,
  numberInputComponent,
  paginationComponent,
  pinInputComponent,
  progressComponent,
  radioGroupComponent,
  scatterChartComponent,
  selectComponent,
  skeletonComponent,
  sliderComponent,
  spinnerComponent,
  switchComponent,
  tabsComponent,
  toggleComponent,
  toggleGroupComponent,
]);
