<!-- Generated by pnpm gen (svelte-playground) from packages/svelte/playground/sections/*.svelte. Do not edit by hand. -->
<!--
  SSR playground — the Svelte twin of the React harness, and the proof of F3.5:
  this component renders server-only (no client: directive) to static HTML, i.e.
  it works as an Astro island with zero client runtime. `open` mounts the Dialog
  + Select popovers.

  It mounts one section per component. A section lives in
  `sections/<Name>.svelte` and says what its component proves on the server;
  `test/ssr/<slug>.ssr.test.ts` asserts that section's server string on its own.
-->
<script lang="ts">
  import Accordion from "./sections/Accordion.svelte";
  import Alert from "./sections/Alert.svelte";
  import Avatar from "./sections/Avatar.svelte";
  import Badge from "./sections/Badge.svelte";
  import Button from "./sections/Button.svelte";
  import Callout from "./sections/Callout.svelte";
  import Card from "./sections/Card.svelte";
  import Charts from "./sections/Charts.svelte";
  import Checkbox from "./sections/Checkbox.svelte";
  import Chip from "./sections/Chip.svelte";
  import Dialog from "./sections/Dialog.svelte";
  import Divider from "./sections/Divider.svelte";
  import Field from "./sections/Field.svelte";
  import Indicator from "./sections/Indicator.svelte";
  import NumberInput from "./sections/NumberInput.svelte";
  import Pagination from "./sections/Pagination.svelte";
  import PinInput from "./sections/PinInput.svelte";
  import Progress from "./sections/Progress.svelte";
  import RadioGroup from "./sections/RadioGroup.svelte";
  import Select from "./sections/Select.svelte";
  import Skeleton from "./sections/Skeleton.svelte";
  import Slider from "./sections/Slider.svelte";
  import Spinner from "./sections/Spinner.svelte";
  import Switch from "./sections/Switch.svelte";
  import Tabs from "./sections/Tabs.svelte";
  import Toggle from "./sections/Toggle.svelte";
  import ToggleGroup from "./sections/ToggleGroup.svelte";

  let { open = false }: { open?: boolean } = $props();
</script>

<main>
  <Accordion {open} />
  <Alert {open} />
  <Avatar {open} />
  <Badge {open} />
  <Button {open} />
  <Callout {open} />
  <Card {open} />
  <Charts {open} />
  <Checkbox {open} />
  <Chip {open} />
  <Dialog {open} />
  <Divider {open} />
  <Field {open} />
  <Indicator {open} />
  <NumberInput {open} />
  <Pagination {open} />
  <PinInput {open} />
  <Progress {open} />
  <RadioGroup {open} />
  <Select {open} />
  <Skeleton {open} />
  <Slider {open} />
  <Spinner {open} />
  <Switch {open} />
  <Tabs {open} />
  <Toggle {open} />
  <ToggleGroup {open} />
</main>
